Repository istio/test-infra, pull requests merged in 2018-09, with the labels that each got.

#963 Force all deployments to be in the prow node pool
  boskos/boskos-deployment.yaml
  boskos/janitor-deployment.yaml
  boskos/mason-deployment.yaml
  boskos/metrics-deployment.yaml
  boskos/reaper-deployment.yaml
  toolbox/metrics/cmd/deployment.yaml
Labels: approved, cla: yes, lgtm

#965 Use regex for branch spec
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.collab-gcp-identity.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.master.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.release-0.8.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.release-1.0.yaml
  prow/cluster/jobs/istio/api/istio.api.master.yaml
  prow/cluster/jobs/istio/api/istio.api.release-0.8.yaml
  prow/cluster/jobs/istio/istio/istio.istio.collab-gcp-identity.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-0.8.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.0.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.0.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.sds_api.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#966 Update Prow with tide fix for after_success jobs
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, cla: yes, lgtm

#967 Maintenance
  docker/istio_builders/CHANGELOG.md
  docker/istio_builders/Makefile
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.collab-gcp-identity.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.master.yaml
  prow/cluster/jobs/istio/api/istio.api.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.collab-gcp-identity.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-0.8.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.0.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  scripts/linux-install-software
  scripts/tools/linux-install-docker
  scripts/tools/linux-install-golang
Labels: approved, cla: yes, lgtm

#969 Experiment to replace bootstrap with pod utils
  docker/istio_builders/CHANGELOG.md
  docker/istio_builders/Makefile
  docker/istio_builders/istio_builder/entrypoint.sh
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/config.yaml
  prow/new-test.sh
Labels: approved, cla: yes, lgtm

#970 Update test infra jobs to use pod-utils
  docker/istio/test-infra/Dockerfile
  docker/istio/test-infra/Makefile
  docker/istio/test-infra/entrypoint.sh
  docker/istio/test-infra/install/install-bazel.sh
  docker/istio/test-infra/install/install-docker.sh
  docker/istio/test-infra/install/install-golang.sh
  docker/istio/test-infra/install/install-gosu.sh
  docker/istio/test-infra/install/install.sh
  prow/build-test.sh
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/config.yaml
  scripts/linters.sh
Labels: approved, cla: yes, lgtm

#973 Make istio-unit-tests required in master.
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#974 enable mcp test variants in prow
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#976 Update job-url for pod-utils jobs
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#978 Make ci/circleci: shellcheck required.
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#979 Fix configuration issues
  docker/istio/istio/Dockerfile
  docker/istio/istio/Makefile
  docker/istio/shared/prow-runner.sh
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#977 Update prow from fork
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, cla: yes, lgtm

#980 Updating to pod-utils for istio master
  docker/istio/istio/Makefile
  docker/istio/shared/prow-runner.sh
  docker/istio/shared/tools/install-helm.sh
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: cla: yes

#985 Using a different host path for test infra and proxy
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#984 One more try to get pod-utils to work for istio master
  docker/istio/istio/Makefile
  docker/istio/istio/install.sh
  docker/istio/shared/prow-runner.sh
  docker/istio/shared/tools/install-gosu.sh
  docker/istio/shared/tools/install-helm.sh
  docker/istio/test-infra/Dockerfile
  docker/istio/test-infra/Makefile
  docker/istio/test-infra/install.sh
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/config.yaml
Labels: approved, cla: yes, do-not-merge/hold
