Repository istio/test-infra, pull requests merged in 2018-11, with the labels that each got.

#1022 Adding local integration tests to post-submit.
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1024 Update lgtm config in plugins.yaml
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#1023 Fix Prow config for istio.io (renamed from istio.github.io)
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#1025 Enables GKE network policy
  boskos/configs.yaml
  boskos/gcp/config_test.go
  boskos/gcp/gke.go
  boskos/gcp/test-configs.yaml
Labels: approved, cla: yes, lgtm

#1020 Adds a CNI based e2e prow test
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1027 Update prow with latest from sebastienvas/test-infra@master
  Gopkg.lock
  boskos/gcp/BUILD.bazel
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  vendor/k8s.io/test-infra/prow/plugins/lgtm/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/lgtm/lgtm.go
  vendor/k8s.io/test-infra/prow/plugins/plugins.go
Labels: approved, cla: yes, lgtm

#1028 Update sticky lgtm config.
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#1021 change timeout for proxy postsubmit for master to 2 hours
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
Labels: approved, cla: yes, lgtm

#1030 run proxy postsubmit, remove green build job, sds api
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.sds_api.yaml
Labels: approved, cla: yes, lgtm

#1031 Update toolbox to support codecov diff.
  toolbox/githubctl/main.go
  toolbox/pkg_check/main.go
  toolbox/pkg_check/main_test.go
Labels: approved, cla: yes, lgtm

#1032 Bump up proxy postsumbit timeout in release-1.1.
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.1.yaml
Labels: approved, cla: yes, lgtm

#1033 Adding threshold as a flag to pkg_check
  toolbox/githubctl/main.go
  toolbox/pkg_check/main.go
Labels: approved, cla: yes, lgtm

#1034 Update boskos deployment
  boskos/janitor-deployment.yaml
  boskos/mason-deployment.yaml
Labels: approved, cla: yes, lgtm

#1036 Moving k8s integration tests to postsubmit
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
Labels: approved, cla: yes, lgtm

#1035 Minor fix in returned message
  toolbox/util/githubClient.go
Labels: approved, cla: yes, lgtm, ok-to-test

#1037 Added new resources and fix Metrics and Reaper deployments
  boskos/mason-deployment.yaml
  boskos/metrics-deployment.yaml
  boskos/reaper-deployment.yaml
  boskos/resources.yaml
Labels: approved, cla: yes, lgtm

#1039 Adding k8s integration test to master presubmit
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1038 rename build-tests to release-test and make it required
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
Labels: approved, cla: yes, lgtm

#1040 Adding more clusters to Prow E2E tests.
  boskos/resources.yaml
Labels: approved, cla: yes, lgtm

#1041 Making integration tests using local env required.
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1042 Making pkg_check return error code.
  toolbox/pkg_check/main.go
  toolbox/pkg_check/main_test.go
Labels: approved, cla: yes, lgtm

#1043 config for testing run_if_changed
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.master.yaml
Labels: approved, cla: yes, lgtm

#1044 run tests if test dir changes
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.master.yaml
  toolbox/githubctl/main.go
Labels: approved, cla: yes, lgtm

#1045 add min profile to post submit
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
Labels: approved, cla: yes, lgtm

#1046 change daily release config
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.master.yaml
Labels: approved, cla: yes, lgtm

#1048 add secrets for daily-releases config
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.master.yaml
Labels: approved, cla: yes, lgtm

#1049 Making upgrade tests required in release-1.0.
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.release-1.0.yaml
Labels: approved, cla: yes, lgtm

#1050 Making upgrade test required for release-1.1
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.master.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.release-1.0.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.release-1.1.yaml
Labels: approved, cla: yes, lgtm

#1051 Adding html report parsing to pkg_check.
  toolbox/pkg_check/main.go
  toolbox/pkg_check/main_test.go
Labels: approved, cla: yes, lgtm

#1052 test branch config for development
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.krishna-test.yaml
Labels: approved, cla: yes, lgtm

#1053 fix config
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.krishna-test.yaml
Labels: approved, cla: yes, lgtm

#1054 Adding threshold override to pkg_check
  toolbox/pkg_check/main.go
  toolbox/pkg_check/main_test.go
Labels: approved, cla: yes, lgtm

#1055 fix test config
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.krishna-test.yaml
Labels: approved, cla: yes, lgtm

#1056 Fix project creation script
  scripts/set-boskos-project.sh
Labels: approved, cla: yes, lgtm

#1057 Skip commment in threshold file
  toolbox/pkg_check/main.go
  toolbox/pkg_check/main_test.go
Labels: approved, cla: yes, lgtm

#1058 Making threshold file parsing more robust
  toolbox/pkg_check/main.go
  toolbox/pkg_check/main_test.go
Labels: approved, cla: yes, lgtm

#1059 fix test config
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.krishna-test.yaml
Labels: approved, cla: yes, lgtm

#1060 test config for test branch
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.krishna-test.yaml
Labels: approved, cla: yes, lgtm

#1061 test config for test branch
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.krishna-test.yaml
Labels: approved, cla: yes, lgtm

#1062 add trigger for release step
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.krishna-test.yaml
Labels: approved, cla: yes, lgtm

#1063 add trigger for release
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.krishna-test.yaml
Labels: approved, cla: yes, lgtm

#1065 adding minProfile test to pre-submit for easy testing
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
Labels: cla: yes

#1067 testing changes for krishna-test branch
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.krishna-test.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1068 testing krishna-test
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.krishna-test.yaml
Labels: approved, cla: yes, lgtm

#1069 fix githubctl to use specific paths for monthly/daily
  toolbox/githubctl/main.go
Labels: approved, cla: yes, lgtm

#1070 testing krishna-test fix script name
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.krishna-test.yaml
Labels: approved, cla: human-approved, cla: yes, lgtm

#1071 krishna-test branch use different scripts for daily/monthly
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.krishna-test.yaml
  toolbox/githubctl/main.go
Labels: approved, cla: yes, lgtm

#1072 fix krishna-test branch config
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.krishna-test.yaml
Labels: approved, cla: yes, lgtm

#1074 Using cert-manager to renew Prow certs
  prow/cluster/cert-manager/README.md
  prow/cluster/cert-manager/cluster-issuer.yaml
  prow/cluster/cert-manager/rbac-config.yaml
  prow/cluster/cert-manager/tls-ing.yaml
Labels: approved, cla: yes, lgtm

#1075 Disable merge bot in istio/istio master per TOC
  prow/config.yaml
Labels: approved, cla: yes, lgtm
