Repository istio/test-infra, pull requests merged in 2018-05, with the labels that each got.

#822 add git_branches for green build and update bot
  prow/config.yaml
  prow/test-infra-update-deps.sh
  toolbox/deps_update/main.go
Labels: approved, cla: yes, lgtm

#823 use baseBranch for finding dependency sha
  toolbox/deps_update/main.go
  toolbox/metrics/buildFreshness/buildFreshness.go
  toolbox/util/dependency.go
Labels: approved, cla: yes, lgtm

#824 disable bot update on release branch
  prow/test-infra-update-deps.sh
Labels: cla: yes

#826 enable update bot for istio repo
  prow/test-infra-update-deps.sh
Labels: cla: yes

#827 enable update bot for istio repo
  prow/test-infra-update-deps.sh
Labels: cla: yes

#829 run update for istio on release* only
  prow/test-infra-update-deps.sh
  toolbox/util/githubClient.go
Labels: cla: yes

#828 Run bookinfo prow tests in parallel (v1alpha1 and v1alpha3)
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#831 run proxy update earlier to istio
  prow/test-infra-update-deps.sh
Labels: cla: yes

#832 return after running istio
  prow/test-infra-update-deps.sh
Labels: cla: yes

#830 Longer e2e timeout to avoid premature abortion
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#834 Remove kubeconfig for unit tests since its not being used anyway
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#835 Revert "Remove kubeconfig for unit tests since its not being used anyway"
  prow/config.yaml
Labels: cla: yes

#819 Get Latest Green SHA to Kick off Release
  toolbox/githubctl/BUILD.bazel
  toolbox/githubctl/README.md
  toolbox/githubctl/main.go
  toolbox/util/commonUtils.go
  toolbox/util/githubClient.go
Labels: approved, cla: yes, lgtm

#837 Sisyphus rerun stops on one green exec
  sisyphus/sisyphusd.go
  sisyphus/sisyphusd_test.go
  sisyphus/test_data/expectedFlakeStats.json
  sisyphus/test_data/job-1.json
Labels: approved, cla: yes, lgtm

#838 add release 0.7
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#840 Fix workspace
  WORKSPACE
Labels: approved, cla: yes, lgtm

#841 add istio-pilot-e2e-envoyv2-v1alpha3 as post submit test
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#844 Enable testing version of tide on istio and proxy
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#845 Fixing branch protection settings
  prow/config.yaml
Labels: approved, cla: yes

#846 Update version of tide
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#849 Adds 1.10 cluster for testing
  boskos/configs.yaml
  boskos/resources.yaml
Labels: approved, cla: yes, lgtm

#848 Update Prow
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, cla: yes

#836 Push presubmit results to different GCS path so testgrid could multiplex
  toolbox/ci2gubernator/README.md
  toolbox/ci2gubernator/lib/ci2gubernator.go
  toolbox/ci2gubernator/main.go
Labels: approved, cla: yes, lgtm

#851 remove depreacted close reopen plugins in favor of lifecycle
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#850 Adds new postsubmits for k8s 1.10
  prow/config.yaml
Labels: approved, cla: yes

#852 Update branch protections
  prow/config.yaml
Labels: approved, cla: yes

#853 Enable push alert for test-infra
  prow/cluster/hook_deployment.yaml
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#855 actually create the 1.10 pool
  boskos/resources.yaml
Labels: approved, cla: yes, lgtm

#856 Fix typo in config
  boskos/configs.yaml
Labels: approved, cla: yes, lgtm

#860 Update branch protection to use netlify
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#859 Force to use latest 1.9 version
  scripts/update-e2e-cluster.sh
Labels: approved, cla: yes, lgtm
