Repository istio/test-infra, pull requests merged in 2018-10, with the labels that each got.

#990 Remove kubeconfig since cluster were deleted
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.collab-gcp-identity.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.master.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.release-0.8.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.release-1.0.yaml
  prow/cluster/jobs/istio/istio/istio.istio.collab-gcp-identity.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-0.8.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.0.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#991 Adding daily-upgrade-tests.
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.master.yaml
Labels: approved, cla: yes, lgtm

#992 Making perf test optional in release-1.0 as well.
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.release-1.0.yaml
Labels: approved, cla: yes, lgtm

#994 Use pod-utils for upgrade test
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.master.yaml
Labels: approved, cla: yes, lgtm

#995 Adding upgrade and downgrade jobs.
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.master.yaml
Labels: approved, cla: yes, lgtm

#998 Add zip to istio-builder docker image
  docker/istio/istio/install.sh
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.master.yaml
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.release-1.0.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1002 Fix buildifer issue
  BUILD.bazel
  WORKSPACE
  go_vendor_repositories.bzl
  scripts/linters.sh
Labels: approved, cla: yes, lgtm

#1001 adding istioctl test job to release qualification.
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.master.yaml
Labels: approved, cla: yes, lgtm

#1000 Rename 1.10 specific test to latest (1.11)
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1003 Adding a util to get PR info in CSV
  toolbox/branch_pr/BUILD.bazel
  toolbox/branch_pr/main.go
Labels: approved, cla: yes, lgtm

#1004 Making lint not required until it is fixed.
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1005 Modify Tide URL to a valid one
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1007 Fixing prow util dependencies
  prow/config.yaml
Labels: approved, cla: yes

#1006 Adding istioctl test to release-1.0
  prow/cluster/jobs/istio-releases/daily-release/istio-releases.daily-release.release-1.0.yaml
Labels: approved, cla: yes, lgtm

#1008 Making lint required
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1010 Blocking bot merge in master
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1011 Really blocking merge in master
  prow/config.yaml
Labels: cla: yes

#1013 Adding integration tests to release-1.1.
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
Labels: approved, cla: yes, lgtm

#1014 Adding missing label
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
Labels: approved, cla: yes, lgtm

#1015 Unblock master
  prow/config.yaml
Labels: approved, cla: yes, lgtm
