Repository istio/test-infra, pull requests merged in 2018-03, with the labels that each got.

#715 Update all images with latest version of bazel
  docker/istio_builders/CHANGELOG.md
  docker/istio_builders/Makefile
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#716 Update prow images to use golang 1.10
  docker/istio_builders/CHANGELOG.md
  docker/istio_builders/Makefile
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#717 Allowing empty bucket for testing
  toolbox/pkg_check/main.go
  toolbox/pkg_check/main_test.go
Labels: approved, cla: yes, lgtm

#720 Add retest and test all for istio-unit-tests
  prow/config.yaml
Labels: cla: yes, lgtm

#721 Update update cluster script to use latest gke version
  scripts/update-e2e-cluster.sh
Labels: approved, cla: yes, lgtm

#709 add comment field in istio.deps
  toolbox/util/dependency.go
Labels: approved, cla: yes, lgtm

#722 old cert not supported anymore
  scripts/update-e2e-cluster.sh
Labels: approved, cla: yes, lgtm

#718 Adds function to create requirement from report
  toolbox/pkg_check/main.go
  toolbox/pkg_check/main_test.go
Labels: approved, cla: yes, lgtm

#723 Bind tester service account to clusteradmin.
  scripts/update-e2e-cluster.sh
Labels: approved, cla: yes, lgtm

#725 fix kubectl command
  scripts/update-e2e-cluster.sh
Labels: approved, cla: yes, lgtm

#724 creating cluster admin role on right cluster
  scripts/update-e2e-cluster.sh
Labels: approved, cla: yes, lgtm

#726 remove ISTIOCTL_URL from greenBuild.VERSION
  toolbox/githubctl/main.go
Labels: cla: yes

#727 change title of bot generated PRs to lessen confusion
  toolbox/deps_update/main.go
Labels: approved, cla: yes, lgtm

#730 Skip updating dependency file if it is not specified
  toolbox/deps_update/main.go
Labels: approved, cla: yes, lgtm

#732 Adding FixIt Metric Tool
  toolbox/fixit/BUILD.bazel
  toolbox/fixit/main.go
  toolbox/release_note_collector/main.go
  toolbox/util/commonUtils.go
  toolbox/util/githubClient.go
Labels: approved, cla: yes, kind/fixit, lgtm

#734 Fix bugs for closed issue count and reviewr count
  toolbox/fixit/main.go
Labels: approved, cla: yes, kind/fixit, lgtm

#728 Adds flags go pkg_check to set build id and jobName
  Gopkg.lock
  go_vendor_repositories.bzl
  toolbox/pkg_check/BUILD.bazel
  toolbox/pkg_check/main.go
  toolbox/pkg_check/main_test.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_test.go
Labels: approved, cla: yes, lgtm

#729 Install clang-5.0 for proxy build
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  prow/config.yaml
  scripts/linux-install-software
  scripts/tools/linux-install-clang
Labels: cla: yes

#735 Add a storage interface and add a service account for cloud storage
  boskos/cmd/mason/main.go
  boskos/cmd/mason_client/main.go
  boskos/gcp/config.go
  scripts/linters.sh
  toolbox/pkg_check/main.go
  toolbox/pkg_check/main_test.go
Labels: cla: yes

#736 Update script to create cluster and update boskos resources
  boskos/resources.yaml
  scripts/set-boskos-project.sh
Labels: approved, cla: yes, lgtm

#740 New prowbazel image 0.4.6 using latest go-junit-report
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#739 Update prow
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, cla: yes, lgtm

#743 Update OWNERS
  OWNERS
  prow/OWNERS
  toolbox/OWNERS
  vendor/k8s.io/test-infra/OWNERS
Labels: approved, cla: yes, lgtm

#742 Update Prow to run v1alpha3 pilot tests
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#744 Disable approve in mungegithub, enable in Prow
  mungegithub/deployment/auth/configmap.yaml
  mungegithub/deployment/istio/configmap.yaml
  mungegithub/deployment/mixer/configmap.yaml
  mungegithub/deployment/mixerclient/configmap.yaml
  mungegithub/deployment/pilot/configmap.yaml
  mungegithub/deployment/proxy/configmap.yaml
  mungegithub/deployment/test-infra/configmap.yaml
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#746 Remove mixerclient
  mungegithub/deployment/mixerclient/configmap.yaml
Labels: approved, cla: yes, lgtm

#747 Enabled tide and remove test infra in mungegithub
  mungegithub/deployment/test-infra/configmap.yaml
  prow/Makefile
  prow/cluster/deck_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/needs-rebase_service.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tide_service.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#748 Adds blunderbuss to automatically assign reviewers
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#749 fix binary path for update deps
  prow/test-infra-update-deps.sh
Labels: approved, cla: yes, lgtm

#751 Using preset in prow config.yaml to remove duplicate code
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#752 Update required test for istio
  mungegithub/deployment/istio/configmap.yaml
Labels: approved, cla: yes, lgtm

#750 disable more plugins in mungegithub
  mungegithub/deployment/istio/configmap.yaml
  mungegithub/deployment/proxy/configmap.yaml
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#753 Enable approve + tide for istio.github.io
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#754 Upgrading Mason
  Gopkg.lock
  Gopkg.toml
  boskos/boskos-deployment.yaml
  boskos/cmd/mason/BUILD.bazel
  boskos/cmd/mason/main.go
  boskos/cmd/mason_client/main.go
  boskos/janitor-deployment.yaml
  boskos/mason-deployment.yaml
  boskos/reaper-deployment.yaml
  go_vendor_repositories.bzl
  toolbox/fixit/BUILD.bazel
  vendor/k8s.io/test-infra/.bazelrc
  vendor/k8s.io/test-infra/.gitignore
  vendor/k8s.io/test-infra/CODEOWNERS
  vendor/k8s.io/test-infra/Gopkg.lock
  vendor/k8s.io/test-infra/Gopkg.toml
  vendor/k8s.io/test-infra/OWNERS
  vendor/k8s.io/test-infra/README.md
  vendor/k8s.io/test-infra/WORKSPACE
  vendor/k8s.io/test-infra/boskos/Makefile
  vendor/k8s.io/test-infra/boskos/boskos.go
  vendor/k8s.io/test-infra/boskos/client/client.go
  vendor/k8s.io/test-infra/boskos/common/common.go
  vendor/k8s.io/test-infra/boskos/common/mason_config.go
  vendor/k8s.io/test-infra/boskos/mason/README.md
  vendor/k8s.io/test-infra/boskos/mason/client.go
  vendor/k8s.io/test-infra/boskos/mason/mason.go
  vendor/k8s.io/test-infra/boskos/mason/mason_test.go
  vendor/k8s.io/test-infra/boskos/mason/test-configs.yaml
  vendor/k8s.io/test-infra/boskos/mason/test-resources.yaml
  vendor/k8s.io/test-infra/boskos/ranch/ranch.go
  vendor/k8s.io/test-infra/boskos/resources.json
  vendor/k8s.io/test-infra/boskos/resources.yaml
  vendor/k8s.io/test-infra/boskos/server_client_test.go
  vendor/k8s.io/test-infra/boskos/storage/storage.go
  vendor/k8s.io/test-infra/image.bzl
  vendor/k8s.io/test-infra/test_infra.bzl
Labels: cla: yes

#688 Job-level flakyness detection by rerun
  sisyphus/BUILD.bazel
  sisyphus/README.md
  sisyphus/alert.go
  sisyphus/branchProtector.go
  sisyphus/ci.go
  sisyphus/ci_test.go
  sisyphus/istio_deployment/BUILD.bazel
  sisyphus/istio_deployment/main.go
  sisyphus/istio_deployment/sisyphus-deployment.yaml
  sisyphus/istio_deployment/update.sh
  sisyphus/sisyphusd.go
  sisyphus/sisyphusd_test.go
  sisyphus/storage.go
  sisyphus/test_data/BUILD.bazel
  sisyphus/test_data/expectedFlakeStats.json
  sisyphus/test_data/job-1.json
  sisyphus/test_data/mock-finished.json
  sisyphus/test_data/mock-latest-build.txt
  sisyphus/test_data/mock-started.json
  toolbox/oncall_alert/main.go
  toolbox/oncall_alert/update.sh
  toolbox/util/commonUtils.go
  toolbox/util/gcsClient.go
  toolbox/util/githubUtils.go
Labels: approved, cla: yes, lgtm

#755 Add more boskos resources
  boskos/cmd/mason/main.go
  boskos/mason-deployment.yaml
  boskos/resources.yaml
Labels: approved, cla: yes, lgtm

#756 run update-dep.sh
  sisyphus/BUILD.bazel
  sisyphus/istio_deployment/BUILD.bazel
Labels: approved, cla: yes, lgtm

#757 Trying using required checks only
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#759 Fix config and update tide deployment
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#761 Disabling github approval as it is confusing
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#741 Update coverage metric to get data directly from GCS
  Gopkg.lock
  WORKSPACE
  toolbox/metrics/BUILD.bazel
  toolbox/metrics/Makefile
  toolbox/metrics/cmd/BUILD.bazel
  toolbox/metrics/cmd/deployment.yaml
  toolbox/metrics/cmd/main.go
  toolbox/metrics/cmd/service.yaml
  toolbox/metrics/coverage/BUILD.bazel
  toolbox/metrics/coverage/coverage.go
  toolbox/metrics/coverage/coverage_test.go
  toolbox/metrics/coverage/storage.go
  toolbox/metrics/main.go
  toolbox/metrics/metrics.go
  toolbox/metrics/metrics_fetcher.yaml
  toolbox/metrics/metrics_test.go
Labels: approved, cla: yes, lgtm

#762 Update Tide version
  prow/cluster/tide_deployment.yaml
Labels: approved, cla: yes, lgtm

#763 Update tide for real
  prow/cluster/tide_deployment.yaml
Labels: approved, cla: yes, lgtm

#765 Force non bazel job to the non build pool
  prow/config.yaml
Labels: cla: yes
