Repository istio/test-infra, pull requests merged in 2019-10, with the labels that each got.

#1870 Don't hide installer, checkout istio
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/config/jobs/installer.yaml
Labels: cla: yes, size/XS

#1871 Add Slack reporter
  prow/config.yaml
Labels: cla: yes, ok-to-test, size/S

#1872 One more installer fix
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/config/jobs/installer.yaml
Labels: cla: yes, size/XS

#1874 Remove circleci from installer repo
  prow/config.yaml
Labels: cla: yes, size/XS

#1865 Explicitly use cookie-secret flag and fix warning.
  prow/cluster/deck_deployment.yaml
Labels: cla: yes, size/XS

#1875 Make installer jobs required
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/config/jobs/installer.yaml
Labels: cla: yes, size/XS

#1873 Add per-commit build for istio/istio
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1877 Add optional gencheck jobs in a number of repos.
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/test-infra.yaml
Labels: cla: yes, size/M

#1878 Cleanup CNI jobs.
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#1879 Fix the gen-check target.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#1880 Update to latest build-tools container
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tests.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#1883 Add an e2e test for release-builder
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/jobs/release-builder.yaml
Labels: cla: yes, size/XS

#1884 Use the old builder image for publish test
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/jobs/release-builder.yaml
Labels: cla: yes, size/XS

#1887 Add a bunch of optional hidden jobs using build-tools on istio/istio.
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/L

#1888 Remove deprecated elide_skipped_contexts value
  prow/plugins.yaml
Labels: cla: yes, size/XS

#1886 Ensure go.mod is up to date before checkin.
  Makefile.core.mk
Labels: cla: yes, size/XS

#1891 Move a few jobs to the build-tools container.
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1892 Update to latest container.
  prow/cluster/jobs/istio/istio/istio.istio.bt.gen.yaml
  prow/config/jobs/istio-bt.yaml
Labels: cla: yes, size/XS

#1893 CNI: Rename make target from prow-e2e to e2e
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#1894 Switch all jobs that passed in pre & postsubmits to the build-tools container.
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#1895 Use build tools for release-builder
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/jobs/release-builder.yaml
Labels: cla: yes, size/XS

#1896 Remove jobs that have been successfully converted to the build-tools container
  prow/cluster/jobs/istio/istio/istio.istio.bt.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio-bt.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/L

#1899 Move more passing jobs to the build-tools container.
  prow/cluster/jobs/istio/istio/istio.istio.bt.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio-bt.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1898 `install` misnamed - should be `test`
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#1901 Let's see if the latest container helps more jobs pass.
  prow/cluster/jobs/istio/istio/istio.istio.bt.gen.yaml
  prow/config/jobs/istio-bt.yaml
Labels: cla: yes, size/XS

#1902 Move 2 more passing jobs to the build-tools container.
  prow/cluster/jobs/istio/istio/istio.istio.bt.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio-bt.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#1897 Add kind capabilities for multicluster/dashboard
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1903 Trim the set of jobs on istio/istio a bit
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#1904 Move remaining istio/istio jobs to the build-tools container.
  prow/cluster/jobs/istio/istio/istio.istio.bt.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio-bt.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/M

#1905 Delete an obsolete set of jobs.
  prow/cluster/jobs/istio/api/istio.api.release-0.8.yaml
Labels: cla: yes, size/M

#1906 Delete old cruft.
  k8s/bazel-remote/deployment.yaml
  k8s/bazel-remote/services.yaml
  k8s/hazelcast/deployment.yaml
  k8s/hazelcast/hazelcast.yaml
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
  prow/cluster/jobs/istio/istio/update-prow-staging.sh
Labels: cla: yes, size/XXL

#1907 Delete another crufty set of jobs.
  prow/cluster/jobs/istio/istio/istio.istio.collab-galley.yaml
  prow/config.yaml
  prow/config/config_test.go
Labels: cla: yes, size/XL

#1890 Add "genjobs" CLI tool.
  go.mod
  prow/cmd/genjobs/README.md
  prow/cmd/genjobs/genjobs.go
Labels: cla: yes, size/L

#1908 Trigger container rebuild if any of the tools change.
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.yaml
  prow/config/jobs/api.yaml
Labels: cla: yes, size/XS

#1911 build the operator container on each commit
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/XS

#1912 Fix typo in make docker.all
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/XS

#1913 Use the latest build container for the operator repo.
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/XS

#1914 run dockerd when building and pushing images.
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/XS

#1910 Add a periodic job to automatically suggest Prow bumps.
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/M

#1918 Make rebuilding of containers a bit more aggressive.
  prow/cluster/jobs/istio/tools/istio.tools.yaml
Labels: cla: yes, size/XS

#1917 Bump prow from v20190927-a9e239ad8 to v20191008-bbd30bc09
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1919 Use docker-capable entrypoint
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/S

#1915 Bump test CPU requests
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1922 Revert "`install` misnamed `test` (#1898)"
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#1916 Update to latest build container
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tests.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#1885 Support client certificate in kubeconfig
  boskos/gcp/gcloud.go
  boskos/gcp/gke.go
  go.mod
Labels: cla: yes, ok-to-test, size/L

#1925 Make release-builder required and sufficient resources
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/jobs/release-builder.yaml
Labels: cla: yes, size/S

#1920 Bump prow from v20191008-bbd30bc09 to v20191010-78fe9feb7
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1926 Update a few things.
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.collab-gce-identity.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/config.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/XL

#1924 Refine "genjobs" CLI and documentation
  prow/cmd/genjobs/README.md
  prow/cmd/genjobs/genjobs.go
Labels: cla: yes, size/M

#1927 Bump prow from v20191010-78fe9feb7 to v20191011-80f304f54
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1929 Switch a bunch of periodic jobs to the build-tools container.
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/XS

#1930 Revert two periodic jobs back to the istio-builder container for now.
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/XS

#1909 Add benchmark test to periodic job
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/M

#1928 Improve job specs
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.3.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/README.md
  prow/config/cmd/generate.go
  prow/config/generate.go
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.3.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio-1.3.yaml
  prow/config/jobs/istio.io-1.3.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator-1.3.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg-1.3.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tests.yaml
  prow/config/jobs/tools.yaml
  prow/config/testdata/simple.gen.yaml
Labels: cla: yes, size/XL

#1932 Add a job for istio.io tests
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1931 Bump prow from v20191011-80f304f54 to v20191014-5b6eb77e5
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1934 Fix istioio target
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1935 Migrate to default_decoration_configs
  go.mod
  go.sum
  prow/config.yaml
  prow/config/config_test.go
Labels: cla: yes, size/L

#1939 Bump prow from v20191014-5b6eb77e5 to v20191015-68dd384c9
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1941 Add run_if_changed support to job gen
  prow/config/generate.go
  prow/config/testdata/simple.gen.yaml
  prow/config/testdata/simple.yaml
Labels: cla: yes, size/S

#1940 Generated jobs for release-1.4 branch
  prow/cluster/jobs/istio/api/istio.api.release-1.4.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.4.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.4.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.4.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.4.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.release-1.4.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.4.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.4.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.4.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.4.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.4.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.4.gen.yaml
  prow/config/generate.go
  prow/config/jobs/api-1.4.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/client-go-1.4.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.4.yaml
  prow/config/jobs/common-files-1.4.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/gogo-genproto-1.4.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/installer-1.4.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio-1.4.yaml
  prow/config/jobs/istio.io-1.4.yaml
  prow/config/jobs/operator-1.4.yaml
  prow/config/jobs/pkg-1.4.yaml
  prow/config/jobs/release-builder-1.4.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/tools-1.4.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/XL

#1942 Add proxy and tools 1.4 config
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml
  prow/cluster/jobs/istio/tools/istio.tools.yaml
Labels: cla: yes, size/L

#1943 Add jobs for trigger warnings
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/generate.go
  prow/config/jobs/release-builder.yaml
  prow/config/testdata/simple.gen.yaml
Labels: cla: yes, size/S

#1936 Add release-1.4 branch protection
  prow/config.yaml
  prow/config/config_test.go
Labels: cla: yes, size/S

#1946 Bump prow from v20191015-68dd384c9 to v20191015-dfc1766ef
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1944 Add release trigger
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/generate.go
  prow/config/jobs/release-builder.yaml
Labels: cla: yes, size/S

#1933 Implement operator e2e
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/XS

#1950 Bump prow from v20191015-dfc1766ef to v20191017-af5797562
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1951 Update clang, libc++, and Bazel in prowbazel images.
  docker/istio/shared/tools/install-bazel.sh
  docker/istio/shared/tools/install-clang.sh
  docker/istio/shared/tools/install-libcxx.sh
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  scripts/tools/linux-install-bazel
  scripts/tools/linux-install-clang
Labels: cla: yes, size/S

#1952 Update testgrid
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  testgrid/default.yaml
  testgrid/istio.gen.yaml
Labels: cla: yes, size/M

#1954 increase timeout for benchmark job
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/XS

#1956 Use prowbazel:0.5.11 in istio/proxy master and release-1.4.
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml
Labels: cla: yes, size/S

#1957 Revert "Use prowbazel:0.5.11 in istio/proxy master and release-1.4."
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml
Labels: cla: yes, size/S

#1955 Kill the master release pipeline
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
Labels: cla: yes, size/L

#1945 Hide gencheck for operator
  prow/cluster/jobs/istio/operator/istio.operator.release-1.4.gen.yaml
  prow/config/jobs/operator-1.4.yaml
Labels: cla: yes, size/XS

#1959 Upgrade to golang 1.13.3
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.4.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.4.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.4.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.4.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.4.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.release-1.4.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.4.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.4.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.4.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.4.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.4.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.4.gen.yaml
  prow/config/generate.go
  prow/config/jobs/api-1.4.yaml
  prow/config/jobs/client-go-1.4.yaml
  prow/config/jobs/cni-1.4.yaml
  prow/config/jobs/common-files-1.4.yaml
  prow/config/jobs/gogo-genproto-1.4.yaml
  prow/config/jobs/installer-1.4.yaml
  prow/config/jobs/istio-1.4.yaml
  prow/config/jobs/istio.io-1.4.yaml
  prow/config/jobs/operator-1.4.yaml
  prow/config/jobs/pkg-1.4.yaml
  prow/config/jobs/release-builder-1.4.yaml
  prow/config/jobs/tools-1.4.yaml
Labels: cla: yes, size/S

#1960 Update golang to 1.12.12 for 1.2 release
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.2.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.2.yaml
Labels: cla: yes, size/XS

#1958 Install clang and libc++ from the official releases.
  docker/istio/shared/tools/install-clang.sh
  docker/istio/shared/tools/install-libcxx.sh
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  scripts/tools/linux-install-clang
Labels: cla: yes, size/L

#1962 update decoration timeout overwrite for benchmark job
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/XS

#1964 Fix lint
  toolbox/githubctl/README.md
Labels: cla: yes, size/M

#1961 Retire Linux jobs for istio/proxy on CircleCI.
  prow/config.yaml
Labels: cla: yes, size/XS

#1963 Bump prow from v20191017-af5797562 to v20191018-2ae771e3e
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1965 Use prowbazel:0.5.12 in istio/proxy master and release-1.4.
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml
Labels: cla: yes, size/S

#1966 Make the gencheck job mandatory for the operator repo.
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/XS

#1968 fix flaky metrics test
  toolbox/metrics/metrics_test.go
Labels: cla: yes, size/XS

#1967 Bump build tools
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/generate.go
Labels: cla: yes, size/XS

#1947 Add benchmark jobs for release 1.3, 1.4
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/M

#1971 Add docker support for release builder
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/jobs/release-builder.yaml
Labels: cla: yes, size/XS

#1953 Clean up boskos resources
  boskos/cluster/metrics-deployment.yaml
  boskos/cluster/reaper-deployment.yaml
  boskos/resources.yaml
Labels: cla: yes, size/M

#1974 Make release docker credentials not read only
  prow/config.yaml
Labels: cla: yes, size/XS

#1975 Bump prow from v20191018-2ae771e3e to v20191021-d0a687bb7
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1970 Add "post-test-infra-push-prowbazel" to push prowbazel image
  prow/Makefile.gcloud.mk
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1978 Bump prow from v20191021-d0a687bb7 to v20191022-7c8165546
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1977 post-test-infra-push-prowbazel
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/XS

#1979 Add a postsubmit job for doc tests.
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1969 Add "Crier" deployment
  prow/cluster/crier_deployment.yaml
  prow/cluster/crier_rbac.yaml
Labels: cla: yes, size/M

#1980 Add GCP permissions for istio.io test
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1981 Bump prow from v20191022-7c8165546 to v20191023-5d6c24c6f
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1982 Remove manifest-apply from operator
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.4.gen.yaml
  prow/config/jobs/operator-1.4.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/S

#1983 Fix githubctl retest
  toolbox/githubctl/main.go
Labels: cla: yes, size/S

#1987 Add optional gencheck jobs on all repos with Go code.
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tests.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/S

#1990 Move istio/api, istio/pkg, and istio/bots to latest container.
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/pkg.yaml
Labels: cla: yes, size/XS

#1989 Bump prow from v20191023-5d6c24c6f to v20191024-64518f5f8
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1992 Get more repos on the latest container.
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.master.gen.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/tests.yaml
Labels: cla: yes, size/XS

#1994 Move istio/operator and istio/release-builder to latest container.
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/release-builder.yaml
Labels: cla: yes, size/XS

#1998 All istio jobs are on kind now
  licenses/k8s.io/kubernetes/License
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/M

#1997 Drop Boskos cluster amount to 20 (from 50)
  boskos/resources.yaml
Labels: cla: yes, size/XS

#1996 Move the installer repo to the latest container.
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/config/jobs/installer.yaml
Labels: cla: yes, size/XS

#1993 Verify that the release scripts work in istio/proxy presubmits.
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml
Labels: cla: yes, size/M

#2001 Update prowbazel to run as "root" user
  docker/prowbazel/Dockerfile
  docker/prowbazel/Makefile
Labels: cla: yes, size/S

#2003 Update perf benchmark periodic job yaml
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/S

#2005 set proper start time for three perf related jobs
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/XS

#2000 Update golang to 1.12.12 for 1.3 release
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.3.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.3.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.3.gen.yaml
  prow/config/jobs/cni-1.3.yaml
  prow/config/jobs/istio-1.3.yaml
  prow/config/jobs/operator-1.3.yaml
Labels: cla: yes, size/S

#2007 Bump prow from v20191024-64518f5f8 to v20191025-88400583c
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2008 Fix directory for prowbazel image push
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/XS

#1991 Restructure genjobs tool and add support for "env" variable overrides
  prow/cmd/genjobs/genjobs.go
  prow/genjobs/README.md
  prow/genjobs/cmd/genjobs/main.go
  prow/genjobs/main.go
  prow/genjobs/pkg/util/errors.go
  prow/genjobs/pkg/util/os.go
Labels: cla: yes, size/XL

#2002 Update image for istio/istio
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2011 Add update to prowbazel image README
  docker/prowbazel/README.md
Labels: cla: yes, size/XS

#2009 Promote prowbazel image for istio/proxy master and release-1.4 to 0.5.13
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml
Labels: cla: yes, size/S

#2010 Update prowbazel to install goimports and golangci
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml
  scripts/tools/linux-install-golang
Labels: cla: yes, size/S

#2012 Make multicluster job required
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2015 Update container image for 1.4 branch.
  prow/cluster/jobs/istio/api/istio.api.release-1.4.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.4.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.release-1.4.gen.yaml
  prow/config/jobs/api-1.4.yaml
  prow/config/jobs/cni-1.4.yaml
  prow/config/jobs/installer-1.4.yaml
Labels: cla: yes, size/XS

#2016 Use updated build image for working linting with cni
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#2017 CNI: `make gen-check` mandatory check
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#2018 Update container images for 1.4 branch.
  prow/cluster/jobs/istio/istio/istio.istio.release-1.4.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.4.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.4.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.4.gen.yaml
  prow/config/jobs/istio-1.4.yaml
  prow/config/jobs/operator-1.4.yaml
  prow/config/jobs/pkg-1.4.yaml
  prow/config/jobs/tools-1.4.yaml
Labels: cla: yes, size/XS

#2014 Add "push-safe" target
  docker/prowbazel/Makefile
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/XS

#2021 Update client-go release 1.4 branch to recent 1.4 container.
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.4.gen.yaml
  prow/config/jobs/client-go-1.4.yaml
Labels: cla: yes, size/XS

#2019 Bump prow from v20191025-88400583c to v20191028-34f10daf9
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2022 Add "istio-private" org to hidden repos.
  prow/config.yaml
Labels: cla: yes, size/XS

#1986 Add gencheck to installer
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/config/jobs/installer.yaml
Labels: cla: yes, size/XS

#2024 Update operator to add jq for e2e check
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/XS

#1948 add periodic job to run e2e test for istio upgrade command
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/S

#2027 Stop publishing 1.1 daily builds
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/M

#2026 Bump prow from v20191028-34f10daf9 to v20191030-49516b6be
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M
