Repository istio/test-infra, pull requests merged in 2019-09, with the labels that each got.

#1750 Add jobs for the tests, client-go, and common-files repos.
  prow/cluster/jobs/istio/client-go/istio-client-go.yaml
  prow/cluster/jobs/istio/common-files/istio-common-files.yaml
  prow/cluster/jobs/istio/tests/istio-tests.yaml
Labels: cla: yes, size/L

#1752 Use the config generator for the client-go repo.
  prow/cluster/jobs/istio/client-go/istio-client-go.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.3.yaml
  prow/config/generate.go
  prow/config/jobs/client-go.yaml
  prow/config/testdata/simple.out.yaml
  prow/config/testdata/simple.yaml
Labels: cla: yes, size/L

#1753 Remove k8s 1.12 tests
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.3.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/L

#1757 Update prow to v20190903-2d1aaee54.
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1756 Fix bookinfo test calling wrong test
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.3.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#1758 Update CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/S

#1759 Make branchprotector run as a trusted ProwJob instead of a k8s cronjob.
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/M

#1760 Remove superfluous prod=prow node selector
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  toolbox/metrics/cmd/deployment.yaml
Labels: cla: yes, size/S

#1761 Fix workload identity deployment
  boskos/gcp/gke.go
Labels: cla: yes, size/XS

#1763 Update prow to v20190903-599c89c3c
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, ok-to-test, size/M

#1515 Add daemonset to prow cluster to increase inotify watch limit
  prow/cluster/tune-sysctls_daemonset.yaml
Labels: cla: yes, ok-to-test, size/M

#1765 Add independent prow build cluster deployment
  prow/Makefile
  prow/cluster/build/tune-sysctls_daemonset.yaml
Labels: cla: yes, size/XS

#1767 Update Prow to v20190905-4782ba3a2
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, ok-to-test, size/M

#1770 Add a trusted postsubmit job to automatically deploy Prow cluster changes.
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/S

#1773 Update Prow to eff7a2073
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, ok-to-test, size/M

#1771 Update common files.
  .commonfiles.sha
  .gitattributes
  Makefile
  Makefile.core.mk
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/report_build_info.sh
  release-note
Labels: cla: yes, size/L

#1775 Modification of Prow README
  prow/README.md
Labels: cla: yes, ok-to-test, size/S

#1772 Update update tests for release pipeline
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
Labels: cla: yes, size/XS

#1778 Use latest container image.
  prow/cluster/jobs/istio/api/istio.api.master.yaml
Labels: cla: yes, size/XS

#1779 First step towards moving the installer repo to prow.
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.yaml
  prow/config/jobs/installer.yaml
Labels: cla: yes, size/M

#1781 Update testgrid for job name changes
  Makefile.core.mk
  go.mod
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.release-1.3.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.3.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.3.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.3.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.3.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.2.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.2.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.3.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.3.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/jobs/istio/tests/istio.tests.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.release-1.3.gen.yaml
  prow/config/generate.go
  prow/config/testdata/simple.gen.yaml
  testgrid/default.yaml
  testgrid/istio-generated.yaml
  testgrid/istio.gen.yaml
Labels: cla: yes, size/XXL

#1782 Set boskos sync period to 15 seconds
  boskos/cmd/mason_client/main.go
Labels: cla: yes, size/XS

#1764 Add operator manifest apply test
  prow/cluster/jobs/istio/operator/istio.operator.yaml
Labels: cla: yes, size/M

#1783 Update prow to v20190909-c3ac80e32
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, ok-to-test, size/M

#1769 Preserve Kube context on Prow "deploy" via Makefile
  prow/Makefile
Labels: cla: yes, size/S

#1777 Use the build-tools container where it makes sense.
  .golangci.yml
  Makefile.core.mk
  Makefile.overrides.mk
  go.mod
  go.sum
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/config/jobs/test-infra.yaml
  scripts/fmt.sh
  scripts/linters.sh
  scripts/run_gobindata.sh
  scripts/run_gofmt.sh
Labels: cla: yes, size/XL

#1780 Add optional jobs for CNI
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.3.gen.yaml
  prow/config.yaml
  prow/config/cmd/generate.go
  prow/config/generate.go
  prow/config/jobs/cni.yaml
  prow/config/jobs/installer.yaml
Labels: cla: yes, size/M

#1786 Run go mod tidy
  go.mod
Labels: cla: yes, size/XS

#1787 Cleanup unused dockerfile
  docker/README.md
  docker/istio/test-infra/Dockerfile
  docker/istio/test-infra/Makefile
  docker/istio/test-infra/install.sh
Labels: cla: yes, size/M

#1788 Update to golang 1.13
  docker/istio/shared/tools/install-golang.sh
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#1792 Revert "Update to golang 1.13 (#1788)"
  docker/istio/shared/tools/install-golang.sh
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#1793 Delete integration race test
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1789 Enable more linters.
  Makefile.core.mk
  boskos/cmd/mason_client/example.sh
  docker/istio/istio/install.sh
  docker/istio/shared/prow-runner.sh
  docker/istio/shared/tools/install-bazel.sh
  docker/istio/shared/tools/install-clang.sh
  docker/istio/shared/tools/install-docker.sh
  docker/istio/shared/tools/install-gcloud.sh
  docker/istio/shared/tools/install-golang.sh
  docker/istio/shared/tools/install-helm.sh
  docker/istio/shared/tools/install-jars.sh
  docker/istio/shared/tools/install-java.sh
  docker/istio/shared/tools/install-kubectl.sh
  docker/istio/shared/tools/install-libcxx.sh
  docker/istio/shared/tools/install-protoc.sh
  docker/istio/shared/tools/install-yamllint.sh
  docker/istio/test-flakey/install.sh
  flakeyTest/daily-flakey-test.sh
  flakeyTest/readPastJunitCommand.sh
  flakeyTest/removeTempFolderCommand.sh
  flakeyTest/testCommand.sh
  go.mod
  prow/bump.sh
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
  prow/cluster/jobs/istio/istio/update-prow-staging.sh
  prow/recreate_prow_configmaps.py
  rbe/install-istio-testing.sh
  scripts/bazel_to_go.py
  scripts/check_dockerfiles.sh
  scripts/check_license.sh
  scripts/deps_to_bazel.py
  scripts/run_golangci.sh
  scripts/set-boskos-project.sh
  scripts/use_bazel_go.sh
  toolbox/metrics/generate.sh
Labels: cla: yes, size/XL

#1791 Postsubmit for deploying boskos and updating boskos config
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/plugins.yaml
Labels: cla: yes, size/M

#1794 Deploy postsubmit job cleanup / simplification
  boskos/Makefile
  prow/Makefile
  prow/Makefile.gcloud.mk
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/config.yaml
Labels: cla: yes, size/L

#1790 Make lintmodern_cni required, and retire classic lint_cni.
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.3.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#1795 Fix codeowners
  CODEOWNERS
Labels: cla: yes, size/XS

#1796 Add "boskos-admin" to mason rather than using defaut serviceaccount
  boskos/cluster/mason-deployment.yaml
Labels: cla: yes, size/XS

#1797 Enable script linting.
  Makefile.core.mk
  boskos/cmd/mason_client/example.sh
  docker/istio/shared/tools/install-kubectl.sh
  docker/prowbazel/entrypoint
  flakeyTest/daily-flakey-test.sh
  flakeyTest/readPastJunitCommand.sh
  flakeyTest/removeTempFolderCommand.sh
  flakeyTest/testCommand.sh
  prow/build-test.sh
  prow/gcr_cleanup_istio_testing.sh
  prow/pj-on-kind.sh
  prow/test-infra-presubmit.sh
  rbe/install-istio-testing.sh
  scripts/all-utilities
  scripts/cleanup-GKE
  scripts/cleanup-cache
  scripts/linux-install-software
  scripts/set-boskos-project.sh
  scripts/tools/linux-install-bazel
  scripts/tools/linux-install-clang
  scripts/tools/linux-install-cmake
  scripts/tools/linux-install-docker
  scripts/tools/linux-install-gcc
  scripts/tools/linux-install-gcloud
  scripts/tools/linux-install-golang
  scripts/tools/linux-install-helm
  scripts/tools/linux-install-ninja
  scripts/tools/linux-install-protoc
  scripts/tools/linux-install-repo
  scripts/tools/linux-install-wrk
  scripts/update-e2e-cluster.sh
  scripts/use_bazel_go.sh
  toolbox/metrics/generate.sh
Labels: cla: yes, size/L

#1798 Add a container-based lint job for installer.
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/config/jobs/installer.yaml
Labels: cla: yes, size/XS

#1799 Update istio-releases tests to have unique job names
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.0.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.1.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.2.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml
  testgrid/default.yaml
  testgrid/istio.gen.yaml
Labels: cla: yes, size/L

#1804 Re-enable CNI tests in master and release-1.3
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.3.gen.yaml
  prow/config/jobs/istio.1.3.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1805 Fix k8s 1.12 name
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1806 Bump prow to v20190913-fb0db8137
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1807 Enable deck rerun
  prow/cluster/deck_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/S

#1808 Raise racetest limits
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1809 Add a lintmodern job to istio/istio.
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1810 Try to get the containers job working on the tools repo.
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.yaml
  prow/config/generate.go
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#1811 Update to get a bug fix for mason
  go.mod
  go.sum
Labels: cla: yes, size/XS

#1813 Increase limits on all jobs
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1815 Update to the latest container for linting istio/istio.
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1814 Remove release-1.0 config
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.0.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.0.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.0.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.0.yaml
Labels: cla: yes, size/XL

#1817 Simplify rerun and trigger
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.release-1.3.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.3.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.3.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.3.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.3.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.3.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.3.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.3.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.release-1.3.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/generate.go
  prow/config/generate_test.go
  prow/config/testdata/simple.gen.yaml
Labels: cla: yes, size/M

#1819 Update presubmit image
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/config/jobs/test-infra.yaml
Labels: cla: yes, size/XS

#1818 Update common files
  .gitattributes
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/lint_go.sh
  go.mod
  go.sum
Labels: cla: yes, size/M

#1820 Generate api and operator test configs
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.3.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/L

#1821 Fix accidentally required operator test
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.3.gen.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/XS

#1784 Disable integration test for installer
  prow/config.yaml
Labels: cla: yes, size/XS

#1822 Fix inconsistent ownership.
  CODEOWNERS
Labels: cla: yes, size/S

#1824 Refactor testgrid layout
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.1.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.2.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.3.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.release-1.3.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.3.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.3.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.3.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.3.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.3.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.2.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.3.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.3.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.releaae-1.3.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.3.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.3.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.release-1.3.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.yaml
  prow/config/generate.go
  prow/config/jobs/pkg-1.3.yaml
  prow/config/testdata/simple.gen.yaml
  testgrid/default.yaml
  testgrid/istio.gen.yaml
Labels: cla: yes, size/L

#1825 Update Prow to v20190918-7672de02b
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1827 Update CNI build tools container.
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#1828 Update Prow to v20190919-01001ae61
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1829 Update cni images to golang 13
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#1831 Switch tools repo to latest container.
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/XS

#1832 Update Prow to v20190920-d724a578b
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1830 Remove @krzyzacy from owners
  CODEOWNERS
Labels: cla: yes, size/S

#1837 Update Prow to v20190924-cb71f84e1
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1812 Add job for perf benchmark
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml
Labels: cla: yes, size/M

#1838 Remove required status check for e2e-dind-IPV6
  prow/config.yaml
Labels: cla: yes, size/XS

#1835 Bump api and client-go prow build image
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.3.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/client-go.yaml
Labels: cla: yes, size/XS

#1839 Update a few things.
  CODEOWNERS
  Makefile
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/L

#1840 Remove superfluous release-1.3 jobs I added yesterday, which aren't actually needed.
  prow/cluster/jobs/istio/api/istio.api.release-1.3.gen.yaml
  prow/config/jobs/api-1.3.yaml
Labels: cla: yes, size/S

#1842 Use the DIND image recently built
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#1844 Use latest dind image
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#1845 Add pipenv install
  docker/istio/istio/install.sh
  docker/istio/shared/tools/install-python.sh
Labels: cla: yes, size/XS

#1846 Use latest DIND buld-tools image for CNi
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#1848 Update image for perf and benchmark
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml
Labels: cla: yes, size/XS

#1849 Add istio maintainers to rerun whitelist
  prow/config.yaml
Labels: cla: yes, size/XS

#1847 Bump Prow from v20190924-cb71f84e1 to v20190926-a128cddb1.
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1843 Retire the old lint job and rename lint_modern to lint.
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#1850 Introduce the release-builder repo.
  prow/config.yaml
Labels: cla: yes, size/XS

#1851 Revert/cni dind
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#1852 Add jobs for release-builder
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/jobs/release-builder.yaml
Labels: cla: yes, size/S

#1854 Use dockerd & appraoch in CNI
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/S

#1855 Update prow to gcr.io/k8s-prow/hook:v20190927-a9e239ad8
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#1859 Use latest image 2019-09-29T02-31-02
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#1860 CNI: Use image 2019-09-29T15-31-13
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/config/jobs/cni.yaml
Labels: cla: yes, size/XS

#1861 Job updates.
  Makefile.core.mk
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.3.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.3.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.3.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.3.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.3.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.3.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.3.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.release-1.3.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tests.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#1862 Mount /var/lib/docker as emptyDir for kind
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.3.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.3.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.3.gen.yaml
  prow/config/generate.go
  prow/config/testdata/simple.gen.yaml
Labels: cla: yes, size/S

#1863 Update common files.
  .golangci.yml
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/gobuild.sh
Labels: cla: yes, size/L

#1864 Don't use custom trigger command
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.3.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.3.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.3.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.3.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.3.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tests/istio.tests.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/generate.go
  prow/config/generate_test.go
  prow/config/testdata/simple.gen.yaml
Labels: cla: yes, size/M

#1866 Enable all linters on this repo.
  Makefile.core.mk
  boskos/README.md
  boskos/cmd/mason/Dockerfile
  docker/istio/istio/Dockerfile
  docker/istio/test-flakey/Dockerfile
  docker/istio/test-flakey/README.md
  docker/prowbazel/Dockerfile
  docker/prowbazel/README.md
  flakeyTest/README.md
  prow/README.md
  prow/cluster/cert-manager/README.md
  prow/config/README.md
  scripts/README.md
  sites/istio.io/gcsweb/README.md
  sites/kube-cert-manager/README.md
  toolbox/ci2gubernator/README.md
  toolbox/errorfinder/README.md
  toolbox/githubctl/README.md
  toolbox/timecomparer/README.md
Labels: cla: yes, size/L

#1868 Add initial prow jobs for installer
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/config/jobs/installer.yaml
Labels: cla: yes, size/S

#1869 Add entrypoint for installer
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/config/jobs/installer.yaml
Labels: cla: yes, size/XS
