Repository istio/test-infra, pull requests merged in 2019-12, with the labels that each got.

#2166 Update repos with latest build tools container
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2168 Bump prow from v20191127-0cc88ec7d to v20191128-48349ea19
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2169 Override envoy in istio-private/istio tests
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.4.gen.yaml
  prow/genjobs/gen-private-jobs.sh
Labels: cla: yes, size/XS

#2170 Add CRI dashboard to testgrid
  testgrid/default.yaml
  testgrid/istio.gen.yaml
Labels: cla: yes, size/XS

#2162 Authentikos: update docs and tag latest image
  authentikos/Dockerfile
  authentikos/Makefile
  authentikos/README.md
Labels: cla: yes, size/S

#2173 update upgrade job
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/M

#2177 Fix typo of upgrade script name
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/S

#2178 Update ci container for api repo
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/config/jobs/api.yaml
Labels: cla: yes, size/XS

#2179 Allow override-selector to remove a node selector
  prow/genjobs/cmd/genjobs/main.go
Labels: cla: yes, size/XS

#2181 Bump prow from v20191128-48349ea19 to v20191204-d7993c80e
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2180 update container image for api job
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/config/jobs/api.yaml
Labels: cla: yes, size/XS

#2175 Update repos with latest build tools container
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, ok-to-test, size/M

#2183 Update build image for istio/istio
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2185 Bump prow from v20191204-d7993c80e to v20191205-ed6d94a45
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, lifecycle/needs-triage, size/M

#2174 Add Transfigure Presubmit
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: cla: yes, size/S

#2189 Update container image for api job
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/config/jobs/api.yaml
Labels: cla: yes, size/XS

#2176 Authentikos: use SA until workload identity can be properly configured
  prow/cluster/private/authentikos_deployment.yaml
Labels: cla: yes, size/S

#2191 Enable ssh in `release-builder` release-1.4 jobs
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.4.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.4.gen.yaml
  prow/config/jobs/release-builder-1.4.yaml
  prow/genjobs/gen-private-jobs.sh
Labels: cla: yes, size/XS

#2186 Remove build-pool
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.4.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.1.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.2.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.1.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.2.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.3.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml
  prow/config/jobs/proxy.yaml
  scripts/README.md
Labels: cla: yes, size/M

#2187 Reduce number of boskos clusters
  boskos/resources.yaml
Labels: cla: yes, size/XS

#2184 Update test-infra deps
  boskos/cmd/mason/main.go
  boskos/cmd/mason_client/main.go
  go.mod
  go.sum
Labels: cla: yes, size/M

#2192 Fix release janitor
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/XS

#2194 Bump prow from v20191205-ed6d94a45 to v20191206-ec60c28a0
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2182 Genjobs: normalize org maps to work with Gerrit hosts
  prow/genjobs/cmd/genjobs/main.go
  prow/genjobs/pkg/util/strings.go
  prow/genjobs/pkg/util/strings_test.go
Labels: cla: yes, size/L

#2198 Bump prow from v20191206-ec60c28a0 to v20191209-e921905b4
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2199 Remove allow_cancellations: true as its now default behavior
  prow/config.yaml
Labels: cla: yes, size/XS

#2200 remove "deploy/netlify" context from "istio-private/istio.io"
  prow/config.yaml
Labels: cla: yes, size/XS

#2167 increase perf timeout for running more tests
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/XS

#2201 Replace istio-builder with build-tools
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/XS

#2202 Bump prow from v20191209-e921905b4 to v20191210-5844d8374
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2204 Update build-tools to pick up debugabiltiy fixes
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2205 Update 1.17 node image
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2208 Bump istio image
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2209 Run proxy tests only on release-1.3
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.3.yaml
Labels: cla: yes, size/XS

#2206 Use pattern rule in make to retrigger `get-cluster-credentials` prerequisite
  prow/Makefile
  prow/Makefile.gcloud.mk
Labels: cla: yes, size/XS

#2160 Genjobs: support lexicographical job sorting
  prow/genjobs/cmd/genjobs/main.go
  prow/genjobs/main_test.go
  prow/genjobs/testdata/sort_ascending/sort_ascending_in.yaml
  prow/genjobs/testdata/sort_ascending/sort_ascending_out.yaml
  prow/genjobs/testdata/sort_descending/sort_descending_in.yaml
  prow/genjobs/testdata/sort_descending/sort_descending_out.yaml
Labels: cla: yes, size/L

#2210 Bump prow from v20191210-5844d8374 to v20191211-cf6fb4d2b
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2214 Bump prow from v20191211-cf6fb4d2b to v20191212-70b0b49fe
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2215 fix broken recreate_prow_configmaps.py
  prow/recreate_prow_configmaps.py
Labels: cla: yes, size/M

#2197 add istio/bots policybot deployment postsubmit
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/config/README.md
  prow/config/jobs/bots.yaml
Labels: cla: yes, size/M

#2218 Bump prow from v20191212-70b0b49fe to v20191213-014dcb6ca
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2217 Remove config for release-1.2
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.2.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.2.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.2.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.2.yaml
  testgrid/default.yaml
Labels: cla: yes, size/XXL

#2163 Genjobs: update docs, create Dockerfile, autodeploy
  Makefile.core.mk
  authentikos/README.md
  prow/Makefile
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/config/config_test.go
  prow/config/generate.go
  prow/config/jobs/test-infra.yaml
  prow/genjobs/Dockerfile
  prow/genjobs/Makefile
  prow/genjobs/README.md
  prow/genjobs/gen-private-jobs.sh
  prow/genjobs/pkg/util/strings_test.go
Labels: cla: yes, size/L

#2172 Automate `istio/api` cross-repo file generation
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/config/generate.go
  prow/config/jobs/api.yaml
  tools/automator/automator.sh
Labels: cla: yes, size/L

#2220 Update operator build tools image
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/XS

#2224 Bump prow from v20191213-014dcb6ca to v20191217-e7571bd25
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2229 Build tools master 2019 12 15 t16 17 48
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/S

#2233 Automator: update common file @ master
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/M

#2235 Update release-builder build-tools
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/jobs/release-builder.yaml
Labels: cla: yes, size/XS

#2234 Update kubernetes version tests
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2237 Remove legacy integration tests
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2239 Bump prow from v20191217-e7571bd25 to v20191217-2b88bfc4b
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2240 Add chases2 to CODEOWNERS
  CODEOWNERS
Labels: cla: yes, kind/oncall-hotlist, size/S

#2238 Update build tools image
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/S

#2236 migrate velodrome
  prow/Makefile
  prow/cluster/velodrome/velodrome-istio-io_managedcertificate.yaml
  prow/cluster/velodrome/velodrome_ing.yaml
  prow/cluster/velodrome/velodrome_namespace.yaml
  prow/cluster/velodrome/velodrome_service.yaml
Labels: cla: yes, size/M

#2225 update and use gcs.istio.io hostname
  prow/config.yaml
  sites/istio.io/gcsweb/deployment.yaml
Labels: cla: yes, kind/oncall-hotlist, size/XS

#2243 Make cgroup mount readonly
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.3.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.4.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.release-1.4.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.3.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.4.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.3.gen.yaml
  prow/config/generate.go
  prow/config/testdata/simple.gen.yaml
Labels: cla: yes, size/XS

#2241 Bump prow from v20191217-2b88bfc4b to v20191219-ecbeba384
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M
