Repository istio/test-infra, pull requests merged in 2019-06, with the labels that each got.

#1293 Update images to use Golang 1.12.5 and remove kind
  docker/istio/shared/tools/install-golang.sh
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  scripts/tools/linux-install-bazel
  scripts/tools/linux-install-golang
Labels: approved, cla: yes, lgtm

#1294 Give unique context name for the test
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
Labels: approved, cla: yes, lgtm

#1291 Add missing integration test gates.
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1297 Update master prow jobs to use new Golang 1.12 and bazel 0.26.0 updates
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.wasm.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes, lgtm

#1296 update bazel to 0.26.0 for istio-builders and test-infra-builders
  docker/istio/shared/tools/install-bazel.sh
Labels: approved, cla: yes, lgtm

#1285 Use new image with install poython-requests
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
Labels: approved, cla: yes, lgtm

#1299 turn on branch protection without required_status_checks for collab-gce-identity branch.
  prow/cluster/jobs/istio/istio/istio.istio.collab-gce-identity.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1295 Split postsubmit integration gates.
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1300 Create a new preset for release's build and test.
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1301 Create bigger test gke cluster and use version gke 1.11
  boskos/configs.yaml
Labels: approved, cla: yes, lgtm

#1302 Revert "Update master prow jobs to use new Golang 1.12 and bazel 0.26.0 updates"
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.wasm.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: human-approved, cla: yes, lgtm

#1303 Add prow config for prow-staging branch
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1304 Increase boskos resources
  boskos/resources.yaml
Labels: approved, cla: yes, lgtm

#1305 Revert "Create bigger test gke cluster and use version gke 1.11"
  boskos/configs.yaml
Labels: approved, cla: yes, lgtm

#1306 Increase boskos pods to speed up cleanup
  boskos/janitor-deployment.yaml
  boskos/mason-deployment.yaml
Labels: approved, cla: yes, lgtm

#1307 Remove deleted script
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
Labels: approved, cla: yes, lgtm

#1308 Make e2e-mixer_no-auth not required test
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.0.yaml
Labels: approved, cla: yes, lgtm

#1309 Update prow-staging to use prow image using Golang 1.12 and bazel 0.26.0
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
Labels: approved, cla: yes, lgtm

#1310 Update master prow jobs to use new Golang 1.12 and bazel 0.26.0 updates
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.wasm.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes, lgtm

#1312 Making release-test required
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.2.yaml
Labels: approved, cla: yes, lgtm

#1313 Making release-test required for release-1.1 branch
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
Labels: approved, cla: yes, lgtm

#1314 Fix incorrect name in prow master
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1315 Add kind v0.3.0 to images
  docker/istio/shared/tools/install-golang.sh
  scripts/tools/linux-install-golang
Labels: approved, cla: yes, lgtm

#1316 Add lint test
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1317 Revert "Add lint test"
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1283 Istio Flakey Test
  flakeyTest/Pair.java
  flakeyTest/TotalFlakey.java
  flakeyTest/readPastJunitCommand.sh
  flakeyTest/removeTempFolderCommand.sh
  flakeyTest/testCommand.sh
Labels: approved, cla: yes, lgtm, ok-to-test

#1318 Making sure only build image job are running on build-pool
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.2.yaml
Labels: approved, cla: yes, lgtm

#1319 Add kind v0.3.0 to prowbazel:0.5.6
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
Labels: approved, cla: yes, lgtm

#1320 add test-flakey folder and install-java.sh
  docker/istio/shared/tools/install-jars.sh
  docker/istio/shared/tools/install-java.sh
  docker/istio/test-flakey/Dockerfile
  docker/istio/test-flakey/Makefile
  docker/istio/test-flakey/install.sh
Labels: approved, cla: yes, lgtm, ok-to-test

#1322 increasing boskos resources
  boskos/janitor-deployment.yaml
  boskos/mason-deployment.yaml
  boskos/resources.yaml
Labels: approved, cla: yes, lgtm

#1323 Add README and modify install-jars.sh
  docker/istio/test-flakey/README.md
  flakeyTest/README.md
Labels: approved, cla: yes, lgtm, ok-to-test

#1325 increase boskos resources
  boskos/janitor-deployment.yaml
  boskos/mason-deployment.yaml
  boskos/resources.yaml
Labels: approved, cla: yes, lgtm

#1326 Update prow-staging to use prow image with Golang 1.12 and kind
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
Labels: approved, cla: yes, lgtm

#1327 Add missing preset-service-account flags to postsubmit K8s integ tests.
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1321 Recreate the collab-galley branch jobs, based on the master branch file.
  prow/cluster/jobs/istio/istio/istio.istio.collab-galley.yaml
Labels: approved, cla: yes, lgtm

#1324 Add test-flakey container to run daily totalFlakey.java
  flakeyTest/daily-flakey-test.sh
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1329 Changes to flakey-container
  flakeyTest/TotalFlakey.java
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1311 Creating build&test version of presubmit tests as optional
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
Labels: approved, cla: yes, lgtm

#1332 Getting rid run_after_success in prow-staging first
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
Labels: approved, cla: yes, lgtm

#1333 Getting rid istio-presubmit.sh
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
Labels: approved, cla: yes, lgtm

#1331 Reducing max pod age to 6h
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1334 Update prow images for master to Golang 1.12.5 with kind v0.30.0
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.wasm.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes, lgtm

#1335 increase resources for proxy
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.wasm.yaml
Labels: approved, cla: yes, lgtm

#1336 Getting rid run after success in presubmit
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1338 update yaml file to include the security json
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1342 Make removed circle tests non-required
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1339 change TotalFlakey.java to read from pantheon directly
  flakeyTest/TotalFlakey.java
  flakeyTest/daily-flakey-test.sh
Labels: approved, cla: yes, lgtm, ok-to-test

#1343 Add lint target to prow-staging
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
Labels: approved, cla: yes, lgtm

#1344 Get rid run after success for master releases
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
Labels: approved, cla: yes, lgtm

#1346 making all tests required
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
Labels: approved, cla: yes, lgtm

#1345 Add prow linter to master
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1347 Delete test-infra config for istio/istio release-0.8
  prow/cluster/jobs/istio/istio/istio.istio.release-0.8.yaml
Labels: approved, cla: yes, lgtm

#1353 Make prow lint required, circle optional
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1354 Add remaining circle tests to prow staging
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
Labels: approved, cla: yes, lgtm

#1349 Deleting run_after_success for release-1.0
  prow/cluster/jobs/istio/istio/istio.istio.release-1.0.yaml
Labels: approved, cla: yes, lgtm

#1355 Prow staging shellcheck
  docker/istio/istio/Dockerfile
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
Labels: approved, cla: yes, lgtm

#1350 Deleting run_after_success for release-1.1
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
Labels: approved, cla: yes, lgtm

#1358 Change the release-1.1 release pipeline to use build&test approach
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.1.yaml
Labels: approved, cla: yes, lgtm

#1356 Turn on circle tests on master
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1360 add yamllint into image
  docker/istio/istio/install.sh
Labels: approved, cla: yes, lgtm

#1359 Nuke run_after_success and deprecate collab-gcp-identity
  prow/cluster/jobs/istio/istio/istio.istio.collab-galley.yaml
  prow/cluster/jobs/istio/istio/istio.istio.collab-gce-identity.yaml
  prow/cluster/jobs/istio/istio/istio.istio.collab-gcp-identity.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1361 Add the Mixer test as a presubmit gate.
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1362 istio/istio authz-v2 is not used anymore and deprecated
  prow/cluster/jobs/istio/istio/istio.istio.authz-v2.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1357 Change the release-1.0 release pipeline to use build&test approach
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.0.yaml
Labels: approved, cla: yes, lgtm

#1366 Switch circle requirement for prow requirement
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1365 Add conformance post-submit gates.
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1364 install jq
  docker/istio/istio/install.sh
Labels: approved, cla: yes, lgtm

#1368 Make circleci build nonrequired
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1369 add yamllint 1.16 and it's dependencies
  docker/istio/istio/Dockerfile
  docker/istio/istio/install.sh
  docker/istio/shared/tools/install-yamllint.sh
Labels: approved, cla: yes, lgtm

#1371 Increase resource requests
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.2.yaml
Labels: approved, cla: yes, lgtm

#1372 Provision enough pod resources for release workflows
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.0.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.1.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.2.yaml
Labels: approved, cla: yes, lgtm

#1373 Experimenting with upper resource limit
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.1.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.2.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.2.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes, lgtm

#1376 Swap prow for circle racetest
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/config.yaml
Labels: cla: yes, lgtm

#1374 Update prow images for master to yamllint 1.16
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes, lgtm

#1378 Revert back the test-infra image
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes

#1377 Remove the new Mixer k8s job, as this is already run as part of the regular gates
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1379 Upgrade to latest kubectl
  docker/istio/istio/install.sh
  docker/istio/shared/tools/install-gcloud.sh
  docker/istio/shared/tools/install-kubectl.sh
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
Labels: approved, cla: yes, lgtm

#1370 Go module testing
  docker/istio/istio/Dockerfile
Labels: approved, cla: yes, lgtm

#1380 Add lint job for operator to prow
  prow/cluster/jobs/istio/operator/istio.operator.master.yaml
Labels: approved, cla: yes, lgtm

#1381 Add an installer prow job to begin the migration
  prow/cluster/jobs/istio/installer/istio.installer.master.yaml
Labels: approved, cla: yes, lgtm

#1382 Try using Go modules in prow-staging
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
Labels: approved, cla: yes, lgtm

#1384 Make pod resource consumption predictable
  prow/cluster/jobs/istio/istio/istio.istio.collab-galley.yaml
  prow/cluster/jobs/istio/istio/istio.istio.collab-gce-identity.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes, lgtm

#1385 Remove GO1111MODULE=on (revert to using vendor dir)
  docker/istio/istio/Dockerfile
Labels: approved, cla: yes, lgtm

#1386 Revert "Swap prow for circle racetest"
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1383 Operator cargo cult copy :)
  prow/cluster/jobs/istio/operator/istio.operator.master.yaml
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#1388 Temp. disable branch protection on operator repo
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1389 After RTD, properly configure prow
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#1390 Update Bazel to 0.27.0 and LLVM/clang to 8.
  docker/istio/shared/tools/install-bazel.sh
  docker/istio/shared/tools/install-clang.sh
  docker/prowbazel/README.md
  scripts/tools/linux-install-bazel
  scripts/tools/linux-install-clang
Labels: approved, cla: yes, lgtm

#1351 Deleting run_after_success for release-1.2
  prow/cluster/jobs/istio/istio/istio.istio.release-1.2.yaml
Labels: approved, cla: yes, lgtm

#1367 Change release-1.2 presubmit release process to build&test
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.2.yaml
Labels: approved, cla: yes, lgtm

#1391 Update prowbazel in proxy/master and proxy/wasm to 0.5.7.
  docker/prowbazel/Makefile
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.wasm.yaml
Labels: approved, cla: yes, lgtm

#1392 Clean up integration test targets
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1393 Turn on new installer test (as optional)
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm
