Repository istio/test-infra, pull requests merged in 2019-07, with the labels that each got.

#1394 Update build image
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1352 Run e2e-simple tests also for distroless images
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1395 Fix KinD tests to properly set up docker
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1397 Upgrade branchprotector to upstream and latest
  prow/cluster/branchprotector_cronjob.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1398 Remove Seb from owners list
  OWNERS
Labels: approved, cla: yes, lgtm, ok-to-test

#1399 Upgrade prow to v20190628-eb4a10930
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/hook_rbac.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1404 Report job status for postsubmit jobs
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1406 Update pod-utils to v20190628-eb4a10930
  prow/config.yaml
Labels: cla: yes, lgtm, ok-to-test

#1410 Use nanosecond int64 value for timeout, grace period
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1405 Use current prowjob CRD
  prow/cluster/prow_job.yaml
  prow/cluster/prowjob_customresourcedefinition.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1401 Script to install/update rbe into the istio-testing project
  rbe/.gitignore
  rbe/README.md
  rbe/install-istio-testing.sh
Labels: approved, cla: yes, lgtm, ok-to-test

#1412 Make build-test pass in official bazel container
  .bazelrc
  .bazelversion
  WORKSPACE
  docker/istio_builders/prow_builder/bootstrap/BUILD.bazel
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/config.yaml
  requirements.txt
Labels: approved, cla: yes, lgtm

#1420 Check in a script to upgrade prow
  prow/bump.sh
Labels: approved, cla: yes, lgtm

#1421 Stop using ssd cache
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes, lgtm

#1419 Upgrade prow to v20190703-1f4d61631
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1414 Increase linter memory requests
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1416 Fix KinD volume syntax
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1400 Check in configs to support RBE
  .bazelignore
  .bazelrc
  BUILD.bazel
  WORKSPACE
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1426 Set up ghproxy for Istio's Prow instance.
  prow/cluster/ghproxy.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1427 Enable SSL redirect for Prow.
  prow/cluster/deck_deployment.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1429 Use RBE for --config=ci
  .bazelrc
Labels: approved, cla: yes, lgtm

#1428 Make Prow components use ghproxy.
  prow/Makefile
  prow/cluster/hook_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/tide_deployment.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1411 Enable spyglass
  prow/cluster/deck_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1435 Increase memory request 2 -> 3gb
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1436 Simplify test-infra configs
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes, lgtm

#1432 Merge approvers and reviewers list
  OWNERS
Labels: approved, cla: yes, lgtm

#1439 Bump Prow to version v20190708-d639b3427.
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1441 Change integ-security-k8s-presubmit-tests-master to requried
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1442 Add cloudfoundry test
  docker/istio/istio/install.sh
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1434 Allow github reviews to add/remove LGTM
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#1444 Move go_repository() calls into their own file
  WORKSPACE
  repos.bzl
  scripts/update_deps.sh
Labels: approved, cla: yes, lgtm

#1438 Use spyglass for job logs
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1430 Add a checkconfig presubmit to validate Prow config.
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1445 Use recommended review, /lgtm, /approve config
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#1387 Add build and test jobs for operator repo
  prow/cluster/jobs/istio/operator/OWNERS
  prow/cluster/jobs/istio/operator/istio.operator.master.yaml
Labels: approved, cla: yes, lgtm

#1447 Skip report on installer until stable
  prow/cluster/jobs/istio/installer/istio.installer.master.yaml
Labels: approved, cla: yes, lgtm

#1448 Temporarily restore /lgtm == /approve
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#1449 [Prow Staging] Switch integration tests to use kind
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
Labels: approved, cla: yes, lgtm

#1451 Create owners files for jobs istio and installer
  prow/cluster/jobs/istio/installer/OWNERS
  prow/cluster/jobs/istio/istio/OWNERS
Labels: approved, cla: yes, lgtm

#1453 Set volume and volumeMount for prow staging kind
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
Labels: approved, cla: yes, lgtm

#1454 Switch circleci->prow required for cloudfoundry
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1455 Switch integration tests to use kind
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1456 Update branch protection settings.
  prow/config.yaml
Labels: approved, cla: yes, do-not-merge/hold, lgtm

#1467 Make prow jobs non-optional
  prow/cluster/jobs/istio/operator/istio.operator.master.yaml
Labels: approved, cla: yes, lgtm

#1476 Fix job inconsistencies
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1463 Disable max concurrency on jobs without external dependencies
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1466 Add branch protection settings for installer
  prow/config.yaml
Labels: approved, cla: yes, lgtm

#1474 Turn off service account for istioctl test
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1464 Require github approve or /approve to approve
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm

#1478 bump istio prow to v20190715-1dacc7e01
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#1477 Remove unneeded service account labels
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1462 Using Pod utils for one proxy test
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
Labels: approved, cla: yes, lgtm

#1481 Add statusreconciler deployment
  prow/Makefile
  prow/cluster/statusreconciler_deployment.yaml
Labels: approved, cla: yes, lgtm

#1479 Moving all proxy tests to use pod utils
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
Labels: approved, cla: yes, lgtm

#1483 Adding .vscode folder to .gitignore.
  .gitignore
Labels: approved, cla: yes, lgtm

#1485 Remove custom context in istio/istio master
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1484 add statusreconciler-deployment into make deployments
  prow/Makefile
Labels: approved, cla: yes, lgtm, ok-to-test

#1468 Adjust the prow plugins we use on our repos.
  prow/plugins.yaml
Labels: cla: yes

#1488 fix(tests): remove integ-telemetry-local* tests
  prow/cluster/jobs/istio/istio/istio.istio.collab-galley.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
Labels: approved, cla: yes, lgtm, size/M

#1495 Raise job CPU limits
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1493 Update Bazel to 0.28.0.
  docker/istio/shared/tools/install-bazel.sh
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  scripts/tools/linux-install-bazel
Labels: approved, cla: yes, lgtm, size/XS

#1494 Update prowbazel in proxy/master and proxy/wasm to 0.5.8.
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.wasm.yaml
Labels: approved, cla: yes, lgtm, size/S

#1482 Make cjwagner a root level OWNERS approver.
  OWNERS
Labels: approved, cla: yes, lgtm

#1491 Protect master and release branches
  prow/config.yaml
  prow/config/BUILD.bazel
  prow/config/config_test.go
Labels: approved, cla: yes, lgtm, size/L

#1443 Added always run option to distroless test
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm

#1506 Finish modernization of operator
  prow/cluster/jobs/istio/operator/istio.operator.master.yaml
Labels: approved, cla: yes, lgtm, size/S

#1502 Modernize operator-test-master
  prow/cluster/jobs/istio/operator/istio.operator.master.yaml
Labels: approved, cla: yes, lgtm, size/S

#1510 Fix typo
  prow/cluster/jobs/istio/operator/istio.operator.master.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1512 Use ghproxy for branchprotector
  prow/cluster/branchprotector_cronjob.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1487 Enable size, trigger and wip across all istio orgs
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm, size/S

#1513 Use original iamge which came from istio C&P
  prow/cluster/jobs/istio/operator/istio.operator.master.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1508 Integration istio/common-files
  .commonfiles.sha
  .golangci.yml
  BUGS-AND-FEATURE-REQUESTS.md
  CONTRIBUTING.md
  LICENSE
  Makefile
  Makefile.common.mk
  SUPPORT.md
  boskos/gcp/gke.go
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  scripts/check_dockerfiles.sh
  scripts/check_license.sh
  scripts/run_gobindata.sh
  scripts/run_gofmt.sh
  scripts/run_golangci.sh
  sisyphus/alert.go
  sisyphus/sisyphusd.go
  toolbox/branch_pr/main.go
  toolbox/githubctl/main.go
  toolbox/metrics/coverage/coverage_test.go
  toolbox/release_note_collector/main.go
  toolbox/util/commonUtils.go
  toolbox/util/githubUtils.go
Labels: approved, cla: yes, lgtm, size/XXL

#1514 Turn on elide_skipped_contexts
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1496 Adding sheets api to the image for go lint be happy
  docker/istio/shared/tools/install-golang.sh
Labels: approved, cla: yes, lgtm, size/XS

#1470 Update branch protection
  prow/config.yaml
  prow/config/config_test.go
Labels: approved, cla: yes, lgtm, size/M

#1518 Allow release managers to merge.
  prow/config.yaml
  prow/config/config_test.go
Labels: approved, cla: yes, lgtm, size/M

#1519 Restrict merges to admins on tide branches
  prow/config.yaml
  prow/config/config_test.go
Labels: approved, cla: yes, lgtm, size/M

#1459 rewrite config with new branches
  prow/README.md
  prow/rewriteConfig.go
  prow/rewriteConfig_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1521 Update WORKSPACE to latest versions
  WORKSPACE
Labels: approved, cla: yes, lgtm, size/M

#1522 Trial tide on operator repository
  prow/config.yaml
Labels: approved, cla: yes, lgtm, size/S

#1507 Add manifest diff test for operator.
  prow/cluster/jobs/istio/operator/istio.operator.master.yaml
Labels: approved, cla: yes, lgtm, size/S

#1517 new inage for test-infra-buider
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1526 Bump prow to v20190722-4f2588df3
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1530 Add job to test that gcsweb is alive
  prow/cluster/jobs/all-periodics.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1527 Move istio/pkg from CircleCi+Mergify to Prow+Tide.
  prow/cluster/jobs/istio/operator/istio.operator.master.yaml
  prow/cluster/jobs/istio/pkg/OWNERS
  prow/cluster/jobs/istio/pkg/istio.pkg.master.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1533 Switch to the same container as the operator repo uses.
  prow/cluster/jobs/istio/pkg/istio.pkg.master.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1525 Add tests for different kubernetes versions
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm, size/M

#1528 add codecov to istio postsubmit
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm, size/S

#1535 Try to fix the test job.
  prow/cluster/jobs/istio/pkg/istio.pkg.master.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1534 Bump prow to v20190724-1fcd9e27e
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1536 Apply credentials for branchprotector too.
  prow/Makefile
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1539 Update the API job to the latest prowbazel image.
  prow/cluster/jobs/istio/api/istio.api.master.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1537 Enable tide for the istio/common-files repo.
  prow/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1538 Increase timeout on kubernetes postsubmit jobs
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1542 Initial attempt at getting testgrid automation
  Makefile
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  testgrid/default.yaml
  testgrid/istio-generated.yaml
Labels: approved, cla: yes, lgtm, size/L

#1544 Temporarily disable mandiff
  prow/cluster/jobs/istio/operator/istio.operator.master.yaml
Labels: approved, cla: yes, lgtm, size/S

#1540 Switch review settings for operator, pkg, and common-files.
  prow/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1551 Enable Tide + Prow + Branch Protection on the community repo.
  prow/cluster/jobs/istio/community/OWNERS
  prow/cluster/jobs/istio/community/istio.community.master.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm, size/S

#1549 Protect the bots repo.
  prow/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1529 Adding privileged back to postsubmit
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1555 Update prow to v20190729-0247813d7
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1554 Update prow staging with cleaned up tests
  prow/cluster/jobs/istio/istio/istio.istio.prow-staging.yaml
Labels: approved, cla: yes, lgtm, size/L

#1556 Send webhooks to cherrypicker service.
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm, size/S

#1557 Add cherrypicker service and deployment.
  prow/Makefile
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/cherrypicker_service.yaml
Labels: approved, cla: yes, lgtm, size/M

#1558 Enable the cherrypicker plugin across the org.
  prow/plugins.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1492 Read error
  toolbox/errorfinder/README.md
  toolbox/errorfinder/main.go
  vendor/google.golang.org/api/sheets/v4/BUILD.bazel
  vendor/google.golang.org/api/sheets/v4/sheets-gen.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#1553 Add annotations for testgrid
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.2.yaml
  testgrid/default.yaml
  testgrid/istio-generated.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1559 Update prow to v20190730-f3698c9e2
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1560 Update prow to v20190730-bfd5985df
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1561 Enable tide for istio/api.
  prow/config.yaml
  prow/config/config_test.go
Labels: approved, cla: yes, lgtm, size/S

#1562 Update all boskos deployment with latest.
  boskos/Makefile
  boskos/boskos-deployment.yaml
  boskos/cleaner-deployment.yaml
  boskos/mason-deployment.yaml
  boskos/metrics-deployment.yaml
  boskos/reaper-deployment.yaml
Labels: approved, cla: yes, lgtm, size/M

#1552 Enabling rerun of Prow jobs for whitelisted users.
  prow/Makefile
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_rbac.yaml
  prow/config.yaml
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/M

#1563 Enable prow and tide for istio.io
  prow/cluster/jobs/istio/community/istio.community.yaml
  prow/cluster/jobs/istio/istio.io/OWNERS
  prow/cluster/jobs/istio/istio.io/istio.istio.io.yaml
  prow/cluster/jobs/istio/operator/istio.operator.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.yaml
  prow/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1566 Updating field for authorized deck users
  prow/config.yaml
Labels: approved, cla: yes, lgtm, size/XS
