Repository istio/test-infra, pull requests merged in 2019-02, with the labels that each got.

#1167 Update Bazel to 0.22 and LLVM/clang to 7.
  docker/istio/shared/tools/install-bazel.sh
  docker/istio/shared/tools/install-clang.sh
  scripts/tools/linux-install-bazel
  scripts/tools/linux-install-clang
Labels: cla: yes, lgtm

#1169 Create new prowbazel image for bazel 0.22
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
Labels: approved, cla: yes, lgtm

#1170 4.13->5.0 for release 1.1
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.1.yaml
Labels: approved, cla: yes, lgtm

#1172 Add lld linker.
  docker/istio/shared/tools/install-clang.sh
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  scripts/tools/linux-install-clang
Labels: approved, cla: yes, lgtm

#1174 Added myself as owner to test-infra
  OWNERS
Labels: approved, cla: yes, lgtm

#1166 Adding a new prow file for collab-galley branch
  prow/cluster/jobs/istio/istio/istio.istio.collab-galley.yaml
Labels: approved, cla: yes, lgtm

#1175 Fix previous commit.
  docker/istio/shared/tools/install-clang.sh
  scripts/tools/linux-install-clang
Labels: approved, cla: yes, lgtm

#1173 Update build image for istio-proxy to prowbazel:0.5.1.
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.1.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.wasm.yaml
Labels: approved, cla: yes, lgtm

#1168 Enable prow tests for auth-v2 branch
  prow/cluster/jobs/istio/istio/istio.istio.authz-v2.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1176 Require certain tests to pass for authz-v2 branch
  prow/config.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1177 Enable required test tag for authz-v2
  prow/config.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#1178 Enables a manually triggered CNI e2e
  prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml
Labels: approved, cla: yes, lgtm

#1179 Adding more resources to boscos clusters for gke-e2e-tests and perf clusters
  boskos/configs.yaml
Labels: approved, cla: yes, lgtm

#1180 Add trace append to gke cluster oauth scope
  boskos/configs.yaml
Labels: approved, cla: yes, lgtm

#1161 Moving gcsweb and velodrome from istio-io project to istio-testing and code under test-infra
  prow/cluster/cert-manager/cluster-issuer.yaml
  sites/istio.io/Makefile
  sites/istio.io/configmap-nginx.yaml
  sites/istio.io/deployment.yaml
  sites/istio.io/gcsweb/Makefile
  sites/istio.io/gcsweb/README.md
  sites/istio.io/gcsweb/deployment.yaml
  sites/istio.io/gcsweb/service.yaml
  sites/istio.io/service.yaml
  sites/kube-cert-manager/README.md
  sites/kube-cert-manager/istio.io-cert.yaml
Labels: approved, cla: yes, lgtm

#1181 Fix branch protector configuration
  prow/config.yaml
Labels: approved, cla: yes, lgtm
