Repository istio/test-infra, pull requests merged in 2019-11, with the labels that each got.

#2029 Add "genjobs" support for periodics, node selectors, and job type
  prow/Makefile
  prow/genjobs/README.md
  prow/genjobs/cmd/genjobs/main.go
Labels: cla: yes, size/L

#2030 Add istio-private/istio "release_istio_postsubmit_private" job
  prow/Makefile
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/plugins.yaml
Labels: cla: yes, size/XS

#2006 Create job to bump testgrid config
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/S

#2031 Bump prow from v20191030-49516b6be to v20191101-c5bcba610
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2033 Revert "Add "post-test-infra-upload-testgrid-config" job (#2006)"
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/S

#2032 Update istio/istio and istio/api prow to use the latest image
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2034 Add "post-test-infra-upload-testgrid-config" job
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/S

#2035 add more upgrade periodic jobs
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/L

#2038 Bump prow from v20191101-c5bcba610 to v20191104-e7d5b8453
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2039 update 1.4 istio/api image for prow
  prow/cluster/jobs/istio/api/istio.api.release-1.4.gen.yaml
  prow/config/jobs/api-1.4.yaml
Labels: cla: yes, size/XS

#2040 add periodic job for testing upgrade within istio 1.2 patch versions.
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/S

#2041 Install gcloud binaries in /usr/local/bin.
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  scripts/tools/linux-install-gcloud
Labels: cla: yes, size/S

#2042 Remove downloaded tarballs from the prowbazel image.
  docker/istio/shared/tools/install-clang.sh
  docker/istio/shared/tools/install-libcxx.sh
  scripts/tools/linux-install-bazel
  scripts/tools/linux-install-clang
  scripts/tools/linux-install-cmake
  scripts/tools/linux-install-golang
  scripts/tools/linux-install-ninja
  scripts/tools/linux-install-protoc
  scripts/tools/linux-install-repo
  scripts/tools/linux-install-wrk
Labels: cla: yes, size/S

#2043 Preload Bazel 1.1.0 in the build images.
  docker/istio/shared/tools/install-bazel.sh
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  scripts/tools/linux-install-bazel
Labels: cla: yes, size/XS

#2044 Bump istio/proxy release-1.4 and master image to 0.5.16
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml
Labels: cla: yes, size/S

#2046 Updating prow master jobs to use new common build-tools
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/README.md
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2049 remove 1.2 upgrade job
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/S

#2048 Fix post-test-infra-upload-testgrid-config
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/S

#2037 Private Deck instance
  prow/cluster/cert-manager/tls-ing.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/deck_private_rbac.yaml
  prow/cluster/deck_private_service.yaml
Labels: cla: yes, size/L

#2050 Bump prow from v20191104-e7d5b8453 to v20191105-3cd32f35e
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2053 Remove deprecated jobs
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.2.yaml
  prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml
  testgrid/istio.gen.yaml
Labels: cla: yes, size/M

#2051 Updating prow master jobs to use new common build-tools
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2055 Revert "Updating prow master jobs to use new common build-tools (#2051)"
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2056 Add fork-repo arg to Transfigure job
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/XS

#2058 Configure gcs for "istio-private"
  prow/config.yaml
Labels: cla: yes, size/XS

#2059 Make gencheck required for istio/istio
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2062 Update release-1.4 to go 1.13.4
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.4.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.4.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.4.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.4.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.release-1.4.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.4.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.4.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.4.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.4.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.4.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.4.gen.yaml
  prow/config/jobs/client-go-1.4.yaml
  prow/config/jobs/cni-1.4.yaml
  prow/config/jobs/common-files-1.4.yaml
  prow/config/jobs/gogo-genproto-1.4.yaml
  prow/config/jobs/installer-1.4.yaml
  prow/config/jobs/istio-1.4.yaml
  prow/config/jobs/istio.io-1.4.yaml
  prow/config/jobs/operator-1.4.yaml
  prow/config/jobs/pkg-1.4.yaml
  prow/config/jobs/release-builder-1.4.yaml
  prow/config/jobs/tools-1.4.yaml
Labels: cla: yes, size/S

#2063 Update release-builder 1.4 jobs
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.4.gen.yaml
  prow/config/jobs/release-builder-1.4.yaml
Labels: cla: yes, size/M

#2065 Updating prow to bionic (again)
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2066 Revert "Updating prow to bionic (again)"
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2067 Updating prow to bionic (again)
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2068 update build image for istio/api master
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/config/jobs/api.yaml
Labels: cla: yes, size/XS

#2069 Revert "Updating prow to bionic (again)"
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2052 Use GKE managed certs for "prow-private.istio.io"
  prow/cluster/cert-manager/tls-ing.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/prow-private-istio-io_managedcertificate.yaml
Labels: cla: yes, size/S

#2060 Add `channel` flag to Genjobs
  prow/Makefile
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/genjobs/README.md
  prow/genjobs/cmd/genjobs/main.go
Labels: cla: yes, size/M

#2061 Enable spyglass in "deck-private"
  prow/cluster/deck_private_deployment.yaml
Labels: cla: yes, size/XS

#2071 Add new Kubernetes 1.17 postsubmit job
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2072 Updating prow to bionic (again)
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2073 update istio/api master and release-1.4 build image
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.4.gen.yaml
  prow/config/jobs/api-1.4.yaml
  prow/config/jobs/api.yaml
Labels: cla: yes, size/XS

#2054 Use GKE managed cert for "prow.istio.io"
  prow/cluster/prow-istio-io_managedcertificate.yaml
Labels: cla: yes, size/XS

#2075 Disable "long-job-names" warning in checkconfig
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: cla: yes, size/XS

#2077 Revert "Disable "long-job-names" warning in checkconfig"
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: cla: yes, size/XS

#2078 Genjobs: Add "--modifier" flag and truncate job name at 63 characters
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.4.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.4.yaml
  prow/gen-private-jobs.sh
  prow/genjobs/README.md
  prow/genjobs/cmd/genjobs/main.go
Labels: cla: yes, size/M

#2020 Make new installer test required, run in postsubmit
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2080 Kill old proxy periodic
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/S

#2081 Add direct as fallback for GOPROXY
  prow/config.yaml
Labels: cla: yes, size/XS

#2076 Enable GKE cert for "prow.istio.io" and remove cert-manager
  prow/cluster/cert-manager/README.md
  prow/cluster/cert-manager/cluster-issuer.yaml
  prow/cluster/cert-manager/rbac-config.yaml
  prow/cluster/tls-ing.yaml
Labels: cla: yes, size/M

#2082 Revert "Add direct as fallback for GOPROXY"
  prow/config.yaml
Labels: cla: yes, size/XS

#2083 Add a new job to try out proxy-build-tools
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
Labels: cla: yes, size/M

#2084 Override gcr registry in istio/proxy postsubmit
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.4.yaml
  prow/gen-private-jobs.sh
Labels: cla: yes, size/S

#2087 Enable unknown-fields check to catch typos and whitespace problems in ProwJob config.
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2086 genjob enhancements
  prow/genjobs/README.md
  prow/genjobs/cmd/genjobs/main.go
Labels: cla: yes, size/M

#2089 Remove temporary new builder job to bring tide back
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
Labels: cla: yes, size/M

#2090 update client go 1.4 image
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.4.gen.yaml
  prow/config/jobs/client-go-1.4.yaml
Labels: cla: yes, size/XS

#2093 Remove max concurrency for jobs requiring gcp access
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.3.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.4.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.4.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.4.gen.yaml
  prow/config/generate.go
Labels: cla: yes, size/XS

#2088 Support host prefix in genjobs
  prow/genjobs/cmd/genjobs/main.go
  prow/genjobs/pkg/util/os.go
  prow/genjobs/pkg/util/strings.go
Labels: cla: yes, size/M

#2057 Bump prow from v20191105-3cd32f35e to v20191111-3ec17d99d
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2092 Move proxy to prow config generation
  prow/cluster/jobs/istio/proxy/istio.proxy.prow-staging.gen.yaml
  prow/config/generate.go
  prow/config/jobs/proxy.yaml
Labels: cla: yes, size/M

#2098 Switch proxy to config gen for master
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml
  prow/config/jobs/proxy.yaml
Labels: cla: yes, size/L

#2100 Run dry run publish only if code changes
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.4.gen.yaml
  prow/config/jobs/release-builder-1.4.yaml
  prow/config/jobs/release-builder.yaml
Labels: cla: yes, size/XS

#2101 Update build image for istio/istio
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2085 Replace prowbazel with build-tools-proxy
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/config/jobs/proxy.yaml
Labels: cla: yes, size/XS

#2091 Configurable envoy repo in private istio/proxy jobs
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.4.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.4.yaml
  prow/config.yaml
  prow/gen-private-jobs.sh
  prow/genjobs/cmd/genjobs/main.go
  prow/genjobs/pkg/util/strings.go
Labels: cla: yes, size/L

#2095 Bump prow from v20191111-3ec17d99d to v20191113-caf5b4a47
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2105 Bump prow from v20191113-caf5b4a47 to v20191115-8d288a842
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2108 Updated prow build-tools image for client-go
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/config/jobs/client-go.yaml
Labels: cla: yes, ok-to-test, size/XS

#2064 Switch to new "slack_reporter_configs" in prow config
  prow/config.yaml
Labels: cla: yes, size/M

#2102 Consolidate job generation
  Makefile.core.mk
  prow/Makefile
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.4.yaml
  prow/gen-private-jobs.sh
Labels: cla: yes, size/M

#2104 Update installer image
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/config/jobs/installer.yaml
Labels: cla: yes, size/XS

#2109 update to stable "checkconfig" image
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: cla: yes, size/XS

#2113 enable slack reporting for "istio-private"
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.4.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.4.yaml
  prow/gen-private-jobs.sh
Labels: cla: yes, size/S

#2112 genjobs: support `--input` file and `--output` file
  prow/genjobs/README.md
  prow/genjobs/cmd/genjobs/main.go
  prow/genjobs/main_test.go
  prow/genjobs/testdata/simple_transform/private.simple-transform.yaml
  prow/genjobs/testdata/simple_transform/simple-transform.yaml
Labels: cla: yes, size/L

#2116 Bump prow from v20191115-8d288a842 to v20191119-00c5af8fa
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2118 disable RBE in private builds until configured and update .netrc
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.4.yaml
  prow/config.yaml
  prow/gen-private-jobs.sh
Labels: cla: yes, size/XS

#2119 update CODEOWNERS so changes to genjobs does not require oncall
  CODEOWNERS
  prow/Makefile
  prow/genjobs/gen-private-jobs.sh
Labels: cla: yes, size/XS

#2120 configure branch protection for "istio-private"
  prow/config.yaml
Labels: cla: yes, size/S

#2121 set proper env variables for "istio-private/proxy" presubmits
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.4.yaml
  prow/config.yaml
  prow/genjobs/gen-private-jobs.sh
Labels: cla: yes, size/M

#2123 Update prow build-tools image for client-go-1.4
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.4.gen.yaml
  prow/config/jobs/client-go-1.4.yaml
Labels: cla: yes, ok-to-test, size/XS

#2126 Bump prow from v20191119-00c5af8fa to v20191120-b1692ff83
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2106 Authentikos
  authentikos/.gitignore
  authentikos/Dockerfile
  authentikos/Makefile
  authentikos/README.md
  authentikos/authentikos.go
  authentikos/examples/authentikos-deployment.yaml
  authentikos/go.mod
  authentikos/go.sum
Labels: cla: yes, size/XL

#2125 override BAZEL_ENVOY_PATH for local envoy tests
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.4.yaml
  prow/genjobs/gen-private-jobs.sh
Labels: cla: yes, size/S

#2099 Genjobs support for preset resolution.
  prow/genjobs/README.md
  prow/genjobs/cmd/genjobs/main.go
  prow/genjobs/gen-private-jobs.sh
  prow/genjobs/pkg/util/os.go
  prow/genjobs/testdata/simple_transform/private.simple-transform.yaml
Labels: cla: yes, size/L

#2129 disable circleci required status "istio-private"
  prow/config.yaml
Labels: cla: yes, size/XS

#2130 update perf jobs path
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes

#2131 be more explict with yaml anchor merge
  prow/config.yaml
Labels: cla: yes, size/S

#2128 Revert "override BAZEL_ENVOY_PATH for local envoy tests (#2125)"
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.4.yaml
  prow/genjobs/gen-private-jobs.sh
Labels: cla: yes, size/S

#2111 add generic "recover()" handler for genjobs
  prow/genjobs/cmd/genjobs/main.go
Labels: cla: yes, size/S

#2134 Bump prow from v20191120-b1692ff83 to v20191121-1ff2207db
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2107 Use authentikos for release-builder jobs
  prow/Makefile
  prow/Makefile.gcloud.mk
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.4.gen.yaml
  prow/cluster/private/authentikos_deployment.yaml
  prow/cluster/private/authentikos_rbac.yaml
  prow/cluster/private/test_pod_namespace.yaml
  prow/config.yaml
  prow/genjobs/gen-private-jobs.sh
Labels: cla: yes, size/L

#2132 Authentikos: add more robust templating support.
  authentikos/Makefile
  authentikos/README.md
  authentikos/authentikos.go
  authentikos/examples/authentikos-deployment.yaml
Labels: cla: yes, size/L

#2137 Retire the unused tests repo, replace with new cri repo.
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/config.yaml
  prow/config/jobs/cri.yaml
Labels: cla: yes, size/XS

#2138 autodeploy private cluster resources
  prow/cluster/BUILD.bazel
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/XS

#2143 Update to kind v0.6.0
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2141 Add presubmit docker check
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2144 Bump prow from v20191121-1ff2207db to v20191125-84f301627
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2136 enable tide merging for "istio-private"
  prow/config.yaml
Labels: cla: yes, size/S

#2148 Use builder image for tools build
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/XS

#2149 Update to operator image: master-2019-11-26T07-29-27
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/config/jobs/operator.yaml
Labels: cla: yes, size/XS

#2147 Bump prow from v20191125-84f301627 to v20191126-731383c55
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2151 Add var/lib/docker mount for docker jobs
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/generate.go
  prow/config/jobs/istio.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2154 update k8s/test-infra version in go deps
  go.mod
  go.sum
  licenses/contrib.go.opencensus.io/exporter/prometheus/LICENSE
  licenses/contrib.go.opencensus.io/exporter/stackdriver/LICENSE
  licenses/github.com/census-instrumentation/opencensus-proto/LICENSE
  licenses/github.com/go-test/deep/LICENSE
  licenses/github.com/gobuffalo/envy/LICENSE.txt
  licenses/github.com/joho/godotenv/LICENCE
  licenses/github.com/markbates/inflect/LICENCE
  licenses/github.com/tektoncd/pipeline/cmd/imagedigestexporter/kodata/LICENSE
  licenses/github.com/tektoncd/pipeline/cmd/pullrequest-init/kodata/LICENSE
  licenses/golang.org/x/build/LICENSE
  licenses/knative.dev/pkg/LICENSE
  licenses/knative.dev/pkg/third_party/mako/LICENSE
Labels: cla: yes, size/XL

#2155 Enable "allow_cancellations", and suppress warning
  prow/config.yaml
Labels: cla: yes, size/XS

#2152 Update run benchmark path for release 1.4 job
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/XS

#2157 Remove check-config test
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/config/jobs/test-infra.yaml
Labels: cla: yes, size/XS

#2158 Bump prow from v20191126-731383c55 to v20191127-0cc88ec7d
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2159 update "release-builder" jobs w/ env overrides
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.4.gen.yaml
  prow/config.yaml
  prow/genjobs/gen-private-jobs.sh
Labels: cla: yes, size/M

#2142 Genjobs: fix incorrect behavior with --extra-refs
  prow/genjobs/README.md
  prow/genjobs/cmd/genjobs/main.go
  prow/genjobs/main_test.go
  prow/genjobs/testdata/extra-refs_exists/extra-refs_exists_in.yaml
  prow/genjobs/testdata/extra-refs_exists/extra-refs_exists_out.yaml
  prow/genjobs/testdata/extra-refs_not_exists/extra-refs_not_exists_in.yaml
  prow/genjobs/testdata/extra-refs_not_exists/extra-refs_not_exists_out.yaml
  prow/genjobs/testdata/simple_transform/simple_transform_in.yaml
  prow/genjobs/testdata/simple_transform/simple_transform_out.yaml
Labels: cla: yes, size/L

#2153 Genjobs: support rerun authz overriding
  prow/genjobs/README.md
  prow/genjobs/cmd/genjobs/main.go
  prow/genjobs/main_test.go
  prow/genjobs/testdata/rerun-orgs/rerun-orgs_in.yaml
  prow/genjobs/testdata/rerun-orgs/rerun-orgs_out.yaml
  prow/genjobs/testdata/rerun-users/rerun-users_in.yaml
  prow/genjobs/testdata/rerun-users/rerun-users_out.yaml
Labels: cla: yes, size/L

#2156 Update istio postsubmits
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S
