Repository istio/test-infra, pull requests merged in 2020-03, with the labels that each got.

#2449 remove benchmark job for 1.4
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/S

#2450 Add experimental build cache
  prow/cluster/build/buildcache.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/generate.go
  prow/config/istio-private_jobs/istio.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/M

#2448 Genjobs: version bump; document verbose/configs options
  prow/genjobs/Makefile
  prow/genjobs/README.md
Labels: cla: yes, size/S

#2453 Fix namespace for cache PV/PVC
  prow/cluster/build/buildcache.yaml
Labels: cla: yes, size/XS

#2452 Authentikos: use Sprig as the library for template functions
  authentikos/Makefile
  authentikos/README.md
  authentikos/authentikos.go
  authentikos/examples/authentikos-deployment.yaml
  authentikos/examples/authentikos-grandmatriarch-deployment.yaml
  authentikos/go.mod
  authentikos/go.sum
Labels: cla: yes, size/M

#2454 Bump prow from v20200227-045f82e5a to v20200228-31c76444e
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/M

#2458 Generate all deploy and push test-infra jobs
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/config/jobs/test-infra.yaml
Labels: cla: yes, size/L

#2461 Add k8s 1.18 job and cleanup postsubmit
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2463 Automator: update common-files@master in istio/test-infra@master
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#2462 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2466 Revert "Automator: update build-tools:master"
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2465 Increase pod schedule timeout to 5m
  prow/config.yaml
Labels: cla: yes, size/XS

#2464 fix authorship attribution
  prow/config.yaml
Labels: cla: yes, size/XS

#2468 Automator: update common-files@master in istio/test-infra@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#2459 Generate: support generation of Periodics
  go.mod
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/config/generate.go
  prow/config/jobs/istio.io.yaml
  testgrid/default.yaml
Labels: cla: yes, size/L

#2467 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2471 add timeout for benchmark job
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/XS

#2470 Revert "fix authorship attribution"
  prow/config.yaml
Labels: cla: yes, size/XS

#2457 Bump prow from v20200228-31c76444e to v20200305-e8ef9758b
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/M

#2476 Automator: update common-files@master in istio/test-infra@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#2475 Update build-tools updater
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/config/jobs/common-files.yaml
Labels: cla: yes, size/XS

#2477 Revert "Update build-tools updater"
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/config/jobs/common-files.yaml
Labels: cla: yes, size/XS

#2478 Automator: update common-files@master in istio/test-infra@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#2479 Automator: update common-files@master in istio/test-infra@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#2483 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#2481 Automator: improve and simplify error handling
  tools/automator/automator.sh
  tools/automator/utils.sh
Labels: cla: yes, size/M

#2480 consolidate update-common and update-build-tools jobs
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.5.gen.yaml
  prow/config/jobs/common-files-1.5.yaml
  prow/config/jobs/common-files.yaml
  tools/automator/scripts/update-build-tools-image.sh
Labels: cla: yes, size/M

#2482 cleanup branchprotector settings
  prow/config.yaml
Labels: cla: yes, size/XS

#2484 automate mason deployment
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/config/jobs/test-infra.yaml
Labels: cla: yes, size/S

#2486 Automator: proceed with commit if only untracked changed
  tools/automator/automator.sh
Labels: cla: yes, size/XS

#2487 ignore out/ dir
  .gitignore
Labels: cla: yes, size/XS

#2488 Update build-tools job
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/config/jobs/common-files.yaml
  tools/automator/automator.sh
  tools/automator/scripts/update-build-tools-image.sh
Labels: cla: yes, size/S

#2485 Automator: update common-files@master in istio/test-infra@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#2491 Automator: update common-files@master in istio/test-infra@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#2490 Automator: simplify passing of args to bash subprocess
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.4.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.5.gen.yaml
  prow/config/jobs/common-files-1.4.yaml
  prow/config/jobs/common-files-1.5.yaml
  prow/config/jobs/common-files.yaml
  tools/automator/automator.sh
Labels: cla: yes, size/S

#2493 Use test selection for all Istio jobs
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/M

#2472 Bump prow from v20200305-e8ef9758b to v20200305-9e853ce03
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/M

#2494 add presubmit target for multicluster tests
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2473 Genjobs: support local and global defaults
  prow/config/istio-private_jobs/.defaults.yaml
  prow/config/istio-private_jobs/00-clean.yaml
  prow/config/istio-private_jobs/istio.yaml
  prow/config/istio-private_jobs/istio_1.4.yaml
  prow/config/istio-private_jobs/proxy.yaml
  prow/config/istio-private_jobs/proxy_1.4.yaml
  prow/config/istio-private_jobs/release-builder.yaml
  prow/config/istio-private_jobs/release-builder_1.4.yaml
  prow/genjobs/Makefile
  prow/genjobs/README.md
  prow/genjobs/cmd/genjobs/main.go
Labels: cla: yes, size/L

#2495 Bump k8s 1.18 version
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2497 Bump prow from v20200305-9e853ce03 to v20200311-9d5dcfe00
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/M

#2500 Automator: update common-files@master in istio/test-infra@master
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#2498 bump k8s/test-infra dep
  boskos/cmd/mason/main.go
  go.mod
  go.sum
  licenses/bazil.org/fuse/LICENSE
  licenses/contrib.go.opencensus.io/exporter/aws/LICENSE
  licenses/contrib.go.opencensus.io/integrations/ocsql/LICENSE
  licenses/contrib.go.opencensus.io/resource/LICENSE
  licenses/github.com/Azure/azure-amqp-common-go/v2/LICENSE
  licenses/github.com/Azure/azure-service-bus-go/LICENSE
  licenses/github.com/GoogleCloudPlatform/cloudsql-proxy/LICENSE
  licenses/github.com/agnivade/levenshtein/License.txt
  licenses/github.com/andreyvit/diff/LICENSE
  licenses/github.com/devigned/tab/LICENSE
  licenses/github.com/dimchansky/utfbom/LICENSE
  licenses/github.com/go-ini/ini/LICENSE
  licenses/github.com/google/go-replayers/grpcreplay/LICENSE
  licenses/github.com/google/go-replayers/httpreplay/LICENSE
  licenses/github.com/google/subcommands/LICENSE
  licenses/github.com/google/wire/LICENSE
  licenses/github.com/mattn/go-ieproxy/LICENSE
  licenses/github.com/tidwall/pretty/LICENSE
  licenses/github.com/vektah/gqlparser/LICENSE
  licenses/github.com/vektah/gqlparser/validator/imported/LICENSE
  licenses/go.mongodb.org/mongo-driver/LICENSE
  licenses/gocloud.dev/LICENSE
  licenses/gopkg.in/yaml.v1/LICENSE
Labels: cla: yes, size/XXL

#2501 Disable istio.io presubmit test
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/config/jobs/istio.io.yaml
Labels: cla: yes, size/XS

#2456 Fix gopkg path in cache
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/generate.go
Labels: cla: yes, size/XS

#2502 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2499 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2496 Add ipv6 tests
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, ok-to-test, size/S

#2504 Enable IPv6 on the docker daemon
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#2474 Genjobs extrarefs
  prow/config/istio-private_jobs/.defaults.yaml
  prow/genjobs/Makefile
  prow/genjobs/README.md
  prow/genjobs/cmd/genjobs/main.go
  prow/genjobs/main_test.go
  prow/genjobs/testdata/config_file/config_file_cfg.yaml
  prow/genjobs/testdata/config_file/config_file_out.yaml
  prow/genjobs/testdata/refs_exists/refs_exists_in.yaml
  prow/genjobs/testdata/refs_exists/refs_exists_out.yaml
  prow/genjobs/testdata/refs_not_exists/refs_not_exists_in.yaml
  prow/genjobs/testdata/refs_not_exists/refs_not_exists_out.yaml
Labels: cla: yes, size/L

#2505 Update build tools image version
  common/scripts/setup_env.sh
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2506 genjobs: replace refs when extra refs are used
  prow/genjobs/Makefile
  prow/genjobs/README.md
  prow/genjobs/cmd/genjobs/main.go
Labels: cla: yes, size/XS

#2507 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2503 use correct requirements for mason image push
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/config/jobs/test-infra.yaml
Labels: cla: yes, size/XS

#2514 Make multicluster target actually use multicluster
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2516 Add cjwagner as CODEOWNER for authentikos
  CODEOWNERS
Labels: cla: yes, size/XS

#2511 Authentikos: intelligent token refresh
  authentikos/Makefile
  authentikos/README.md
  authentikos/authentikos.go
  authentikos/authentikos_test.go
  authentikos/examples/authentikos-deployment.yaml
  authentikos/examples/authentikos-grandmatriarch-deployment.yaml
  authentikos/go.mod
Labels: cla: yes, size/L

#2517 Authentikos: bump version for istio-private
  prow/cluster/private/authentikos_deployment.yaml
Labels: cla: yes, size/XS

#2518 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#2519 Ensure "get-api-resources" is rerun per distinct cluster
  prow/Makefile
  prow/Makefile.gcloud.mk
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/config/jobs/test-infra.yaml
Labels: cla: yes, size/S

#2513 Bump prow from v20200311-9d5dcfe00 to v20200316-b3233486a
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/M

#2522 Bump to 1.18-rc.1
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2520 Redirect http -> https for gcsweb.istio.io
  prow/cluster/gcsweb/gcsweb_configmap-nginx.yaml
  prow/cluster/gcsweb/gcsweb_deployment.yaml
  prow/cluster/gcsweb/gcsweb_service.yaml
Labels: cla: yes, size/M

#2527 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2526 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2528 Mount grafana token for releae
  prow/cluster/jobs/all-presets.yaml
Labels: cla: yes, size/XS

#2523 Bump prow from v20200316-b3233486a to v20200320-e079f1a17
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/M

#2530 Add private 1.5 jobs
  prow/cluster/jobs/all-presets.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.5.gen.yaml
  prow/cluster/jobs/istio-private/operator/istio-private.operator.release-1.4.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.5.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.5.gen.yaml
  prow/config/istio-private_jobs/istio_1.5.yaml
  prow/config/istio-private_jobs/operator_1.4.yaml
  prow/config/istio-private_jobs/proxy_1.5.yaml
  prow/config/istio-private_jobs/release-builder_1.5.yml
Labels: cla: yes, size/L

#2533 Use netrc in istio-private/istio for go mod
  Makefile.overrides.mk
  prow/cluster/jobs/all-presets.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.4.gen.yaml
  prow/config/istio-private_jobs/istio_1.4.yaml
Labels: cla: yes, size/S

#2535 Fix release builder private deps
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.4.gen.yaml
  prow/config/istio-private_jobs/release-builder_1.4.yaml
Labels: cla: yes, size/XS

#2532 Require multicluster tests in presubmit
  Makefile.core.mk
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2536 Bump prow from v20200320-e079f1a17 to v20200323-ecb75feef
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/M

#2122 enable rerun "deck-private"
  prow/cluster/deck_private_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2534 reduce perf benchmark job timeout
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/XS

#2512 Authentikos: integration tests
  authentikos/Makefile
  authentikos/test/integ-simple.sh
  authentikos/test/lib.sh
  authentikos/test/testdata/authentikos-simple.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/config/jobs/test-infra.yaml
Labels: cla: yes, size/L

#2537 Use go caching in unit tests
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2524 Cleanup gcsweb and velodrome ing object configs: part 1
  prow/cluster/gcsweb/gcsweb_ing.yaml
  prow/cluster/velodrome/velodrome_ing.yaml
Labels: cla: yes, size/S

#2541 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2542 Automator: src/dst branches can be configured independently
  Makefile.core.mk
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.4.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.5.gen.yaml
  prow/config/jobs/common-files-1.4.yaml
  prow/config/jobs/common-files-1.5.yaml
  tools/automator/automator.sh
Labels: cla: yes, size/S

#2540 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/operator.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2539 Update api prow job images
  prow/cluster/jobs/istio/api/istio.api.release-1.5.gen.yaml
  prow/config/jobs/api-1.5.yaml
Labels: cla: yes, size/XS

#2543 Additional change for buildtools non-master jobs
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.4.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.5.gen.yaml
  prow/config/jobs/common-files-1.4.yaml
  prow/config/jobs/common-files-1.5.yaml
Labels: cla: yes, size/XS

#2521 Redirect http -> https for velodrome.istio.io
  prow/cluster/velodrome/velodrome_configmap-nginx.yaml
  prow/cluster/velodrome/velodrome_deployment.yaml
  prow/cluster/velodrome/velodrome_ing.yaml
  prow/cluster/velodrome/velodrome_service.yaml
Labels: cla: yes, size/M

#2545 Avoid potential conflicts in fork branch name
  tools/automator/automator.sh
  tools/automator/utils.sh
Labels: cla: yes, size/S

#2547 Automator: update build-tools:release-1.5
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.5.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.5.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.5.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.5.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.5.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.5.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.5.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.5.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.5.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.5.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.5.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.5.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.5.gen.yaml
  prow/config/jobs/client-go-1.5.yaml
  prow/config/jobs/cni-1.5.yaml
  prow/config/jobs/common-files-1.5.yaml
  prow/config/jobs/gogo-genproto-1.5.yaml
  prow/config/jobs/istio-1.5.yaml
  prow/config/jobs/istio.io-1.5.yaml
  prow/config/jobs/pkg-1.5.yaml
  prow/config/jobs/proxy-1.5.yaml
  prow/config/jobs/release-builder-1.5.yaml
  prow/config/jobs/tools-1.5.yaml
Labels: cla: yes, size/S

#2544 Temporarily disable ipv6 tests
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2549 Refine prune logic
  prow/Makefile
  prow/api-resources.py
Labels: cla: yes, size/S

#2531 Refine script to create-deps-cm for istio-private dependency overrides
  prow/Makefile
  prow/create-deps-cm.sh
Labels: cla: yes, size/M

#2546 Respect errexit and propogate exit code
  tools/automator/automator.sh
  tools/automator/utils.sh
Labels: cla: yes, size/S

#2529 Add perf-dashboard deploy postsubmit
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/XS

#2551 Support kind blacklist in pruned deployments
  prow/Makefile.gcloud.mk
  prow/api-resources.py
Labels: cla: yes, size/S

#2555 Update Kubernetes jobs
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2525 Cleanup gcsweb and velodrome ing object configs: part 2
  prow/cluster/gcsweb/gcsweb_ing_tmp.yaml
  prow/cluster/velodrome/velodrome_ing_tmp.yaml
Labels: cla: yes, size/M

#2554 Automator: update common-files@master in istio/test-infra@master
  Makefile
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#2556 Remove {installer,operator}@master jobs
  prow/cluster/jobs/istio/installer/istio.installer.master.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.master.gen.yaml
  prow/config/jobs/installer.yaml
  prow/config/jobs/operator.yaml
  testgrid/default.yaml
Labels: cla: yes, do-not-merge/hold, size/M

#2557 Restore istio.io presubmit tests as optional
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/config/jobs/istio.io.yaml
Labels: cla: yes, size/XS

#2538 Bump prow from v20200323-ecb75feef to v20200327-2771f83dd
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/M

#2560 Use print() function in both Python 2 and Python 3
  scripts/bazel_to_go.py
Labels: cla: yes, ok-to-test, size/S

#2561 raw_input() was removed from Python on 1/1/2020
  prow/recreate_prow_configmaps.py
Labels: cla: yes, ok-to-test, size/XS
