Repository istio/test-infra, pull requests merged in 2020-11, with the labels that each got.

#3031 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3029 Added Helm3 tests to release-1.8 branch
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.8.gen.yaml
  prow/config/jobs/istio-1.8.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3030 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3034 Automator: update build-tools:release-1.8
  prow/cluster/jobs/istio/api/istio.api.release-1.8.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.8.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.8.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.8.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.8.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.8.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.8.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.8.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.8.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.8.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.8.gen.yaml
  prow/config/jobs/api-1.8.yaml
  prow/config/jobs/client-go-1.8.yaml
  prow/config/jobs/common-files-1.8.yaml
  prow/config/jobs/envoy-1.8.yaml
  prow/config/jobs/gogo-genproto-1.8.yaml
  prow/config/jobs/istio-1.8.yaml
  prow/config/jobs/istio.io-1.8.yaml
  prow/config/jobs/pkg-1.8.yaml
  prow/config/jobs/proxy-1.8.yaml
  prow/config/jobs/release-builder-1.8.yaml
  prow/config/jobs/tools-1.8.yaml
Labels: cla: yes, release-notes-none, size/S

#3035 Fixing prow autobump by using prow controller manager as reference
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/XS

#3019 Add label for prow-controller-manager service
  prow/cluster/prow-controller-manager.yaml
Labels: cla: yes, size/XS

#3037 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3032 Don't delete vendor while deploying monitoring
  prow/Makefile
  prow/cluster/monitoring/mixins/Makefile
Labels: cla: yes, size/XS

#3009 Bump prow from v20201026-f7d653694b to v20201102-45eeca6478
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3033 Add metrics ports for prow/crier and prow/horologium
  prow/cluster/crier_service.yaml
  prow/cluster/horologium_service.yaml
Labels: cla: yes, size/S

#3039 Bump to 1.20 beta 1
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3038 Add missing label on horologium service
  prow/cluster/horologium_service.yaml
Labels: cla: yes, size/XS

#3041 Cleanup unused folder
  docker/prowbazel/Dockerfile
  docker/prowbazel/Makefile
  docker/prowbazel/README.md
  docker/prowbazel/entrypoint
  scripts/tools/linux-install-bazel
  scripts/tools/linux-install-clang
  scripts/tools/linux-install-cmake
  scripts/tools/linux-install-docker
  scripts/tools/linux-install-gcc
  scripts/tools/linux-install-gcloud
  scripts/tools/linux-install-golang
  scripts/tools/linux-install-helm
  scripts/tools/linux-install-ninja
  scripts/tools/linux-install-protoc
  scripts/tools/linux-install-repo
  scripts/tools/linux-install-wrk
Labels: cla: yes, size/XL

#3042 Update perf jobs to release-1.8
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/S

#3043 Fix automator updates of client-go
  tools/automator/automator.sh
Labels: cla: yes, size/XS

#3044 Install Metallb for single cluster too
  common/scripts/kind_provisioner.sh
Labels: cla: yes, size/XS

#3045 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3046 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#3047 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#3040 Bump prow from v20201102-45eeca6478 to v20201109-a36ed74f01
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3048 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3050 Fix autobumper job failed by plank renaming
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/config/jobs/test-infra.yaml
Labels: cla: yes, size/XS

#3051 Support generating periodic jobs for internal repos
  go.mod
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.8.gen.yaml
  prow/config/generate.go
  prow/config/testdata/simple.gen.yaml
  prow/genjobs/cmd/genjobs/main.go
  prow/genjobs/main_test.go
  prow/genjobs/pkg/util/strings_test.go
Labels: cla: yes, size/L

#3054 Automator: update build-tools:release-1.8
  prow/cluster/jobs/istio/api/istio.api.release-1.8.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.8.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.8.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.8.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.8.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.8.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.8.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.8.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.8.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.8.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.8.gen.yaml
  prow/config/jobs/api-1.8.yaml
  prow/config/jobs/client-go-1.8.yaml
  prow/config/jobs/common-files-1.8.yaml
  prow/config/jobs/envoy-1.8.yaml
  prow/config/jobs/gogo-genproto-1.8.yaml
  prow/config/jobs/istio-1.8.yaml
  prow/config/jobs/istio.io-1.8.yaml
  prow/config/jobs/pkg-1.8.yaml
  prow/config/jobs/proxy-1.8.yaml
  prow/config/jobs/release-builder-1.8.yaml
  prow/config/jobs/tools-1.8.yaml
Labels: cla: yes, release-notes-none, size/S

#3057 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3053 Update rbac for istio-prow.
  prow/cluster/prow-controller-manager.yaml
Labels: cla: yes, size/S

#3056 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3062 make pilot-multicluster tests required
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3063 Allow configuring imagePullPolicy with the config generator tools
  prow/config/generate.go
Labels: cla: yes, size/S

#3064 Update the 1.7 images
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.7.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.7.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.7.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.7.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.7.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.7.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.7.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.7.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.7.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.7.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.7.gen.yaml
  prow/config/jobs/api-1.7.yaml
  prow/config/jobs/client-go-1.7.yaml
  prow/config/jobs/common-files-1.7.yaml
  prow/config/jobs/gogo-genproto-1.7.yaml
  prow/config/jobs/istio-1.7.yaml
  prow/config/jobs/istio.io-1.7.yaml
  prow/config/jobs/pkg-1.7.yaml
  prow/config/jobs/proxy-1.7.yaml
  prow/config/jobs/release-builder-1.7.yaml
  prow/config/jobs/tools-1.7.yaml
Labels: cla: yes, size/S

#3049 Bump prow from v20201109-a36ed74f01 to v20201116-dbd60ab192
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3060 Manual update of build-tools:release-1.6
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.6.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.6.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.6.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.6.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.6.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.6.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.6.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.6.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.6.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.6.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.6.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.6.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.6.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.6.gen.yaml
  prow/config/jobs/api-1.6.yaml
  prow/config/jobs/client-go-1.6.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/common-files-1.6.yaml
  prow/config/jobs/gogo-genproto-1.6.yaml
  prow/config/jobs/istio-1.6.yaml
  prow/config/jobs/istio.io-1.6.yaml
  prow/config/jobs/pkg-1.6.yaml
  prow/config/jobs/proxy-1.6.yaml
  prow/config/jobs/release-builder-1.6.yaml
  prow/config/jobs/tools-1.6.yaml
Labels: cla: yes, size/S

#3067 always run security and telemetry mc jobs
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.8.gen.yaml
  prow/config/jobs/istio-1.8.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3066 make pilot-multicluster required in 1.8
  prow/cluster/jobs/istio/istio/istio.istio.release-1.8.gen.yaml
  prow/config/jobs/istio-1.8.yaml
Labels: cla: yes, size/XS

#3069 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3071 Remove obsolete test
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3072 Introduce improvements made in k8s prow monitoring to istio
  prow/cluster/monitoring/mixins/grafana_dashboards/ghproxy.jsonnet
Labels: cla: yes, size/L

#3073 Add Docker requirement to cni 1.6 jobs
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/config/jobs/cni-1.6.yaml
Labels: cla: yes, size/XS

#3070 Remove repos with only `main` from release branch common-file updates
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.7.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.8.gen.yaml
  prow/config/jobs/common-files-1.6.yaml
  prow/config/jobs/common-files-1.7.yaml
  prow/config/jobs/common-files-1.8.yaml
  prow/config/jobs/common-files.yaml
Labels: cla: yes, size/M

#3059 Fix mason for using release channel to create GKE clusters
  boskos/gcp/gke.go
Labels: cla: yes, size/M

#3074 Fix proxy automator job and configgen improvement
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/config/generate.go
  prow/config/jobs/envoy.yaml
  prow/config/testdata/simple.gen.yaml
  prow/genjobs/testdata/env_denylist/env_denylist_in.yaml
  prow/genjobs/testdata/env_denylist/env_denylist_out.yaml
  prow/genjobs/testdata/volume_denylist/volume_denylist_in.yaml
  prow/genjobs/testdata/volume_denylist/volume_denylist_out.yaml
Labels: cla: yes, size/S

#3068 Bump prow from v20201116-dbd60ab192 to v20201123-dbc92a6558
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3075 Changing cluster Deployments to "apps/v1"
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: cla: yes, size/M

#3077 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3079 Update the 1.7 images
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.7.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.7.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.7.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.7.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.7.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.7.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.7.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.7.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.7.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.7.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.7.gen.yaml
  prow/config/jobs/api-1.7.yaml
  prow/config/jobs/client-go-1.7.yaml
  prow/config/jobs/common-files-1.7.yaml
  prow/config/jobs/gogo-genproto-1.7.yaml
  prow/config/jobs/istio-1.7.yaml
  prow/config/jobs/istio.io-1.7.yaml
  prow/config/jobs/pkg-1.7.yaml
  prow/config/jobs/proxy-1.7.yaml
  prow/config/jobs/release-builder-1.7.yaml
  prow/config/jobs/tools-1.7.yaml
Labels: cla: yes, size/S

#2974 Add istio-boskos-perf-06 back after the project migration
  boskos/resources.yaml
Labels: cla: yes, size/XS
