Repository istio/test-infra, pull requests merged in 2020-05, with the labels that each got.

#2629 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#2628 Update build-image and automator jobs for release-1.6
  prow/cluster/jobs/istio/api/istio.api.release-1.6.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.6.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.6.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.6.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.6.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.6.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.6.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.6.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.6.gen.yaml
  prow/config/jobs/api-1.6.yaml
  prow/config/jobs/client-go-1.6.yaml
  prow/config/jobs/common-files-1.6.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/gogo-genproto-1.6.yaml
  prow/config/jobs/istio-1.6.yaml
  prow/config/jobs/istio.io-1.6.yaml
  prow/config/jobs/pkg-1.6.yaml
  prow/config/jobs/proxy-1.6.yaml
  prow/config/jobs/release-builder-1.6.yaml
  prow/config/jobs/tools-1.6.yaml
Labels: cla: yes, size/M

#2607 Run update-ref-docs (dry-run) on presubmit of istio.io
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2632 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2631 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2633 Update CODEOWNERS, so Istio T&R also owns test-infra jobs
  CODEOWNERS
Labels: cla: yes, size/XS

#2634 Bump kind images for kind 0.8.0
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2636 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2635 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2638 Update branch for "update-build-tools-image" jobs on non-master branches
  tools/automator/scripts/update-images.sh
Labels: cla: yes, size/XS

#2641 Automator: update build-tools:release-1.6
  prow/cluster/jobs/istio/api/istio.api.release-1.6.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.6.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.6.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.6.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.6.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.6.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.6.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.6.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.6.gen.yaml
  prow/config/jobs/api-1.6.yaml
  prow/config/jobs/client-go-1.6.yaml
  prow/config/jobs/common-files-1.6.yaml
  prow/config/jobs/gogo-genproto-1.6.yaml
  prow/config/jobs/istio-1.6.yaml
  prow/config/jobs/istio.io-1.6.yaml
  prow/config/jobs/pkg-1.6.yaml
  prow/config/jobs/proxy-1.6.yaml
  prow/config/jobs/release-builder-1.6.yaml
  prow/config/jobs/tools-1.6.yaml
Labels: cla: yes, size/S

#2639 Remove conformance test job
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2642 Update daily perf job to run on release-1.6 and master
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/S

#2643 istio/ti extra ref should always be pinned to master
  prow/cluster/jobs/istio/api/istio.api.release-1.6.gen.yaml
  prow/config/jobs/api-1.6.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/istio.io.yaml
Labels: cla: yes, size/XS

#2622 Bump prow from v20200427-baaf248ed to v20200501-e6124e633
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2646 Automator: bump k8s-prow images
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/XS

#2647 Remove "benchmark_check" job on release-1.6
  prow/cluster/jobs/istio/tools/istio.tools.release-1.6.gen.yaml
  prow/config/jobs/tools-1.6.yaml
Labels: cla: yes, size/S

#2626 Cherrypicker: enable create-issue-on-conflict
  prow/cluster/cherrypicker_deployment.yaml
Labels: cla: yes, size/XS

#2648 Update upgrade job to test 1.5-latest to 1.6-latest and 1.6-latest to master
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/S

#2644 Add extra perf cluster and nighthawk daily job
  boskos/resources.yaml
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/M

#2650 Add prow jobs for upgrade-downgrade tests, upgrade tests, and downgrade tests
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/L

#2652 Enable testing for envoy private and release-1.6
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.master.gen.yaml
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.release-1.4.gen.yaml
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.release-1.5.gen.yaml
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.release-1.6.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.6.gen.yaml
  prow/config/istio-private_jobs/envoy.yaml
  prow/config/jobs/envoy.yaml
  testgrid/default.yaml
Labels: cla: yes, size/S

#2651 Increase boskos resources
  boskos/resources.yaml
Labels: cla: yes, size/XS

#2654 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2655 Enable testing for istio.io private
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.4.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.5.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.6.gen.yaml
  prow/config/istio-private_jobs/istio.io.yaml
Labels: cla: yes, size/XS

#2656 Per review comments in #2650, remove the tests for the upgrade-downgrade scenario
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/M

#2658 Update netrc HOME path
  prow/cluster/jobs/all-presets.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.4.yaml
  prow/config/istio-private_jobs/proxy_1.4.yaml
Labels: cla: yes, size/M

#2598 not hide the controller test
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes

#2649 Bump prow from v20200501-e6124e633 to v20200507-36c6a27f0
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2661 Istio T&R also owns generated and inrepo config jobs
  CODEOWNERS
Labels: cla: yes, size/XS

#2660 Automator: bump k8s-prow images
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/XS

#2653 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2663 Automator: update build-tools:release-1.6
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.6.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.6.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.6.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.6.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.6.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.6.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.6.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.6.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.6.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.6.gen.yaml
  prow/config/jobs/api-1.6.yaml
  prow/config/jobs/client-go-1.6.yaml
  prow/config/jobs/common-files-1.6.yaml
  prow/config/jobs/gogo-genproto-1.6.yaml
  prow/config/jobs/istio-1.6.yaml
  prow/config/jobs/istio.io-1.6.yaml
  prow/config/jobs/pkg-1.6.yaml
  prow/config/jobs/proxy-1.6.yaml
  prow/config/jobs/release-builder-1.6.yaml
  prow/config/jobs/tools-1.6.yaml
Labels: cla: yes, size/S

#2665 Make netlify task optional in istio.io
  prow/config.yaml
Labels: cla: yes, size/XS

#2666 use MULTICLUSTER topology in multicluster tests
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2667 Fix docs postsubmit
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/config/jobs/istio.io.yaml
Labels: cla: yes, size/XS

#2668 Allow ProwJobs to be aborted without completion time.
  prow/cluster/prowjob_customresourcedefinition.yaml
Labels: cla: yes, size/XS

#2662 Bump prow from v20200507-36c6a27f0 to v20200518-8da074ad4
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2672 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2669 Explicitly specify --github-token-path.
  prow/cluster/hook_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/tide_deployment.yaml
Labels: cla: yes, size/XS

#2673 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2671 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2675 Revert update-ref-docs job back to using the SOURCE_BRANCH_NAME for the
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/config/jobs/istio.io.yaml
Labels: cla: yes, size/XS

#2670 Automator: bump k8s-prow images
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/XS

#2677 make controller test required
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2674 Bump prow from v20200518-8da074ad4 to v20200526-c96f7e37b
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2678 Automator: bump k8s-prow images
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/XS

#2617 100% automated release branch job generation
  prow/config/cmd/generate.go
  prow/config/generate.go
  prow/config/generate_test.go
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/tools.yaml
  prow/config/testdata/simple.gen.yaml
  prow/config/testdata/simple.yaml
Labels: cla: yes, size/L

#2676 Remove istio-releases
  prow/config.yaml
  prow/config/config_test.go
  prow/plugins.yaml
Labels: cla: yes, size/M

#2682 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#2681 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/cni.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2683 Add centos job for proxy
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/config/jobs/proxy.yaml
Labels: cla: yes, size/S
