Repository istio/test-infra, pull requests merged in 2020-07, with the labels that each got.

#2751 Manually bump the autobumper.
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/XS

#2752 Bump prow from v20200628-cc1c099dad to v20200703-4509c055d7
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2748 Remove deprecated docker image build
  docker/istio/istio/Dockerfile
  docker/istio/istio/Makefile
  docker/istio/istio/install.sh
  docker/istio/shared/prow-runner.sh
  docker/istio/shared/tools/install-bazel.sh
  docker/istio/shared/tools/install-clang.sh
  docker/istio/shared/tools/install-docker.sh
  docker/istio/shared/tools/install-gcloud.sh
  docker/istio/shared/tools/install-golang.sh
  docker/istio/shared/tools/install-helm.sh
  docker/istio/shared/tools/install-jars.sh
  docker/istio/shared/tools/install-java.sh
  docker/istio/shared/tools/install-kubectl.sh
  docker/istio/shared/tools/install-libcxx.sh
  docker/istio/shared/tools/install-protoc.sh
  docker/istio/shared/tools/install-python.sh
  docker/istio/test-flakey/Dockerfile
  docker/istio/test-flakey/Makefile
  docker/istio/test-flakey/README.md
  docker/istio/test-flakey/install.sh
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XL

#2755 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2756 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2749 Remove unused ci2gubernator
  BUILD.bazel
  toolbox/ci2gubernator/BUILD.bazel
  toolbox/ci2gubernator/Makefile
  toolbox/ci2gubernator/README.md
  toolbox/ci2gubernator/lib/BUILD.bazel
  toolbox/ci2gubernator/lib/ci2gubernator.go
  toolbox/ci2gubernator/main.go
Labels: cla: yes, size/XL

#2758 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2759 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/S

#2754 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2757 Bump prow from v20200703-4509c055d7 to v20200708-1254fdd37f
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2760 Remove flaky run test job
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: cla: yes, size/M

#2750 Remove various unused toolbox functions
  go.mod
  go.sum
  licenses/github.com/golang-collections/collections/LICENSE
  toolbox/errorfinder/BUILD.bazel
  toolbox/errorfinder/README.md
  toolbox/errorfinder/main.go
  toolbox/fixit/BUILD.bazel
  toolbox/fixit/main.go
  toolbox/timecomparer/BUILD.bazel
  toolbox/timecomparer/README.md
  toolbox/timecomparer/main.go
Labels: cla: yes, size/XXL

#2747 Remove unused flaky test code
  flakeyTest/Pair.java
  flakeyTest/README.md
  flakeyTest/TotalFlakey.java
  flakeyTest/daily-flakey-test.sh
  flakeyTest/readPastJunitCommand.sh
  flakeyTest/removeTempFolderCommand.sh
  flakeyTest/testCommand.sh
Labels: cla: yes, size/XL

#2762 Update centos image
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/config/jobs/proxy.yaml
Labels: cla: yes, size/XS

#2765 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2763 Add job for benchmark test in presubmit and postsubmit
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/istio-private_jobs/istio.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2767 Bump build-tools
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2768 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#2769 Remove clarketm from CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/S

#2770 Add docker requirements for perf jobs
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/XS

#2771 Unhide benchmark job
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2772 Temporarily disable all merging
  prow/config.yaml
Labels: cla: yes, size/XS

#2773 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#2766 Bump prow from v20200708-1254fdd37f to v20200710-f1d386e7c4
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2775 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2776 Add docker requirements defined in higher level configs into perf jobs
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/S

#2774 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2778 Update to k8s 1.19 rc
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2777 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#2780 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/S

#2779 Use allowlist and denylist in genjobs and its config
  prow/config/istio-private_jobs/.defaults.yaml
  prow/config/istio-private_jobs/envoy.yaml
  prow/config/istio-private_jobs/istio.io.yaml
  prow/config/istio-private_jobs/istio.yaml
  prow/config/istio-private_jobs/istio_1.4.yaml
  prow/config/istio-private_jobs/istio_1.5.yaml
  prow/config/istio-private_jobs/istio_1.6.yml
  prow/config/istio-private_jobs/operator_1.4.yaml
  prow/config/istio-private_jobs/proxy.yaml
  prow/config/istio-private_jobs/proxy_1.4.yaml
  prow/config/istio-private_jobs/proxy_1.5.yaml
  prow/config/istio-private_jobs/proxy_1.6.yml
  prow/config/istio-private_jobs/release-builder.yaml
  prow/config/istio-private_jobs/release-builder_1.4.yaml
  prow/config/istio-private_jobs/release-builder_1.5.yml
  prow/config/istio-private_jobs/release-builder_1.6.yml
  prow/genjobs/Makefile
  prow/genjobs/README.md
  prow/genjobs/cmd/genjobs/main.go
  prow/genjobs/main_test.go
  prow/genjobs/testdata/env_denylist/env_denylist_in.yaml
  prow/genjobs/testdata/env_denylist/env_denylist_out.yaml
  prow/genjobs/testdata/volume_denylist/volume_denylist_in.yaml
  prow/genjobs/testdata/volume_denylist/volume_denylist_out.yaml
Labels: cla: yes, size/L

#2753 Automator: bump k8s-prow images
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/XS

#2782 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#2783 Automate updating proxy in istio on changes
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/config/jobs/proxy.yaml
Labels: cla: yes, size/S

#2785 Use "allowlist" in prow plugins comment
  prow/plugins.yaml
Labels: cla: yes, size/XS

#2787 Verify that release notes are present
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
  tools/check_release_notes.sh
Labels: cla: yes, size/L

#2790 Make proxy update optional and use build-tools image
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/config/jobs/proxy.yaml
Labels: cla: yes, size/XS

#2791 Fix indentation
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2789 Update boskos cluster to 1.17
  boskos/resources.yaml
Labels: cla: yes, size/XS

#2792 Fix oauth path
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2793 Bikeshed job name
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2788 add analyze-tests job
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2784 Use "denylist" in api-resources.py
  prow/api-resources.py
Labels: cla: yes, size/S

#2794 Added success for label
  tools/check_release_notes.sh
Labels: cla: yes, size/XS

#2797 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2796 Trigger release notes on all pull requests
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
  tools/check_release_notes.sh
Labels: cla: yes, size/XS

#2795 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2800 Revert "Automator: update build-tools:master"
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2801 Update Automator to do make clean gen
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.5.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.6.gen.yaml
  prow/config/jobs/api-1.5.yaml
  prow/config/jobs/api-1.6.yaml
  prow/config/jobs/api.yaml
Labels: cla: yes, size/XS

#2803 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#2802 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#2807 Tune benchmark CPU
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.4.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.4.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/generate.go
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2805 Clarify message for release notes
  tools/check_release_notes.sh
Labels: cla: yes, size/XS

#2810 Delete removed boskos projects
  boskos/resources.yaml
Labels: cla: yes, size/M

#2808 Make AUTOMATOR job to update proxy dependency auto-merge
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/config/jobs/proxy.yaml
Labels: cla: yes, size/XS

#2811 Document automator
  tools/automator/README.md
  tools/automator/automator.sh
Labels: cla: yes, size/L

#2812 Drop boskos version
  boskos/resources.yaml
Labels: cla: yes, size/XS

#2813 Another attempt at go module caching
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.6.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.6.gen.yaml
  prow/config/generate.go
  prow/config/jobs/istio-1.6.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/M

#2809 Add Istio CNI install test job
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2814 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, size/XS

#2781 Bump prow from v20200710-f1d386e7c4 to v20200717-96f632166e
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2816 Fix install CNI test job
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2815 Automator: bump k8s-prow images
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/XS

#2818 Increase scheduling timeout
  prow/config.yaml
Labels: cla: yes, size/XS

#2821 Add prow jobs for release-1.7
  prow/cluster/jobs/istio/api/istio.api.release-1.7.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.7.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.7.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.7.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.7.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.7.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.7.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.7.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.7.gen.yaml
  prow/config/jobs/api-1.7.yaml
  prow/config/jobs/client-go-1.7.yaml
  prow/config/jobs/gogo-genproto-1.7.yaml
  prow/config/jobs/istio-1.7.yaml
  prow/config/jobs/istio.io-1.7.yaml
  prow/config/jobs/pkg-1.7.yaml
  prow/config/jobs/proxy-1.7.yaml
  prow/config/jobs/release-builder-1.7.yaml
  prow/config/jobs/tools-1.7.yaml
Labels: cla: yes, size/XL

#2820 Add branch protection for 1.7 branches
  prow/config.yaml
Labels: cla: yes, size/XS

#2822 Fix some missing jobs
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.7.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.7.gen.yaml
  prow/config/jobs/common-files-1.7.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/envoy.yaml
Labels: cla: yes, size/M

#2823 Remove 1.4 jobs
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.release-1.4.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.4.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.4.gen.yaml
  prow/cluster/jobs/istio-private/operator/istio-private.operator.release-1.4.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.4.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.4.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.4.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.4.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.4.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.4.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.4.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.4.gen.yaml
  prow/cluster/jobs/istio/installer/istio.installer.release-1.4.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.4.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.4.gen.yaml
  prow/cluster/jobs/istio/operator/istio.operator.release-1.4.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.4.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.4.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.4.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.yaml
  prow/config/jobs/api-1.4.yaml
  prow/config/jobs/client-go-1.4.yaml
  prow/config/jobs/cni-1.4.yaml
  prow/config/jobs/common-files-1.4.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto-1.4.yaml
  prow/config/jobs/installer-1.4.yaml
  prow/config/jobs/istio-1.4.yaml
  prow/config/jobs/istio.io-1.4.yaml
  prow/config/jobs/operator-1.4.yaml
  prow/config/jobs/pkg-1.4.yaml
  prow/config/jobs/release-builder-1.4.yaml
  prow/config/jobs/tools-1.4.yaml
Labels: cla: yes, size/XXL

#2824 Touch 1.7 jobs
  prow/cluster/jobs/istio/api/istio.api.release-1.7.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.7.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.7.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.7.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.7.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.7.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.7.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.7.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.7.gen.yaml
  prow/config/jobs/api-1.7.yaml
  prow/config/jobs/client-go-1.7.yaml
  prow/config/jobs/common-files-1.7.yaml
  prow/config/jobs/gogo-genproto-1.7.yaml
  prow/config/jobs/istio-1.7.yaml
  prow/config/jobs/istio.io-1.7.yaml
  prow/config/jobs/pkg-1.7.yaml
  prow/config/jobs/release-builder-1.7.yaml
  prow/config/jobs/tools-1.7.yaml
Labels: cla: yes, size/S

#2826 Bump proxy test as well
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.7.gen.yaml
  prow/config/jobs/proxy-1.7.yaml
Labels: cla: yes, size/XS

#2761 Remove mixer jobs
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2825 Gzip jobs
  prow/plugins.yaml
Labels: cla: yes, size/XS

#2828 Update kubernetes 1.19 image
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2830 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/XS

#2827 Update testgrid dashboard
  testgrid/default.yaml
  testgrid/istio.gen.yaml
Labels: cla: yes, size/L

#2831 Remove unnecessary perf deploy postsubmit job
  prow/cluster/jobs/istio/tools/istio.tools.release-1.6.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.7.gen.yaml
  prow/config/jobs/tools-1.6.yaml
  prow/config/jobs/tools-1.7.yaml
Labels: cla: yes, size/S

#2832 Experimental: cache go build results as well as modules
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/generate.go
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#2834 Apply the release-notes-none to automated PR's
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.7.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.7.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.7.gen.yaml
  prow/config/jobs/api-1.7.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/common-files-1.7.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/proxy-1.7.yaml
  prow/config/jobs/proxy.yaml
Labels: cla: yes, size/S

#2837 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2835 Add build cache to all Istio jobs
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/generate.go
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/M

#2838 Apply the release-notes-none label to cherrypicks
  prow/cluster/cherrypicker_deployment.yaml
Labels: cla: yes, size/XS

#2833 Add prow.k8s.io/gerrit-report-label=Verified label for Prow jobs running with Gerrit
  prow/genjobs/cmd/genjobs/main.go
Labels: cla: yes, ok-to-test, size/S

#2839 Change the field name to support-gerrit-reporting to be less confusing
  prow/genjobs/cmd/genjobs/main.go
Labels: cla: yes, ok-to-test, size/M

#2841 Update perf benchmark job to release 1.7
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/S

#2840 multicluster job uses directory target
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.7.gen.yaml
  prow/config/jobs/istio-1.7.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#2819 Bump prow from v20200717-96f632166e to v20200724-b2cdf8399d
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#2842 Update upgrade/downgrade job to release 1.7
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/S

#2844 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2845 Set auto-merge on update_ref_docs job
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/config/jobs/istio.io.yaml
Labels: cla: yes, size/XS

#2843 Automator: bump k8s-prow images
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/config/jobs/community.yaml
Labels: cla: yes, size/XS

#2836 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.7.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy-1.7.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#2846 Update script to check for release notes files rather than querying GitHub
  tools/check_release_notes.sh
Labels: cla: yes, size/M

#2847 Use PULL_BASE_REF in release-notes-check
  tools/check_release_notes.sh
Labels: cla: yes, size/S

#2849 Remove galley job
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S
