Repository istio/test-infra, pull requests merged in 2021-09, with the labels that each got.

#3534 Upload TestGrid Config directly to GCS
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/prowjob_service_accounts.yaml
  testgrid/default.yaml
Labels: cla: yes, size/L

#3535 Update Prow to v20210901-2242e3ec6b
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3537 Delete Transfigure Jobs
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, size/M

#3536 Update Prow to v20210902-02bdcbd6bf
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3539 Update Prow to v20210902-01e03305a2
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3540 Update Prow to v20210903-cf6e08b05f
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3543 Make istiodremote pilot tests required
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3542 Update Prow to v20210906-6cb55987fb
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3541 A few updates and improvements to Prow configgen tool
  go.mod
  go.sum
  licenses/github.com/ulule/deepcopier/LICENSE
  prow/config/README.md
  prow/config/cmd/generate.go
  prow/config/generate.go
  prow/config/generate_test.go
  prow/config/jobs/.base.yaml
  prow/config/testdata/.base.yaml
  prow/config/testdata/simple.gen.yaml
  prow/config/testdata/simple.yaml
  prow/generate-transform-jobs/main.go
Labels: cla: yes, size/L

#3545 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3546 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3521 Fix periodic proxy update jobs
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.11.gen.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/proxy-1.11.yaml
  prow/config/jobs/proxy.yaml
  testgrid/config.yaml
Labels: cla: yes, size/M

#3544 Update Prow to v20210907-7006ec3f0c
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3547 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M, release-notes-none

#3549 [Prow configgen] Append base requirements when .base.yaml is overlaid
  prow/config/generate.go
Labels: cla: yes, size/XS

#3550 Automator: update build-tools:release-1.10
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.10.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.10.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.10.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.10.gen.yaml
  prow/config/jobs/api-1.10.yaml
  prow/config/jobs/client-go-1.10.yaml
  prow/config/jobs/common-files-1.10.yaml
  prow/config/jobs/envoy-1.10.yaml
  prow/config/jobs/gogo-genproto-1.10.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio.io-1.10.yaml
  prow/config/jobs/pkg-1.10.yaml
  prow/config/jobs/proxy-1.10.yaml
  prow/config/jobs/release-builder-1.10.yaml
  prow/config/jobs/tools-1.10.yaml
Labels: cla: yes, size/S, release-notes-none

#3548 Update Prow to v20210909-3483cd12ba
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3523 Add automation to update common-files for a new build image
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/S

#3552 Fixes to the Prow configgen tool
  prow/config/generate.go
  prow/config/testdata/simple-matrix.gen.yaml
  prow/config/testdata/simple-matrix.yaml
Labels: cla: yes, size/M

#3553 Add optional skipped security-istiodremote job
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#3554 Missing common-files and wrong path to binary
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/XS

#3555 Start Docker for job
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/XS

#3556 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3551 Update Prow to v20210909-6c59eee681
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3560 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3557 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M, release-notes-none

#3562 Revert "Automator: update build-tools:master"
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#3561 Update Prow to v20210913-b6578706d1
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3563 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3559 [release-1.9] Manual update of release 1.9 tools image
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.9.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.9.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.9.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.9.gen.yaml
  prow/config/jobs/api-1.9.yaml
  prow/config/jobs/client-go-1.9.yaml
  prow/config/jobs/common-files-1.9.yaml
  prow/config/jobs/envoy-1.9.yaml
  prow/config/jobs/gogo-genproto-1.9.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.io-1.9.yaml
  prow/config/jobs/pkg-1.9.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/release-builder-1.9.yaml
  prow/config/jobs/tools-1.9.yaml
Labels: cla: yes, size/M

#3564 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M, release-notes-none

#3565 Update Prow to v20210914-d9fade61b4
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3567 Automator: update build-tools:release-1.11
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.11.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.11.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.11.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.11.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.11.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.11.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.11.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.11.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.11.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.11.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.11.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.11.gen.yaml
  prow/config/jobs/api-1.11.yaml
  prow/config/jobs/client-go-1.11.yaml
  prow/config/jobs/common-files-1.11.yaml
  prow/config/jobs/enhancements-1.11.yaml
  prow/config/jobs/gogo-genproto-1.11.yaml
  prow/config/jobs/istio-1.11.yaml
  prow/config/jobs/istio.io-1.11.yaml
  prow/config/jobs/pkg-1.11.yaml
  prow/config/jobs/proxy-1.11.yaml
  prow/config/jobs/release-builder-1.11.yaml
  prow/config/jobs/tools-1.11.yaml
Labels: cla: yes, size/L, release-notes-none

#3568 Add optional skipped telemetry-istiodremote job
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#3566 Update Prow to v20210915-1112f4f614
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3569 Update Prow to v20210916-3c87dfedd5
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3570 Automator: update build-tools:release-1.10
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.10.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.10.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.10.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.10.gen.yaml
  prow/config/jobs/api-1.10.yaml
  prow/config/jobs/client-go-1.10.yaml
  prow/config/jobs/common-files-1.10.yaml
  prow/config/jobs/envoy-1.10.yaml
  prow/config/jobs/gogo-genproto-1.10.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio.io-1.10.yaml
  prow/config/jobs/pkg-1.10.yaml
  prow/config/jobs/proxy-1.10.yaml
  prow/config/jobs/release-builder-1.10.yaml
  prow/config/jobs/tools-1.10.yaml
Labels: cla: yes, size/S, release-notes-none

#3571 Update Prow to v20210920-bd8073b837
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3574 Update Prow to v20210921-6ca431fa31
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3558 Make default build cluster use Workload Identity.
  prow/config.yaml
Labels: cla: yes, size/XS

#3576 Fix boskos service WI annotation.
  boskos/cluster/boskos-deployment.yaml
Labels: cla: yes, size/XS

#3575 Update Prow to v20210922-dceed92199
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3579 Remove `cla:yes` label check from queries for the istio.io repo
  prow/config.yaml
Labels: cla: yes, size/S

#3578 Update Prow to v20210922-3d09bce713
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3581 Bump k8s images
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3580 Update Prow to v20210924-1544aef1b6
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3577 Switch boskos {mason, janitor} to use WI.
  boskos/cluster/janitor-deployment.yaml
  boskos/cluster/mason-deployment.yaml
Labels: cla: yes, size/S

#3582 Update Prow to v20210927-83b202827b
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3585 Add hidden,optional,skipped multicluster istiodremote pilot test
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#3586 Update Prow to v20210928-0afc0f8086
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3573 Adding cosign key env variables to 'release' preset
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.11.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.7.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.8.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.9.gen.yaml
  prow/config/jobs/.base.yaml
  prow/config/jobs/release-builder-1.10.yaml
  prow/config/jobs/release-builder-1.11.yaml
Labels: cla: yes, size/L

#3587 Update Prow to v20210929-8f784792a4
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge

#3589 Make istiodremote telemetry tests required
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3588 Update Prow to v20210930-8bb162050c
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M, auto-merge
