Repository istio/test-infra, pull requests merged in 2021-07, with the labels that each got.

#3411 Update Prow to v20210701-419533b534
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3415 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3414 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3416 Revert "Automator: update build-tools:master"
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#3409 Add periodic job for security fuzz tests
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
  testgrid/config.yaml
Labels: cla: yes, size/XS

#3412 Update Prow to v20210701-3efe91b8cd
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3399 Explicitly define slack report config in each job
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.8.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.7.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.8.gen.yaml
  prow/config/generate.go
Labels: cla: yes, size/S

#3417 Update Prow to v20210705-728bc30968
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3418 Update Prow to v20210705-6238fe35f8
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3423 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3419 Automator: update build-tools:release-1.10
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.10.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.10.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.10.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.10.gen.yaml
  prow/config/jobs/api-1.10.yaml
  prow/config/jobs/client-go-1.10.yaml
  prow/config/jobs/common-files-1.10.yaml
  prow/config/jobs/envoy-1.10.yaml
  prow/config/jobs/gogo-genproto-1.10.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio.io-1.10.yaml
  prow/config/jobs/pkg-1.10.yaml
  prow/config/jobs/proxy-1.10.yaml
  prow/config/jobs/release-builder-1.10.yaml
  prow/config/jobs/tools-1.10.yaml
Labels: cla: yes, release-notes-none, size/S

#3422 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3420 Update Prow to v20210707-3e989f60ab
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3426 Some updates to the Prow configgen tool
  prow/config/README.md
  prow/config/generate.go
Labels: cla: yes, size/M

#3425 Update Prow to v20210707-32dc49e04b
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3429 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3427 Update automator exclude check to exclude files in PR causing event
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  tools/automator/README.md
  tools/automator/automator.sh
Labels: cla: yes, size/M

#3428 Update Prow to v20210712-f6f2d3955b
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3432 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3433 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3434 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3435 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3437 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3436 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3424 Automator: update build-tools:release-1.9
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.9.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.9.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.9.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.9.gen.yaml
  prow/config/jobs/api-1.9.yaml
  prow/config/jobs/client-go-1.9.yaml
  prow/config/jobs/common-files-1.9.yaml
  prow/config/jobs/envoy-1.9.yaml
  prow/config/jobs/gogo-genproto-1.9.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.io-1.9.yaml
  prow/config/jobs/pkg-1.9.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/release-builder-1.9.yaml
  prow/config/jobs/tools-1.9.yaml
Labels: cla: yes, release-notes-none, size/M

#3431 Update Prow to v20210713-49f933a3ed
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3439 Restore api dep update on client-go in all cases
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/config/jobs/api.yaml
Labels: cla: yes, size/S

#3438 Automator: update build-tools:release-1.10
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.10.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.10.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.10.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.10.gen.yaml
  prow/config/jobs/api-1.10.yaml
  prow/config/jobs/client-go-1.10.yaml
  prow/config/jobs/common-files-1.10.yaml
  prow/config/jobs/envoy-1.10.yaml
  prow/config/jobs/gogo-genproto-1.10.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio.io-1.10.yaml
  prow/config/jobs/pkg-1.10.yaml
  prow/config/jobs/proxy-1.10.yaml
  prow/config/jobs/release-builder-1.10.yaml
  prow/config/jobs/tools-1.10.yaml
Labels: cla: yes, release-notes-none, size/S

#3430 Add branch protection to 1.11
  prow/config.yaml
Labels: cla: yes, size/XS

#3442 Add jobs for 1.11
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.11.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.11.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.11.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.11.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.11.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.11.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.11.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.11.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.11.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.11.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.11.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.11.gen.yaml
  prow/config/istio-private_jobs/api-1.11.yaml
  prow/config/istio-private_jobs/envoy-1.11.yaml
  prow/config/istio-private_jobs/istio-1.11.yaml
  prow/config/istio-private_jobs/istio.io-1.11.yaml
  prow/config/istio-private_jobs/proxy-1.11.yaml
  prow/config/istio-private_jobs/release-builder-1.11.yaml
  prow/config/jobs/api-1.11.yaml
  prow/config/jobs/client-go-1.11.yaml
  prow/config/jobs/common-files-1.11.yaml
  prow/config/jobs/enhancements-1.11.yaml
  prow/config/jobs/gogo-genproto-1.11.yaml
  prow/config/jobs/istio-1.11.yaml
  prow/config/jobs/istio.io-1.11.yaml
  prow/config/jobs/pkg-1.11.yaml
  prow/config/jobs/proxy-1.11.yaml
  prow/config/jobs/release-builder-1.11.yaml
  prow/config/jobs/tools-1.11.yaml
  testgrid/config.yaml
Labels: cla: yes, size/XXL

#3440 Fix automator script failing on exit code of 1 from grep
  tools/automator/automator.sh
Labels: cla: yes, size/XS

#3443 Workaround prow library limitations to properly hide jobs
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.11.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.7.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.8.gen.yaml
  prow/config/generate.go
Labels: cla: yes, size/XS

#3441 Update Prow to v20210714-ac233fa9c6
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3445 Update to use `make` for conistency across branching
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/config/jobs/istio.io.yaml
Labels: cla: yes, size/XS

#3444 Update Prow to v20210714-62f15287bd
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3446 Update Prow to v20210715-871d72532d
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3449 Add job with assertions enabled
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#3448 Update Prow to v20210716-430fa04d50
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3450 Use 1.11 images for 1.11 jobs
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.11.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.11.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.11.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.11.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.11.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.11.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.11.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.11.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.11.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.11.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.11.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.11.gen.yaml
  prow/config/jobs/api-1.11.yaml
  prow/config/jobs/client-go-1.11.yaml
  prow/config/jobs/common-files-1.11.yaml
  prow/config/jobs/enhancements-1.11.yaml
  prow/config/jobs/gogo-genproto-1.11.yaml
  prow/config/jobs/istio-1.11.yaml
  prow/config/jobs/istio.io-1.11.yaml
  prow/config/jobs/pkg-1.11.yaml
  prow/config/jobs/proxy-1.11.yaml
  prow/config/jobs/release-builder-1.11.yaml
  prow/config/jobs/tools-1.11.yaml
Labels: cla: yes, size/L

#3453 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3454 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3451 Update Prow to v20210720-5548472063
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3456 Bump 1.22 image
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3455 Update Prow to v20210721-e4ef4dafee
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3457 Automator: update build-tools:release-1.10
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.10.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.10.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.10.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.10.gen.yaml
  prow/config/jobs/api-1.10.yaml
  prow/config/jobs/client-go-1.10.yaml
  prow/config/jobs/common-files-1.10.yaml
  prow/config/jobs/envoy-1.10.yaml
  prow/config/jobs/gogo-genproto-1.10.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio.io-1.10.yaml
  prow/config/jobs/pkg-1.10.yaml
  prow/config/jobs/proxy-1.10.yaml
  prow/config/jobs/release-builder-1.10.yaml
  prow/config/jobs/tools-1.10.yaml
Labels: cla: yes, release-notes-none, size/S

#3458 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3463 Automator: update build-tools:release-1.11
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.11.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.11.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.11.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.11.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.11.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.11.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.11.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.11.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.11.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.11.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.11.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.11.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.11.gen.yaml
  prow/config/jobs/api-1.11.yaml
  prow/config/jobs/client-go-1.11.yaml
  prow/config/jobs/common-files-1.11.yaml
  prow/config/jobs/enhancements-1.11.yaml
  prow/config/jobs/gogo-genproto-1.11.yaml
  prow/config/jobs/istio-1.11.yaml
  prow/config/jobs/istio.io-1.11.yaml
  prow/config/jobs/pkg-1.11.yaml
  prow/config/jobs/proxy-1.11.yaml
  prow/config/jobs/release-builder-1.11.yaml
  prow/config/jobs/tools-1.11.yaml
Labels: cla: yes, release-notes-none, size/L

#3462 Fix release notes to use gh pr view
  tools/check_release_notes.sh
Labels: cla: yes, size/S

#3464 Revert "Fix release notes to use gh pr view"
  tools/check_release_notes.sh
Labels: cla: yes, size/S

#3461 Update Prow to v20210722-a7efb93946
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3466 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3465 Update Prow to v20210723-55eee17612
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3468 Test Kubernetes 1.22 on 1.10
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.11.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.11.gen.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio-1.11.yaml
Labels: cla: yes, size/S

#3467 Update Prow to v20210727-b2b0794248
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3469 Update Prow to v20210728-b79cedd058
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3471 Update the modifier values for Prow configgen to disambiguate
  prow/config/README.md
  prow/config/generate.go
  prow/config/jobs/api-1.10.yaml
  prow/config/jobs/api-1.11.yaml
  prow/config/jobs/api-1.9.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/enhancements-1.11.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio-1.11.yaml
  prow/config/jobs/istio-1.7.yaml
  prow/config/jobs/istio-1.8.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.io-1.10.yaml
  prow/config/jobs/istio.io-1.11.yaml
  prow/config/jobs/istio.io-1.7.yaml
  prow/config/jobs/istio.io-1.8.yaml
  prow/config/jobs/istio.io-1.9.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy-1.10.yaml
  prow/config/jobs/proxy-1.8.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/release-builder-1.10.yaml
  prow/config/jobs/release-builder-1.11.yaml
  prow/config/jobs/release-builder-1.7.yaml
  prow/config/jobs/release-builder-1.8.yaml
  prow/config/jobs/release-builder-1.9.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/tools.yaml
  prow/config/testdata/simple.gen.yaml
  prow/config/testdata/simple.yaml
Labels: cla: yes, size/L

#3472 Revert "Revert "Fix release notes to use gh pr view (#3462)" (#3464)"
  tools/check_release_notes.sh
Labels: cla: yes, size/S

#3473 Revert "Revert "Revert "Fix release notes to use gh pr view (#3462)" …
  tools/check_release_notes.sh
Labels: cla: yes, size/S

#3474 Fix notes path
  tools/check_release_notes.sh
Labels: cla: yes, size/XS

#3470 Update Prow to v20210729-79c386fdf5
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M

#3475 Add token
  tools/check_release_notes.sh
Labels: cla: yes, size/S

#3476 Add PR Number and Pr Owner
  tools/check_release_notes.sh
Labels: cla: yes, size/XS

#3478 Add test selector to cni postsubmit job.
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3477 Update Prow to v20210729-6b709c5ea0
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: auto-merge, cla: yes, size/M
