Repository istio/test-infra, pull requests merged in 2021-04, with the labels that each got.

#3239 Fix release 1.9 centos build image.
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.8.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/config/jobs/proxy-1.8.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/proxy.yaml
Labels: cla: yes, size/S

#3240 Remove docker and entrypoint from centos job.
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.8.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/config/jobs/proxy-1.8.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/proxy.yaml
Labels: cla: yes, size/XS

#3231 automator - Add option to exclude file/path on git diff
  tools/automator/README.md
  tools/automator/automator.sh
Labels: cla: yes, size/S

#3242 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3237 Update Prow to v20210404-ef7abaaa70
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3245 Add enhancements repo
  prow/config.yaml
Labels: cla: yes, size/XS

#3243 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/envoy-1.9.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3247 Add branch protection for release-1.10
  prow/config.yaml
Labels: cla: yes, size/XS

#3249 Add release-1.10 Prow job configs
  prow/cluster/jobs/istio/api/istio.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.10.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.10.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.10.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.10.gen.yaml
  prow/config/jobs/api-1.10.yaml
  prow/config/jobs/client-go-1.10.yaml
  prow/config/jobs/common-files-1.10.yaml
  prow/config/jobs/gogo-genproto-1.10.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio.io-1.10.yaml
  prow/config/jobs/pkg-1.10.yaml
  prow/config/jobs/proxy-1.10.yaml
  prow/config/jobs/release-builder-1.10.yaml
  prow/config/jobs/tools-1.10.yaml
  testgrid/config.yaml
Labels: cla: yes, size/XXL

#3250 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3251 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3253 Update base image
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.8.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/config/jobs/proxy-1.10.yaml
  prow/config/jobs/proxy-1.8.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/proxy.yaml
Labels: cla: yes, size/S

#3252 Automator: update build-tools:release-1.10
  prow/cluster/jobs/istio/api/istio.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.10.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.10.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.10.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.10.gen.yaml
  prow/config/jobs/api-1.10.yaml
  prow/config/jobs/client-go-1.10.yaml
  prow/config/jobs/common-files-1.10.yaml
  prow/config/jobs/gogo-genproto-1.10.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio.io-1.10.yaml
  prow/config/jobs/pkg-1.10.yaml
  prow/config/jobs/proxy-1.10.yaml
  prow/config/jobs/release-builder-1.10.yaml
  prow/config/jobs/tools-1.10.yaml
Labels: cla: yes, release-notes-none, size/S

#3254 Update update-images.sh
  tools/automator/scripts/update-images.sh
Labels: cla: yes, size/XS

#3259 Fix master branch common files
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#3258 Bump kubernetes jobs
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#3256 Automator: update build-tools:release-1.9
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.9.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.9.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.9.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.9.gen.yaml
  prow/config/jobs/api-1.9.yaml
  prow/config/jobs/client-go-1.9.yaml
  prow/config/jobs/common-files-1.9.yaml
  prow/config/jobs/envoy-1.9.yaml
  prow/config/jobs/gogo-genproto-1.9.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.io-1.9.yaml
  prow/config/jobs/pkg-1.9.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/release-builder-1.9.yaml
  prow/config/jobs/tools-1.9.yaml
Labels: cla: yes, release-notes-none, size/S

#3257 Automator: update build-tools:release-1.8
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.8.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.8.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.8.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.8.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.8.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.8.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.8.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.8.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.8.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.8.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.8.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.8.gen.yaml
  prow/config/jobs/api-1.8.yaml
  prow/config/jobs/client-go-1.8.yaml
  prow/config/jobs/common-files-1.8.yaml
  prow/config/jobs/envoy-1.8.yaml
  prow/config/jobs/gogo-genproto-1.8.yaml
  prow/config/jobs/istio-1.8.yaml
  prow/config/jobs/istio.io-1.8.yaml
  prow/config/jobs/pkg-1.8.yaml
  prow/config/jobs/proxy-1.8.yaml
  prow/config/jobs/release-builder-1.8.yaml
  prow/config/jobs/tools-1.8.yaml
Labels: cla: yes, release-notes-none, size/S

#3255 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/envoy-1.9.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3260 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3222 Prow config generator supports configuring annotations with requirement presets
  prow/config/generate.go
  prow/config/requirement.go
  prow/config/testdata/.global.yaml
  prow/config/testdata/simple.gen.yaml
  prow/config/testdata/simple.yaml
Labels: cla: yes, size/S

#3261 Update presets for 1.8 1.9 and 1.10
  prow/cluster/jobs/all-presets.yaml
Labels: cla: yes, size/S

#3262 Update presets for 1.8 1.9 and 1.10
  prow/cluster/jobs/all-presets.yaml
Labels: cla: yes, size/S

#3263 Add API
  prow/cluster/jobs/all-presets.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/config/istio-private_jobs/api-1.10.yaml
  prow/config/istio-private_jobs/api-1.7.yaml
  prow/config/istio-private_jobs/api-1.8.yaml
  prow/config/istio-private_jobs/api-1.9.yaml
  prow/config/istio-private_jobs/api.yaml
  prow/config/istio-private_jobs/istio.yaml
  prow/config/istio-private_jobs/istio_1.4.yaml
  prow/config/istio-private_jobs/proxy_1.4.yaml
  prow/config/istio-private_jobs/release-builder.yaml
  prow/config/istio-private_jobs/release-builder_1.4.yaml
Labels: cla: yes, size/L

#3265 Add a postsubmit job for CNI
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#3266 Unhide 1.21+ jobs and use stable release
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3267 Add github-optional
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.8.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.8.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.9.gen.yaml
  prow/config/jobs/.global.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio-1.8.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/release-builder-1.10.yaml
  prow/config/jobs/release-builder-1.8.yaml
  prow/config/jobs/release-builder-1.9.yaml
  prow/config/jobs/release-builder.yaml
Labels: cla: yes, size/S

#3268 Update periodic update of istio test ref in istio.io to 1.10.
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/config/jobs/istio.io.yaml
Labels: cla: yes, size/XS

#3270 Update latest k8s for tests, move 1.21 postsubmit to 1.20 for coverage
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#3271 Update the kind images to latest for testing. 1.20 done by presubmit.
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/config/jobs/istio-1.10.yaml
Labels: cla: yes, size/XS

#3246 Update Prow to v20210412-ed35ec0cee
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3274 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3273 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/envoy-1.9.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3275 Istio prow: deck use workload identity
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_rbac.yaml
Labels: cla: yes, size/XS

#3276 Hot fix workload identity annotation for deck sa
  prow/cluster/deck_rbac.yaml
Labels: cla: yes, size/XS

#3279 Hot fix: add part-of: prow label to all newly added rbac
  prow/cluster/crier_rbac.yaml
  prow/cluster/deck_rbac.yaml
  prow/cluster/hook_rbac.yaml
  prow/cluster/horologium_rbac.yaml
  prow/cluster/sinker_rbac.yaml
  prow/cluster/tide_rbac.yaml
Labels: cla: yes, size/M

#3278 Add prefixes private repos
  prow/cluster/jobs/all-presets.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.9.gen.yaml
  prow/config/istio-private_jobs/istio.yaml
  prow/config/istio-private_jobs/istio_1.8.yml
  prow/config/istio-private_jobs/istio_1.9.yml
  prow/config/istio-private_jobs/proxy.yaml
  prow/config/istio-private_jobs/proxy_1.8.yml
  prow/config/istio-private_jobs/proxy_1.9.yml
  prow/config/istio-private_jobs/release-builder.yaml
  prow/config/istio-private_jobs/release-builder_1.8.yml
  prow/config/istio-private_jobs/release-builder_1.9.yml
Labels: cla: yes, size/M

#3280 Change secret to configmap
  prow/cluster/jobs/all-presets.yaml
Labels: cla: yes, size/S

#3281 Change $HOME to /home
  prow/cluster/jobs/all-presets.yaml
Labels: cla: yes, size/XS

#3282 Add private jobs for 1.10
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.10.gen.yaml
  prow/config/istio-private_jobs/istio_1.10.yml
  prow/config/istio-private_jobs/proxy_1.10.yml
  prow/config/istio-private_jobs/release-builder_1.10.yml
Labels: cla: yes, size/M

#3283 Add private jobs for 1.10
  prow/config/istio-private_jobs/envoy.yaml
Labels: cla: yes, size/XS

#3284 Add envoy-1.10 jobs
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.10.gen.yaml
  prow/config/jobs/envoy-1.10.yaml
  testgrid/config.yaml
Labels: cla: yes, size/M

#3285 Unhide 1.21 integration test for 1.10
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/config/jobs/istio-1.10.yaml
Labels: cla: yes, size/XS

#3286 Update Envoy images
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.master.gen.yaml
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.10.gen.yaml
  prow/config/jobs/envoy-1.10.yaml
  prow/config/jobs/envoy.yaml
Labels: cla: yes, size/XS

#3272 Update Prow to v20210419-8262f2d0c6
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3289 Delete unused tot resources
  prow/cluster/tot_deployment.yaml
  prow/cluster/tot_service.yaml
Labels: cla: yes, size/M

#3290 Use explicit github-token-path flag
  prow/cluster/cherrypicker_deployment.yaml
Labels: cla: yes, size/XS

#3291 Automator: update build-tools:release-1.10
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.10.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.10.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.10.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.10.gen.yaml
  prow/config/jobs/api-1.10.yaml
  prow/config/jobs/client-go-1.10.yaml
  prow/config/jobs/common-files-1.10.yaml
  prow/config/jobs/envoy-1.10.yaml
  prow/config/jobs/gogo-genproto-1.10.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio.io-1.10.yaml
  prow/config/jobs/pkg-1.10.yaml
  prow/config/jobs/proxy-1.10.yaml
  prow/config/jobs/release-builder-1.10.yaml
  prow/config/jobs/tools-1.10.yaml
Labels: cla: yes, release-notes-none, size/S

#3292 Add periodic job to for envoy-1.10 from envoy-1.9
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.9.gen.yaml
  prow/config/jobs/envoy-1.10.yaml
  prow/config/jobs/envoy-1.9.yaml
  testgrid/config.yaml
Labels: cla: yes, size/S

#3294 Remove periodic envoy job which inadvertantly got merged.
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.10.gen.yaml
  prow/config/jobs/envoy-1.10.yaml
  testgrid/config.yaml
Labels: cla: yes, size/S

#3296 Disable RBE in 1.5/1.6 private
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.5.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.6.gen.yaml
Labels: cla: yes, size/XS

#3297 Add periodic job to istio/proxy 1.10 branch to get latest envoy 1.18 …
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.10.gen.yaml
  prow/config/jobs/envoy-1.10.yaml
  testgrid/config.yaml
Labels: cla: yes, size/XS

#3298 Disable release notes job in private repo
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/config/istio-private_jobs/istio_1.10.yml
  prow/config/istio-private_jobs/istio_1.6.yml
  prow/config/istio-private_jobs/istio_1.7.yml
  prow/config/istio-private_jobs/istio_1.8.yml
  prow/config/istio-private_jobs/istio_1.9.yml
Labels: cla: yes, size/S

#3300 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3301 Automator: update build-tools:release-1.9
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.9.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.9.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.9.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.9.gen.yaml
  prow/config/jobs/api-1.9.yaml
  prow/config/jobs/client-go-1.9.yaml
  prow/config/jobs/common-files-1.9.yaml
  prow/config/jobs/envoy-1.9.yaml
  prow/config/jobs/gogo-genproto-1.9.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.io-1.9.yaml
  prow/config/jobs/pkg-1.9.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/release-builder-1.9.yaml
  prow/config/jobs/tools-1.9.yaml
Labels: cla: yes, size/M

#3244 Istio prow: enable secret managed by kubernetes external secrets
  prow/README.md
  prow/cluster/kubernetes-external-secrets_crd.yaml
  prow/cluster/kubernetes-external-secrets_deployment.yaml
  prow/cluster/kubernetes-external-secrets_rbac.yaml
  prow/cluster/kubernetes-external-secrets_service.yaml
  prow/cluster/monitoring/mixins/lib/config.libsonnet
  prow/cluster/monitoring/mixins/prometheus/external_secret_alerts.libsonnet
  prow/cluster/monitoring/mixins/prometheus/prometheus.libsonnet
  prow/cluster/monitoring/prow_servicemonitors.yaml
Labels: cla: yes, size/L

#3303 automator.sh now creates tickets in istio/istio on failed merges
  tools/automator/automator.sh
Labels: cla: yes, size/S

#3295 Update Prow to v20210426-51fd28eca9
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3302 Add a CNI presubmit test job.
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#3305 Don't fail automator's merge workflow if there's a merge conflict
  tools/automator/automator.sh
Labels: cla: yes, size/XS
