Repository istio/test-infra, pull requests merged in 2021-01, with the labels that each got.

#3105 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3106 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3107 Bump prow from v20201228-15d664642a to v20210105-c50d055243
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3110 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#3112 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3113 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3111 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3114 Fix go generate branch to skip non yaml/yml files
  go.sum
  prow/config/cmd/generate.go
Labels: cla: yes, size/S

#3115 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3109 Bump prow from v20210105-c50d055243 to v20210111-f6f01a1373
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3116 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3118 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3120 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3119 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3124 Fix misleading logs
  prow/config/cmd/generate.go
Labels: cla: yes, size/S

#3123 Create 1.9 jobs
  prow/cluster/jobs/istio/api/istio.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.9.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.9.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.9.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.9.gen.yaml
  prow/config/jobs/api-1.9.yaml
  prow/config/jobs/client-go-1.9.yaml
  prow/config/jobs/common-files-1.9.yaml
  prow/config/jobs/gogo-genproto-1.9.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.io-1.9.yaml
  prow/config/jobs/pkg-1.9.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/release-builder-1.9.yaml
  prow/config/jobs/tools-1.9.yaml
  testgrid/default.yaml
Labels: cla: yes, size/XL

#3122 Add branch protection for 1.9 branches
  prow/config.yaml
Labels: cla: yes, size/XS

#3121 Add test for Kubernetes v1.21.0-alpha.1
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#3126 Automator: update build-tools:release-1.9
  prow/cluster/jobs/istio/api/istio.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.9.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.9.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.9.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.9.gen.yaml
  prow/config/jobs/api-1.9.yaml
  prow/config/jobs/client-go-1.9.yaml
  prow/config/jobs/common-files-1.9.yaml
  prow/config/jobs/gogo-genproto-1.9.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.io-1.9.yaml
  prow/config/jobs/pkg-1.9.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/release-builder-1.9.yaml
  prow/config/jobs/tools-1.9.yaml
Labels: cla: yes, release-notes-none, size/S

#3127 bump autobumper to working image
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
Labels: cla: yes, ok-to-test, size/XS

#3103 Bump upgrade periodic jobs to version 1.9
  prow/cluster/jobs/all-periodics.yaml
Labels: cla: yes, size/M

#3128 Refactor the configgen tool
  prow/config/README.md
  prow/config/cmd/generate.go
  prow/config/generate.go
  prow/config/generate_test.go
  prow/config/jobs/.global.yaml
  prow/config/jobs/istio-1.8.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.yaml
  prow/config/requirement.go
  prow/config/testdata/.global.yaml
  prow/config/testdata/simple-matrix.gen.yaml
  prow/config/testdata/simple-matrix.yaml
  prow/config/testdata/simple.gen.yaml
  prow/config/testdata/simple.yaml
Labels: cla: yes, size/XXL

#3129 Allowlist and denylist can be specified as regex for the genjobs tool
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.7.gen.yaml
  prow/genjobs/cmd/genjobs/main.go
Labels: cla: yes, size/S

#3131 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3132 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3133 Temporarily make istio doc test pre-submit (they have known failures)
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/config/jobs/istio.io.yaml
Labels: cla: yes, size/XS

#3117 Bump prow from v20210111-f6f01a1373 to v20210119-c4c19e6d20
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3136 Allow chizhg to rerun Istio Prow jobs through UI
  prow/config.yaml
Labels: cla: yes, size/XS

#3137 manual build tools bump
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#3138 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#3141 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#3142 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3143 Automator: update common-files@master in istio/test-infra@master
  .gitattributes
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3144 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3145 Make security and telemetry MC tests required
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3140 Temporarily disable istio.io multicluster test in postsubmit
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/config/jobs/istio.io.yaml
Labels: cla: yes, size/XS

#3146 Prune legacy jobs
  prow/cluster/jobs/istio/api/istio.api.release-1.5.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.6.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.5.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.6.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.5.gen.yaml
  prow/cluster/jobs/istio/cni/istio.cni.release-1.6.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.5.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.6.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.5.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.6.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.5.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.6.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.5.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.6.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.5.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.6.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.5.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.6.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.5.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.6.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.5.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.6.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.5.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.6.gen.yaml
  prow/config/jobs/api-1.5.yaml
  prow/config/jobs/api-1.6.yaml
  prow/config/jobs/client-go-1.5.yaml
  prow/config/jobs/client-go-1.6.yaml
  prow/config/jobs/cni-1.5.yaml
  prow/config/jobs/cni-1.6.yaml
  prow/config/jobs/common-files-1.5.yaml
  prow/config/jobs/common-files-1.6.yaml
  prow/config/jobs/envoy-1.5.yaml
  prow/config/jobs/envoy-1.6.yaml
  prow/config/jobs/gogo-genproto-1.5.yaml
  prow/config/jobs/gogo-genproto-1.6.yaml
  prow/config/jobs/istio-1.5.yaml
  prow/config/jobs/istio-1.6.yaml
  prow/config/jobs/istio.io-1.5.yaml
  prow/config/jobs/istio.io-1.6.yaml
  prow/config/jobs/pkg-1.5.yaml
  prow/config/jobs/pkg-1.6.yaml
  prow/config/jobs/proxy-1.5.yaml
  prow/config/jobs/proxy-1.6.yaml
  prow/config/jobs/release-builder-1.5.yaml
  prow/config/jobs/release-builder-1.6.yaml
  prow/config/jobs/tools-1.5.yaml
  prow/config/jobs/tools-1.6.yaml
  testgrid/default.yaml
Labels: cla: yes, size/XXL

#3147 Remove legacy generated file
  testgrid/istio.gen.yaml
Labels: cla: yes, size/XS

#3148 Revert "Automator: update build-tools:release-1.9"
  prow/cluster/jobs/istio/api/istio.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.9.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.9.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.9.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.9.gen.yaml
  prow/config/jobs/api-1.9.yaml
  prow/config/jobs/client-go-1.9.yaml
  prow/config/jobs/common-files-1.9.yaml
  prow/config/jobs/gogo-genproto-1.9.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.io-1.9.yaml
  prow/config/jobs/pkg-1.9.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/release-builder-1.9.yaml
  prow/config/jobs/tools-1.9.yaml
Labels: cla: yes, size/S

#3149 Automator: update build-tools:release-1.9
  prow/cluster/jobs/istio/api/istio.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.9.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.9.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.9.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.9.gen.yaml
  prow/config/jobs/api-1.9.yaml
  prow/config/jobs/client-go-1.9.yaml
  prow/config/jobs/common-files-1.9.yaml
  prow/config/jobs/gogo-genproto-1.9.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.io-1.9.yaml
  prow/config/jobs/pkg-1.9.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/release-builder-1.9.yaml
  prow/config/jobs/tools-1.9.yaml
Labels: cla: yes, release-notes-none, size/S

#3139 Bump prow from v20210119-c4c19e6d20 to v20210123-aa0de54ee1
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3150 Exempt istio-release-robot from slack manual merge warnings.
  prow/plugins.yaml
Labels: cla: yes, size/XS

#3153 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3154 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3155 Modify prow/config/istio-private_jobs with 1.8 and 1.9 branches
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.9.gen.yaml
  prow/config/istio-private_jobs/envoy.yaml
  prow/config/istio-private_jobs/istio.io.yaml
  prow/config/istio-private_jobs/istio_1.8.yml
  prow/config/istio-private_jobs/istio_1.9.yml
  prow/config/istio-private_jobs/proxy_1.8.yml
  prow/config/istio-private_jobs/proxy_1.9.yml
  prow/config/istio-private_jobs/release-builder_1.8.yml
  prow/config/istio-private_jobs/release-builder_1.9.yml
Labels: cla: yes, size/L

#3156 Use envoyproxy/envoy not envoyproxy/envoy-wasm repo for istio-private jobs
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/config/istio-private_jobs/proxy.yaml
Labels: cla: yes, size/XS

#3158 Bump 1.7 images
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.7.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.7.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.7.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.7.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.7.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.7.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.7.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.7.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.7.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.7.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.7.gen.yaml
  prow/config/jobs/api-1.7.yaml
  prow/config/jobs/client-go-1.7.yaml
  prow/config/jobs/common-files-1.7.yaml
  prow/config/jobs/gogo-genproto-1.7.yaml
  prow/config/jobs/istio-1.7.yaml
  prow/config/jobs/istio.io-1.7.yaml
  prow/config/jobs/pkg-1.7.yaml
  prow/config/jobs/proxy-1.7.yaml
  prow/config/jobs/release-builder-1.7.yaml
  prow/config/jobs/tools-1.7.yaml
Labels: cla: yes, size/S

#3160 Make istio envoy 1.7 tsan test optional.
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.release-1.7.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.7.gen.yaml
  prow/config/jobs/envoy-1.7.yaml
Labels: cla: yes, size/XS

#3163 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3164 Remove archived cri repo from common file updates
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/config/jobs/common-files.yaml
Labels: cla: yes, size/XS

#3162 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3161 Skip build Envoy filter example in istio/envoy
  go.sum
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.master.gen.yaml
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.release-1.8.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.7.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.8.gen.yaml
  prow/config/jobs/envoy-1.7.yaml
  prow/config/jobs/envoy-1.8.yaml
  prow/config/jobs/envoy.yaml
Labels: cla: yes, size/L

#3165 Correct env var to disable envoy filter example build.
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.master.gen.yaml
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.release-1.7.gen.yaml
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.release-1.8.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.7.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.8.gen.yaml
  prow/config/jobs/envoy-1.7.yaml
  prow/config/jobs/envoy-1.8.yaml
  prow/config/jobs/envoy.yaml
Labels: cla: yes, size/S
