Repository istio/test-infra, pull requests merged in 2021-05, with the labels that each got.

#3304 Update Prow to v20210502-ba10239e8c
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3310 temporary jobs for istiodless remotes
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/M

#3311 fix istiodless flag
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3312 Automator: update build-tools:release-1.9
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.9.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.9.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.9.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.9.gen.yaml
  prow/config/jobs/api-1.9.yaml
  prow/config/jobs/client-go-1.9.yaml
  prow/config/jobs/common-files-1.9.yaml
  prow/config/jobs/envoy-1.9.yaml
  prow/config/jobs/gogo-genproto-1.9.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.io-1.9.yaml
  prow/config/jobs/pkg-1.9.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/release-builder-1.9.yaml
  prow/config/jobs/tools-1.9.yaml
Labels: cla: yes, release-notes-none, size/M

#3314 Automator: update common-files@master in istio/test-infra@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3315 Update CNI test job to use CNI enablement flag.
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3316 Fixed istio repository name where new issues are created
  tools/automator/automator.sh
Labels: cla: yes, size/XS

#3318 Add netrc
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.9.gen.yaml
  prow/config/istio-private_jobs/release-builder_1.8.yml
  prow/config/istio-private_jobs/release-builder_1.9.yml
Labels: cla: yes, size/XS

#3319 More presets
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.8.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.9.gen.yaml
  prow/config/istio-private_jobs/release-builder_1.8.yml
  prow/config/istio-private_jobs/release-builder_1.9.yml
Labels: cla: yes, size/XS

#3321 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3323 Enable Google Analytics for prow.istio.io.
  prow/config.yaml
Labels: cla: yes, size/XS

#3320 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3317 Automator: update build-tools:release-1.10
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.10.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.10.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.10.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.10.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.10.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.10.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.10.gen.yaml
  prow/config/jobs/api-1.10.yaml
  prow/config/jobs/client-go-1.10.yaml
  prow/config/jobs/common-files-1.10.yaml
  prow/config/jobs/envoy-1.10.yaml
  prow/config/jobs/gogo-genproto-1.10.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio.io-1.10.yaml
  prow/config/jobs/pkg-1.10.yaml
  prow/config/jobs/proxy-1.10.yaml
  prow/config/jobs/release-builder-1.10.yaml
  prow/config/jobs/tools-1.10.yaml
Labels: cla: yes, release-notes-none, size/S

#3322 Automator: update build-tools:release-1.9
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.9.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.9.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.9.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.9.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.9.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.9.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.9.gen.yaml
  prow/config/jobs/api-1.9.yaml
  prow/config/jobs/client-go-1.9.yaml
  prow/config/jobs/common-files-1.9.yaml
  prow/config/jobs/envoy-1.9.yaml
  prow/config/jobs/gogo-genproto-1.9.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.io-1.9.yaml
  prow/config/jobs/pkg-1.9.yaml
  prow/config/jobs/proxy-1.9.yaml
  prow/config/jobs/release-builder-1.9.yaml
  prow/config/jobs/tools-1.9.yaml
Labels: cla: yes, release-notes-none, size/M

#3325 Make centos job required
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/config/jobs/proxy.yaml
Labels: cla: yes, size/XS

#3327 Release notes validation
  tools/check_release_notes.sh
Labels: cla: yes, size/M

#3328 Release notes validation
  tools/check_release_notes.sh
Labels: cla: yes, size/XS

#3209 Add istio/client-go, istio/pkg and istio/gogo-genproto to list of automator jobs
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/pkg.yaml
Labels: cla: yes, size/M

#3324 Update Prow to v20210515-9461f01d36
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3326 add schema validation
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/config/jobs/enhancements.yaml
  scripts/validate_schema.sh
  testgrid/config.yaml
Labels: cla: yes, size/L

#3329 Make enhancements job optional
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/config/jobs/enhancements.yaml
Labels: cla: yes, size/XS

#3331 Convert args to use equals instead of space
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/config/jobs/enhancements.yaml
Labels: cla: yes, size/XS

#3332 Fix arg
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/config/jobs/enhancements.yaml
Labels: cla: yes, size/XS

#3333 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3334 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3335 Istio prow: switch grafana password to be from external secret
  prow/cluster/kubernetes_external_secrets.yaml
  prow/cluster/monitoring/templates/grafana_secret.yaml
Labels: cla: yes, size/S

#3337 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3338 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3340 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3339 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3341 Revert to the exact image we had before
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, size/M

#3343 Isolate multicluster jobs
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#3330 Update Prow to v20210524-cf0aabdfa9
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: cla: yes, size/M

#3344 Add a periodic job to assist in measuring test stability
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
  testgrid/config.yaml
Labels: cla: yes, size/S

#3345 Update master istio.io automated job to use master istio repo.
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/config/jobs/istio.io.yaml
Labels: cla: yes, size/XS

#3347 Add periodic tests for dedicated n2 and e2 nodes
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/M

#3350 Update common-files and fix lint failure
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  prow/config/generate.go
Labels: cla: yes, size/XS

#3351 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3349 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3352 Skip release test
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/XS

#3353 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3355 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#3354 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3357 Disable go cache
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#3359 Pin IPv6 jobs to ubuntu nodes
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#3360 Revert "Disable go cache (#3357)"
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.yaml
Labels: cla: yes, size/S

#3361 Undo some changes to test regression
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.9.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.10.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.9.gen.yaml
  prow/config/jobs/istio-1.10.yaml
  prow/config/jobs/istio-1.9.yaml
  prow/config/jobs/istio.yaml
  testgrid/config.yaml
Labels: cla: yes, size/M

#3362 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3363 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M

#3364 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3365 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/envoy/istio.envoy.master.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/envoy.yaml
  prow/config/jobs/gogo-genproto.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: cla: yes, release-notes-none, size/M
