Repository istio/test-infra, pull requests merged in 2022-10, with the labels that each got.

#4311 Update Prow to v20221004-d1295ab2d7
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4313 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4312 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: size/M, release-notes-none

#4314 Automator: update build-tools:release-1.14
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.14.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.14.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.14.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.14.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.14.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.14.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.14.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.14.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.14.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.14.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.14.gen.yaml
  prow/config/jobs/api-1.14.yaml
  prow/config/jobs/client-go-1.14.yaml
  prow/config/jobs/common-files-1.14.yaml
  prow/config/jobs/enhancements-1.14.yaml
  prow/config/jobs/istio-1.14.yaml
  prow/config/jobs/istio.io-1.14.yaml
  prow/config/jobs/pkg-1.14.yaml
  prow/config/jobs/proxy-1.14.yaml
  prow/config/jobs/release-builder-1.14.yaml
  prow/config/jobs/tools-1.14.yaml
Labels: size/S, release-notes-none

#4316 Add istio/community to repos for updating after common-files change
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/config/jobs/common-files.yaml
Labels: size/XS

#4317 Automator: update build-tools:release-1.15
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.15.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.15.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.15.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.15.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.15.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.15.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.15.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.15.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.15.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.15.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.15.gen.yaml
  prow/config/jobs/api-1.15.yaml
  prow/config/jobs/client-go-1.15.yaml
  prow/config/jobs/common-files-1.15.yaml
  prow/config/jobs/enhancements-1.15.yaml
  prow/config/jobs/istio-1.15.yaml
  prow/config/jobs/istio.io-1.15.yaml
  prow/config/jobs/pkg-1.15.yaml
  prow/config/jobs/proxy-1.15.yaml
  prow/config/jobs/release-builder-1.15.yaml
  prow/config/jobs/tools-1.15.yaml
Labels: size/L, release-notes-none

#4318 Automator: update common-files@master in istio/test-infra@master
  LICENSE
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#4319 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4320 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: size/M, release-notes-none

#4321 Update Prow to v20221007-5eacea2e18
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4323 Update Prow to v20221010-dd25d02461
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4324 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#4325 Update Prow to v20221011-5d4db25b24
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4322 prow: protect experimental branch
  prow/config.yaml
Labels: size/XS

#4326 Disable release notes test in experimental-* branches
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/config/experimental/istio.yaml
Labels: size/XS

#4327 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#4328 A change in istio/tools pkg directory should cause new container build
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/tools.yaml
Labels: size/XS

#4330 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#4332 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4329 Update Prow to v20221014-f54c8765a7
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4331 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: size/M, release-notes-none

#4334 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4335 Update Prow to v20221016-ee0e1638a8
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4333 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: size/M, release-notes-none

#4337 Update Prow to v20221018-1a130015da
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4340 Update regex to also find sha and not just date for build images
  tools/prowgen/cmd/prowgen/main.go
Labels: size/XS

#4339 Generate Prow jobs for Istio 1.16
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.16.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.16.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.16.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.16.gen.yaml
  prow/config/istio-private_jobs/api-1.16.yaml
  prow/config/istio-private_jobs/envoy-1.16.yaml
  prow/config/istio-private_jobs/istio-1.16.yaml
  prow/config/istio-private_jobs/istio.io-1.16.yaml
  prow/config/istio-private_jobs/proxy-1.16.yaml
  prow/config/istio-private_jobs/release-builder-1.16.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/client-go-1.16.yaml
  prow/config/jobs/common-files-1.16.yaml
  prow/config/jobs/enhancements-1.16.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio.io-1.16.yaml
  prow/config/jobs/pkg-1.16.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/release-builder-1.16.yaml
  prow/config/jobs/tools-1.16.yaml
  testgrid/config.yaml
Labels: size/XXL

#4338 Disable the Grafana login form.
  prow/cluster/monitoring/grafana_configmaps.yaml
Labels: size/XS

#4341 Update Prow to v20221019-ad25b9b7d1
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4342 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/XS, auto-merge, release-notes-none

#4345 set envoy update branch
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/config/jobs/proxy-1.16.yaml
Labels: size/XS

#4347 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#4346 Update Prow to v20221020-bb135cb447
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4348 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4349 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: size/M, release-notes-none

#4344 Automator: update build-tools:release-1.16
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.16.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.16.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.16.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.16.gen.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/client-go-1.16.yaml
  prow/config/jobs/common-files-1.16.yaml
  prow/config/jobs/enhancements-1.16.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio.io-1.16.yaml
  prow/config/jobs/pkg-1.16.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/release-builder-1.16.yaml
  prow/config/jobs/tools-1.16.yaml
Labels: size/L, release-notes-none

#4350 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: size/XS, auto-merge, release-notes-none

#4336 Add branch protection for 1.16
  prow/config.yaml
Labels: size/XS

#4343 Add CI/CD support for ztunnel
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/ztunnel.yaml
  testgrid/config.yaml
Labels: size/S

#4353 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4352 ztunnel: cache dependency download
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/.base.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/S

#4354 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4351 Update Prow to v20221021-f6c02074bb
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4355 Add release job for ztunnel
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/XS

#4358 Update Prow to v20221024-d0c013ee2d
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4359 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4361 ambient tests
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/config/jobs/istio-ambient.yaml
  testgrid/config.yaml
Labels: size/S

#4363 Update Prow to v20221026-709aedbbfe
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4356 testgrid: dashboards must belong to dashboard groups
  go.mod
  go.sum
  licenses/bitbucket.org/creachadair/stringset/LICENSE
  testgrid/config.yaml
  testgrid/config_test.go
Labels: ok-to-test, size/L

#4362 Automator: update build-tools:release-1.16
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.16.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.16.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.16.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.16.gen.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/client-go-1.16.yaml
  prow/config/jobs/common-files-1.16.yaml
  prow/config/jobs/enhancements-1.16.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio.io-1.16.yaml
  prow/config/jobs/pkg-1.16.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/release-builder-1.16.yaml
  prow/config/jobs/tools-1.16.yaml
Labels: size/L, release-notes-none

#4364 Update Prow to v20221027-c0f9edbb5d
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4365 Update Prow to v20221028-a8625c1f93
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge
