Repository istio/test-infra, pull requests merged in 2022-11, with the labels that each got.

#4366 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4367 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4371 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4370 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4373 Rotate test-infra-trusted build cluster kubeconfig
  prow/cluster/gencred-config/gencred-config.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/prowjob_service_accounts.yaml
Labels: size/M

#4372 Update Prow to v20221102-8efc754883
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4374 Sync test-infra-trusted build cluster kubeconfig from GSM to prow
  prow/cluster/kubernetes_external_secrets.yaml
Labels: size/S

#4375 Prow deployments switch from kubeconfig flag to env var
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
Labels: size/S

#4377 Test-infra-trusted build cluster kubeconfig secret should be in defau…
  prow/cluster/kubernetes_external_secrets.yaml
Labels: size/XS

#4376 Add new test-infra-trusted build cluster kubeconfig to prow deployments
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
Labels: size/M

#4368 Automator: update build-tools:release-1.16
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.16.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.16.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.16.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.16.gen.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/client-go-1.16.yaml
  prow/config/jobs/common-files-1.16.yaml
  prow/config/jobs/enhancements-1.16.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio.io-1.16.yaml
  prow/config/jobs/pkg-1.16.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/release-builder-1.16.yaml
  prow/config/jobs/tools-1.16.yaml
Labels: size/L, release-notes-none

#4369 Automator: update build-tools:release-1.15
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.15.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.15.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.15.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.15.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.15.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.15.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.15.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.15.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.15.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.15.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.15.gen.yaml
  prow/config/jobs/api-1.15.yaml
  prow/config/jobs/client-go-1.15.yaml
  prow/config/jobs/common-files-1.15.yaml
  prow/config/jobs/enhancements-1.15.yaml
  prow/config/jobs/istio-1.15.yaml
  prow/config/jobs/istio.io-1.15.yaml
  prow/config/jobs/pkg-1.15.yaml
  prow/config/jobs/proxy-1.15.yaml
  prow/config/jobs/release-builder-1.15.yaml
  prow/config/jobs/tools-1.15.yaml
Labels: size/L, release-notes-none

#4381 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4380 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4382 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4378 Automator: update build-tools:release-1.14
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.14.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.14.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.14.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.14.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.14.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.14.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.14.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.14.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.14.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.14.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.14.gen.yaml
  prow/config/jobs/api-1.14.yaml
  prow/config/jobs/client-go-1.14.yaml
  prow/config/jobs/common-files-1.14.yaml
  prow/config/jobs/enhancements-1.14.yaml
  prow/config/jobs/istio-1.14.yaml
  prow/config/jobs/istio.io-1.14.yaml
  prow/config/jobs/pkg-1.14.yaml
  prow/config/jobs/proxy-1.14.yaml
  prow/config/jobs/release-builder-1.14.yaml
  prow/config/jobs/tools-1.14.yaml
Labels: size/S, release-notes-none

#4379 Update Prow to v20221103-4bdeafeef2
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4357 Add new cron job for updating envoyproxy/go-control-plane
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: size/S

#4383 Update Prow to v20221104-4497ace285
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4384 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4385 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4386 Revert "Automator: update build-tools:master"
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M

#4388 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4387 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4389 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4390 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4391 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4393 Automator: update build-tools:release-1.16
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.16.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.16.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.16.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.16.gen.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/client-go-1.16.yaml
  prow/config/jobs/common-files-1.16.yaml
  prow/config/jobs/enhancements-1.16.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio.io-1.16.yaml
  prow/config/jobs/pkg-1.16.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/release-builder-1.16.yaml
  prow/config/jobs/tools-1.16.yaml
Labels: size/L, release-notes-none

#4395 Update Prow to v20221108-d3ce231cb9
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4397 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#4398 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4396 Update Prow to v20221109-1955b5822e
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4394 Remove the 1.13 periodic jobs
  prow/cluster/jobs/istio/istio/istio.istio.release-1.13.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.13.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.13.gen.yaml
  prow/config/jobs/istio-1.13.yaml
  prow/config/jobs/proxy-1.13.yaml
  prow/config/jobs/release-builder-1.13.yaml
  testgrid/config.yaml
Labels: size/L

#4399 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4400 Update Prow to v20221110-d224b81b1a
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4402 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4401 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4403 Update Prow to v20221111-fe4f3e2158
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4404 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#4406 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4407 Add a k8s 1.26 istio integ test job
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: size/S

#4408 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#4411 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4410 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4412 Update Prow to v20221115-a6c6c84e3d
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4413 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#4415 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4414 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4409 Fix cargo mount
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/.base.yaml
Labels: size/XS

#4416 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/fix_copyright_banner.sh
Labels: size/XS, auto-merge, release-notes-none

#4417 Update Prow to v20221117-c31c738d0c
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4418 Update Prow to v20221117-3815e13b72
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4419 Update Prow to v20221121-dfec9ce18d
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4421 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4424 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4423 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none
