Repository istio/test-infra, pull requests merged in 2022-07, with the labels that each got.

#4147 Update the istio/community sync job timeout. It sometimes exceeds 2 hrs.
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/config/jobs/community.yaml
Labels: size/XS

#4146 Update Prow to v20220630-695df9040a
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4148 Update Prow to v20220704-55148688b2
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4149 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4142 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: size/M, release-notes-none

#4150 Update Prow to v20220705-20e880da9b
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4151 Update Prow to v20220707-726e618341
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4152 Update Prow to v20220707-6c9b2eb5c9
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4153 Update Prow to v20220711-fb03943056
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4155 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#4156 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#4157 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4154 Update Prow to v20220712-d94683d4de
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4082 Add experimental ds branch ci/cd
  Makefile.core.mk
  prow/cluster/jobs/istio/istio/istio.istio.experimental-dual-stack.gen.yaml
  prow/config/experimental/.defaults.yaml
  prow/config/experimental/istio.yaml
  tools/prowtrans/cmd/prowtrans/main.go
Labels: size/M

#4159 Automator: update build-tools:release-1.14
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.14.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.14.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.14.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.14.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.14.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.14.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.14.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.14.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.14.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.14.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.14.gen.yaml
  prow/config/jobs/api-1.14.yaml
  prow/config/jobs/client-go-1.14.yaml
  prow/config/jobs/common-files-1.14.yaml
  prow/config/jobs/enhancements-1.14.yaml
  prow/config/jobs/istio-1.14.yaml
  prow/config/jobs/istio.io-1.14.yaml
  prow/config/jobs/pkg-1.14.yaml
  prow/config/jobs/proxy-1.14.yaml
  prow/config/jobs/release-builder-1.14.yaml
  prow/config/jobs/tools-1.14.yaml
Labels: size/S, release-notes-none

#4158 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-dual-stack.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: size/M, release-notes-none

#4160 Update Prow to v20220713-b07b206195
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4162 Support cluster-per-arch
  Makefile.core.mk
  prow/config/jobs/.base.yaml
  tools/prowgen/pkg/decorator/variable.go
  tools/prowgen/pkg/generate.go
  tools/prowgen/pkg/spec/spec.go
  tools/prowgen/pkg/testdata/.base.yaml
  tools/prowgen/pkg/testdata/simple.gen.yaml
Labels: size/S

#4163 Automator: update build-tools:release-1.14
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.14.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.14.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.14.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.14.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.14.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.14.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.14.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.14.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.14.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.14.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.14.gen.yaml
  prow/config/jobs/api-1.14.yaml
  prow/config/jobs/client-go-1.14.yaml
  prow/config/jobs/common-files-1.14.yaml
  prow/config/jobs/enhancements-1.14.yaml
  prow/config/jobs/istio-1.14.yaml
  prow/config/jobs/istio.io-1.14.yaml
  prow/config/jobs/pkg-1.14.yaml
  prow/config/jobs/proxy-1.14.yaml
  prow/config/jobs/release-builder-1.14.yaml
  prow/config/jobs/tools-1.14.yaml
Labels: size/S, release-notes-none

#4165 Normalize config names
  tools/prowtrans/cmd/prowtrans/main.go
  tools/prowtrans/pkg/util/strings.go
Labels: size/XS

#4164 Update Prow to v20220715-5578b93739
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4166 Update Prow to v20220718-1211ccbc68
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4168 Update failing job definition
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.13.gen.yaml
  prow/config/jobs/common-files-1.13.yaml
Labels: size/XS

#4167 Manual build-tools image update for 1.13 jobs
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.13.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.13.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.13.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.13.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.13.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.13.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.13.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.13.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.13.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.13.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.13.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.13.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.13.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.13.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.13.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.13.gen.yaml
  prow/config/jobs/api-1.13.yaml
  prow/config/jobs/client-go-1.13.yaml
  prow/config/jobs/common-files-1.13.yaml
  prow/config/jobs/enhancements-1.13.yaml
  prow/config/jobs/gogo-genproto-1.13.yaml
  prow/config/jobs/istio-1.13.yaml
  prow/config/jobs/istio.io-1.13.yaml
  prow/config/jobs/pkg-1.13.yaml
  prow/config/jobs/proxy-1.13.yaml
  prow/config/jobs/release-builder-1.13.yaml
  prow/config/jobs/tools-1.13.yaml
Labels: size/M

#4170 Remove the 1.12 periodic jobs as it's EOL.
  prow/cluster/jobs/istio/istio/istio.istio.release-1.12.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.12.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.12.gen.yaml
  prow/config/jobs/istio-1.12.yaml
  prow/config/jobs/proxy-1.12.yaml
  prow/config/jobs/release-builder-1.12.yaml
  testgrid/config.yaml
Labels: size/M

#4172 Revert "Update Prow to v20220719-c85a2ec6dc"
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M

#4171 Update Prow to v20220720-42160bd9d6
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4175 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#4174 Automator: update build-tools:release-1.14
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.14.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.14.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.14.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.14.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.14.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.14.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.14.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.14.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.14.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.14.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.14.gen.yaml
  prow/config/jobs/api-1.14.yaml
  prow/config/jobs/client-go-1.14.yaml
  prow/config/jobs/common-files-1.14.yaml
  prow/config/jobs/enhancements-1.14.yaml
  prow/config/jobs/istio-1.14.yaml
  prow/config/jobs/istio.io-1.14.yaml
  prow/config/jobs/pkg-1.14.yaml
  prow/config/jobs/proxy-1.14.yaml
  prow/config/jobs/release-builder-1.14.yaml
  prow/config/jobs/tools-1.14.yaml
Labels: size/S, release-notes-none

#4179 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4178 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-dual-stack.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: size/M, release-notes-none

#4181 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/S, auto-merge, release-notes-none

#4176 Automator: update build-tools:release-1.13
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.13.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.13.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.13.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.13.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.13.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.13.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.13.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.13.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.13.gen.yaml
  prow/cluster/jobs/istio/gogo-genproto/istio.gogo-genproto.release-1.13.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.13.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.13.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.13.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.13.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.13.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.13.gen.yaml
  prow/config/jobs/api-1.13.yaml
  prow/config/jobs/client-go-1.13.yaml
  prow/config/jobs/common-files-1.13.yaml
  prow/config/jobs/enhancements-1.13.yaml
  prow/config/jobs/gogo-genproto-1.13.yaml
  prow/config/jobs/istio-1.13.yaml
  prow/config/jobs/istio.io-1.13.yaml
  prow/config/jobs/pkg-1.13.yaml
  prow/config/jobs/proxy-1.13.yaml
  prow/config/jobs/release-builder-1.13.yaml
  prow/config/jobs/tools-1.13.yaml
Labels: size/M, release-notes-none

#4182 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4183 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-dual-stack.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: size/M, release-notes-none

#4184 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4186 Automator: update build-tools:release-1.14
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.14.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.14.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.14.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.14.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.14.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.14.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.14.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.14.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.14.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.14.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.14.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.14.gen.yaml
  prow/config/jobs/api-1.14.yaml
  prow/config/jobs/client-go-1.14.yaml
  prow/config/jobs/common-files-1.14.yaml
  prow/config/jobs/enhancements-1.14.yaml
  prow/config/jobs/istio-1.14.yaml
  prow/config/jobs/istio.io-1.14.yaml
  prow/config/jobs/pkg-1.14.yaml
  prow/config/jobs/proxy-1.14.yaml
  prow/config/jobs/release-builder-1.14.yaml
  prow/config/jobs/tools-1.14.yaml
Labels: size/S, release-notes-none

#4185 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-dual-stack.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: size/M, release-notes-none

#4188 Arm build cluster
  prow/Makefile
  prow/cluster/arm/kubernetes-external-secrets_crd.yaml
  prow/cluster/arm/kubernetes-external-secrets_deployment.yaml
  prow/cluster/arm/kubernetes-external-secrets_rbac.yaml
  prow/cluster/arm/kubernetes-external-secrets_service.yaml
  prow/cluster/arm/kubernetes_external_secrets.yaml
  prow/cluster/arm/prowjob_service_accounts.yaml
  prow/cluster/arm/test_pod_namespace.yaml
  prow/cluster/arm/tune-sysctls_daemonset.yaml
  prow/config.yaml
Labels: size/L

#4187 arm64: add initial build-tools job with bootstap image
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/.base.yaml
  prow/config/jobs/tools.yaml
Labels: size/M

#4191 arm64: add tolerations to jobs
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  tools/prowgen/pkg/generate.go
  tools/prowgen/pkg/testdata/simple.gen.yaml
Labels: size/S

#4192 Drop github requirement for arm64 postsubmit
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/tools.yaml
Labels: size/XS

#4194 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-dual-stack.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: size/M, release-notes-none

#4195 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4190 proxy: add arm64 jobs
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/config/jobs/proxy.yaml
Labels: size/S

#4193 arm64: drop bootstrap image
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/tools.yaml
Labels: size/XS

#4197 proxy: fix arm builds
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/config/jobs/proxy.yaml
Labels: size/S

#4198 Fix minor issue on arm64 proxy builds
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/config/jobs/proxy.yaml
Labels: size/XS
