Repository istio/test-infra, pull requests merged in 2023-06, with the labels that each got.

#4738 Update Prow to v20230601-43eb1068e4
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4741 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4744 Remove `release-` from 1.18 Base image name to match others
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.18.gen.yaml
  prow/config/jobs/release-builder-1.18.yaml
Labels: size/XS

#4743 Update Prow to v20230605-4109cab408
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4745 Update Prow to v20230605-b63f6f76cb
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4746 Automator: update build-tools:release-1.18
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.18.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.18.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.18.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.18.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.18.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.18.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.18.gen.yaml
  prow/config/jobs/api-1.18.yaml
  prow/config/jobs/client-go-1.18.yaml
  prow/config/jobs/common-files-1.18.yaml
  prow/config/jobs/enhancements-1.18.yaml
  prow/config/jobs/istio-1.18.yaml
  prow/config/jobs/istio.io-1.18.yaml
  prow/config/jobs/pkg-1.18.yaml
  prow/config/jobs/proxy-1.18.yaml
  prow/config/jobs/release-builder-1.18.yaml
  prow/config/jobs/tools-1.18.yaml
  prow/config/jobs/ztunnel-1.18.yaml
Labels: size/M, release-notes-none

#4747 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#4748 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4749 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#4750 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#4752 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4754 Bump go dependencies
  go.mod
  go.sum
  licenses/cloud.google.com/go/compute/metadata/LICENSE
  licenses/github.com/PuerkitoBio/purell/LICENSE
  licenses/github.com/andygrunwald/go-gerrit/LICENSE
  licenses/github.com/emicklei/go-restful/v3/LICENSE
  licenses/github.com/googleapis/enterprise-certificate-proxy/LICENSE
  licenses/github.com/grpc-ecosystem/grpc-gateway/v2/LICENSE.txt
  licenses/github.com/grpc-ecosystem/grpc-gateway/v2/internal/casing/LICENSE.md
  licenses/github.com/opencontainers/go-digest/LICENSE
  licenses/github.com/satori/go.uuid/LICENSE
  licenses/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/LICENSE
Labels: size/L, release-notes-none

#4756 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#4755 Add initial terraform infrastructure
  infra/README.md
  infra/gcp/.gitignore
  infra/gcp/istio-prow-build/cluster-prow-arm.tf
  infra/gcp/istio-prow-build/cluster-prow.tf
  infra/gcp/istio-prow-build/iam.tf
  infra/gcp/istio-prow-build/keys.tf
  infra/gcp/istio-prow-build/main.tf
  infra/gcp/istio-prow-build/providers.tf
  infra/gcp/istio-prow-build/services.tf
  infra/gcp/istio-prow-build/storage.tf
Labels: size/XL

#4760 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#4736 Automator: update build-tools:release-1.16
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.16.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.16.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.16.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.16.gen.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/client-go-1.16.yaml
  prow/config/jobs/common-files-1.16.yaml
  prow/config/jobs/enhancements-1.16.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio.io-1.16.yaml
  prow/config/jobs/pkg-1.16.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/release-builder-1.16.yaml
  prow/config/jobs/tools-1.16.yaml
Labels: size/L, release-notes-none

#4757 Update Prow to v20230613-9df263832f
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4761 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#4762 Complete terraform backfill
  infra/README.md
  infra/gcp/istio-io/dns.tf
  infra/gcp/istio-io/main.tf
  infra/gcp/istio-io/providers.tf
  infra/gcp/istio-io/storage.tf
  infra/gcp/istio-prerelease-testing/main.tf
  infra/gcp/istio-prerelease-testing/providers.tf
  infra/gcp/istio-prerelease-testing/storage.tf
  infra/gcp/istio-release/main.tf
  infra/gcp/istio-release/providers.tf
  infra/gcp/istio-release/storage.tf
  infra/gcp/istio-testing/cluster-policy-bot.tf
  infra/gcp/istio-testing/cluster-prow.tf
  infra/gcp/istio-testing/elekto.tf
  infra/gcp/istio-testing/iam.tf
  infra/gcp/istio-testing/keys.tf
  infra/gcp/istio-testing/main.tf
  infra/gcp/istio-testing/providers.tf
  infra/gcp/istio-testing/services.tf
  infra/gcp/istio-testing/spanner.tf
  infra/gcp/istio-testing/storage.tf
Labels: size/XL

#4763 jobs: deny usage of underscore in name
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.16.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.17.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.16.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.17.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.18.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/istio-private_jobs/api.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/api-1.17.yaml
  prow/config/jobs/api-1.18.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/client-go-1.16.yaml
  prow/config/jobs/client-go-1.17.yaml
  prow/config/jobs/client-go-1.18.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/istio.io-1.16.yaml
  prow/config/jobs/istio.io-1.17.yaml
  prow/config/jobs/istio.io-1.18.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/pkg-1.16.yaml
  prow/config/jobs/pkg-1.17.yaml
  prow/config/jobs/pkg-1.18.yaml
  prow/config/jobs/tools.yaml
  tools/prowgen/pkg/generate.go
Labels: size/L, release-notes-none

#4768 Drop benchmark check job, which is obsolete
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/tools.yaml
Labels: size/S, release-notes-none

#4767 Add jobs validating job specs
  go.mod
  go.sum
  licenses/golang.org/x/exp/LICENSE
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/config/jobs_test.go
Labels: size/XL

#4765 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4770 add ARM unit tests
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/config/jobs/proxy.yaml
Labels: size/S

#4769 Terraform: better document GCS buckets and cleanup empty ones
  infra/README.md
  infra/gcp/istio-testing/storage.tf
Labels: size/L, release-notes-none

#4771 make test-arm optional
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/config/jobs/proxy.yaml
Labels: size/XS

#4773 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4772 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4775 Remove perf dashboardf deployer
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.16.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.17.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.18.gen.yaml
  prow/config/jobs/tools-1.16.yaml
  prow/config/jobs/tools-1.17.yaml
  prow/config/jobs/tools-1.18.yaml
  prow/config/jobs/tools.yaml
Labels: size/L

#4776 Revert "make test-arm optional"
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/config/jobs/proxy.yaml
Labels: size/XS

#4779 Automator: update build-tools:release-1.18
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.18.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.18.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.18.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.18.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.18.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.18.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.18.gen.yaml
  prow/config/jobs/api-1.18.yaml
  prow/config/jobs/client-go-1.18.yaml
  prow/config/jobs/common-files-1.18.yaml
  prow/config/jobs/enhancements-1.18.yaml
  prow/config/jobs/istio-1.18.yaml
  prow/config/jobs/istio.io-1.18.yaml
  prow/config/jobs/pkg-1.18.yaml
  prow/config/jobs/proxy-1.18.yaml
  prow/config/jobs/release-builder-1.18.yaml
  prow/config/jobs/tools-1.18.yaml
  prow/config/jobs/ztunnel-1.18.yaml
Labels: size/M, release-notes-none

#4778 Automator: update build-tools:release-1.16
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.16.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.16.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.16.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.16.gen.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/client-go-1.16.yaml
  prow/config/jobs/common-files-1.16.yaml
  prow/config/jobs/enhancements-1.16.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio.io-1.16.yaml
  prow/config/jobs/pkg-1.16.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/release-builder-1.16.yaml
  prow/config/jobs/tools-1.16.yaml
Labels: size/L, release-notes-none

#4781 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#4783 prow: add highlighter config
  prow/config.yaml
Labels: size/XS, release-notes-none

#4785 Update Prow to v20230621-2a6a094857
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4753 Automator: update build-tools:release-1.17
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.17.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.17.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.17.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.17.gen.yaml
  prow/config/jobs/api-1.17.yaml
  prow/config/jobs/client-go-1.17.yaml
  prow/config/jobs/common-files-1.17.yaml
  prow/config/jobs/enhancements-1.17.yaml
  prow/config/jobs/istio-1.17.yaml
  prow/config/jobs/istio.io-1.17.yaml
  prow/config/jobs/pkg-1.17.yaml
  prow/config/jobs/proxy-1.17.yaml
  prow/config/jobs/release-builder-1.17.yaml
  prow/config/jobs/tools-1.17.yaml
Labels: size/L, release-notes-none

#4786 terraform: Cleanup removed buckets
  infra/gcp/istio-io/storage.tf
  infra/gcp/istio-prow-build/cluster-prow-arm-private.tf
  infra/gcp/istio-prow-build/cluster-prow-arm.tf
  infra/gcp/istio-prow-build/cluster-prow-private.tf
  infra/gcp/istio-prow-build/cluster-prow.tf
  infra/gcp/istio-prow-build/iam.tf
  infra/gcp/istio-prow-build/main.tf
  infra/gcp/istio-prow-build/storage.tf
Labels: size/L

#4784 Setup job configuration to allow reading GCP secrets directly
  prow/config/jobs_test.go
  tools/prowgen/pkg/decorator/requirement.go
  tools/prowgen/pkg/spec/spec.go
  tools/prowgen/pkg/testdata/.base.yaml
  tools/prowgen/pkg/testdata/simple.gen.yaml
  tools/prowgen/pkg/testdata/simple.yaml
Labels: size/M, release-notes-none

#4789 Remove policybot secret
  prow/cluster/build/kubernetes_external_secrets.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/config/jobs/bots.yaml
Labels: size/M

#4782 prow: migrate from gencred to gke-gcloud-auth-plugin/WI
  infra/gcp/istio-testing/iam.tf
  prow/cluster/build_kubeconfig.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/gencred-config/gencred-config.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/kubernetes_external_secrets.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/prowjob_service_accounts.yaml
  prow/cluster/sinker_deployment.yaml
  prow/config/jobs_test.go
Labels: size/L

#4793 Fix crier deployment kubeconfig reference
  prow/cluster/crier_deployment.yaml
Labels: size/XS

#4792 Remove obsolete variable from prow jobs
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.18.gen.yaml
  prow/config/istio-private_jobs/proxy-1.16.yaml
  prow/config/istio-private_jobs/proxy-1.17.yaml
  prow/config/istio-private_jobs/proxy-1.18.yaml
  prow/config/istio-private_jobs/proxy.yaml
Labels: size/XS, release-notes-none

#4787 terraform: add initial scoped service accounts
  infra/gcp/istio-prow-build/iam.tf
  infra/gcp/istio-prow-build/secrets.tf
  infra/gcp/modules/workload-identity-service-account/README.md
  infra/gcp/modules/workload-identity-service-account/main.tf
  infra/gcp/modules/workload-identity-service-account/outputs.tf
  infra/gcp/modules/workload-identity-service-account/variables.tf
  infra/gcp/modules/workload-identity-service-account/versions.tf
  prow/cluster/build/prowjob_service_accounts.yaml
Labels: size/L

#4799 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4797 terraform: fix new WI SAs to have write access to prow logs
  infra/gcp/istio-prow-build/iam.tf
  infra/gcp/modules/workload-identity-service-account/main.tf
  infra/gcp/modules/workload-identity-service-account/variables.tf
Labels: size/S, release-notes-none

#4800 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4803 jobs: drop privileges in tools presubmit test
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.16.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.17.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.18.gen.yaml
  prow/config/jobs/tools-1.16.yaml
  prow/config/jobs/tools-1.17.yaml
  prow/config/jobs/tools-1.18.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs_test.go
Labels: size/S, release-notes-none

#4801 jobs: cleanup release-test config on old branches
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.18.gen.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio-1.17.yaml
  prow/config/jobs/istio-1.18.yaml
  prow/config/jobs_test.go
Labels: size/XS, release-notes-none

#4796 Migrate proxy jobs over to RBE sa
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/proxy-1.17.yaml
  prow/config/jobs/proxy-1.18.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs_test.go
Labels: size/L

#4804 jobs: drop github token on ref-docs-dry-run
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.18.gen.yaml
  prow/config/jobs/istio.io-1.16.yaml
  prow/config/jobs/istio.io-1.17.yaml
  prow/config/jobs/istio.io-1.18.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs_test.go
Labels: size/S, release-notes-none

#4788 Remove cosign 'secret'
  prow/cluster/build/kubernetes_external_secrets.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.18.gen.yaml
  prow/cluster/private/kubernetes_external_secrets.yaml
  prow/config/jobs/.base.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/api-1.17.yaml
  prow/config/jobs/api-1.18.yaml
  prow/config/jobs/client-go-1.16.yaml
  prow/config/jobs/client-go-1.17.yaml
  prow/config/jobs/client-go-1.18.yaml
  prow/config/jobs/common-files-1.16.yaml
  prow/config/jobs/common-files-1.17.yaml
  prow/config/jobs/common-files-1.18.yaml
  prow/config/jobs/enhancements-1.16.yaml
  prow/config/jobs/enhancements-1.17.yaml
  prow/config/jobs/enhancements-1.18.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio-1.17.yaml
  prow/config/jobs/istio-1.18.yaml
  prow/config/jobs/istio.io-1.16.yaml
  prow/config/jobs/istio.io-1.17.yaml
  prow/config/jobs/istio.io-1.18.yaml
  prow/config/jobs/pkg-1.16.yaml
  prow/config/jobs/pkg-1.17.yaml
  prow/config/jobs/pkg-1.18.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/proxy-1.17.yaml
  prow/config/jobs/proxy-1.18.yaml
  prow/config/jobs/release-builder-1.16.yaml
  prow/config/jobs/release-builder-1.17.yaml
  prow/config/jobs/release-builder-1.18.yaml
  prow/config/jobs/tools-1.16.yaml
  prow/config/jobs/tools-1.17.yaml
  prow/config/jobs/tools-1.18.yaml
  prow/config/jobs/ztunnel-1.18.yaml
Labels: size/XXL, release-notes-none

#4806 Copy SA from build cluster to ARM as well
  prow/cluster/arm/prowjob_service_accounts.yaml
Labels: size/S, release-notes-none

#4807 Fix postsubmit to deploy ARM as well
  prow/cluster/arm/prowjob_service_accounts.yaml
  prow/cluster/build/prowjob_service_accounts.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
Labels: size/XS, release-notes-none

#4808 terraform: Add readonly github account and initial secrets
  infra/gcp/istio-prow-build/iam.tf
  infra/gcp/istio-prow-build/secrets.tf
Labels: size/M, release-notes-none

#4802 Update Prow to v20230623-ea9b5f8eba
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4798 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4811 jobs: fix proxy postsubmit
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/proxy-1.17.yaml
  prow/config/jobs/proxy-1.18.yaml
  prow/config/jobs/proxy.yaml
Labels: size/S, release-notes-none

#4805 jobs: drop permissions on release-builder
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.18.gen.yaml
  prow/config/jobs/release-builder-1.16.yaml
  prow/config/jobs/release-builder-1.17.yaml
  prow/config/jobs/release-builder-1.18.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs_test.go
Labels: size/XS, release-notes-none

#4810 Fix some incorrect job tests
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs_test.go
Labels: size/M, release-notes-none

#4809 Move release-notes job to fine scoped github token
  infra/gcp/istio-prow-build/secrets.tf
  prow/cluster/build/prowjob_service_accounts.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.18.gen.yaml
  prow/config/jobs/.base.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/api-1.17.yaml
  prow/config/jobs/api-1.18.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio-1.17.yaml
  prow/config/jobs/istio-1.18.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs_test.go
Labels: size/M

#4814 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4812 Move to revamped release notes tool
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.18.gen.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/api-1.17.yaml
  prow/config/jobs/api-1.18.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio-1.17.yaml
  prow/config/jobs/istio-1.18.yaml
  prow/config/jobs/istio.yaml
Labels: size/M

#4813 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4815 Fix release notes job
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.18.gen.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/api-1.17.yaml
  prow/config/jobs/api-1.18.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio-1.17.yaml
  prow/config/jobs/istio-1.18.yaml
  prow/config/jobs/istio.yaml
Labels: size/M, release-notes-none

#4794 prow: remove authentikos
  prow/cluster/private-arm/authentikos_deployment.yaml
  prow/cluster/private-arm/authentikos_rbac.yaml
  prow/cluster/private/authentikos_deployment.yaml
  prow/cluster/private/authentikos_rbac.yaml
Labels: size/L

#4817 Drop obsolete release notes script
  tools/check_release_notes.sh
Labels: size/L, release-notes-none

#4777 Benchmark Ztunnel Command
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/ztunnel.yaml
Labels: ok-to-test, size/XS

#4795 terraform: initial GKE modules
  infra/gcp/istio-prow-build/cluster-prow.tf
  infra/gcp/istio-testing/cluster-policy-bot.tf
  infra/gcp/istio-testing/iam.tf
  infra/gcp/modules/gke-cluster/README.md
  infra/gcp/modules/gke-cluster/main.tf
  infra/gcp/modules/gke-cluster/outputs.tf
  infra/gcp/modules/gke-cluster/variables.tf
  infra/gcp/modules/gke-cluster/versions.tf
  infra/gcp/modules/gke-nodepool/README.md
  infra/gcp/modules/gke-nodepool/main.tf
  infra/gcp/modules/gke-nodepool/variables.tf
  infra/gcp/modules/gke-nodepool/versions.tf
Labels: size/XL, size/L, release-notes-none

#4790 prow: move deck-private to use WI
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/deck_private_rbac.yaml
Labels: size/XS

#4819 Ztunnel benches only run on demand
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/ztunnel.yaml
Labels: ok-to-test, size/XS

#4820 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4822 Remove legacy `pkg` jobs
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/config/jobs/pkg.yaml
  testgrid/config.yaml
Labels: size/S, release-notes-none

#4818 terraform: Flesh out prowjob-release complete IAM
  infra/gcp/istio-prow-build/iam.tf
  infra/gcp/istio-prow-build/keys.tf
  infra/gcp/istio-prow-build/storage.tf
  infra/gcp/modules/workload-identity-service-account/main.tf
  infra/gcp/modules/workload-identity-service-account/variables.tf
Labels: size/M

#4825 Fix deck private deployment
  prow/cluster/deck_private_deployment.yaml
Labels: size/XS, release-notes-none

#4824 terraform: a few minor fixups
  infra/gcp/istio-prow-build/iam.tf
  infra/gcp/modules/workload-identity-service-account/main.tf
  prow/cluster/build/prowjob_service_accounts.yaml
Labels: size/S, release-notes-none

#4826 Remove obsolete ambient branch
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/config/jobs/istio-ambient.yaml
  testgrid/config.yaml
Labels: size/S, release-notes-none

#4827 Move release builder over to new secret management scheme
  infra/gcp/istio-prow-build/iam.tf
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/jobs/.base.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs_test.go
Labels: size/M, release-notes-none

#4828 Benchmarking Ztunnel is a presubmit job
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/XS

#4832 automator: fix arg parsing
  tools/automator/automator.sh
Labels: size/XS, release-notes-none

#4821 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4836 jobs: fix containers build
  infra/gcp/istio-prow-build/iam.tf
  prow/cluster/build/prowjob_service_accounts.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.16.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.17.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.18.gen.yaml
  prow/config/jobs/tools-1.16.yaml
  prow/config/jobs/tools-1.17.yaml
  prow/config/jobs/tools-1.18.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs_test.go
Labels: size/M, release-notes-none

#4837 arm cluster needs build-tools service account
  prow/cluster/arm/prowjob_service_accounts.yaml
Labels: size/XS, release-notes-none

#4841 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4831 Move build-base to explicit script
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/release-builder.yaml
Labels: size/S, release-notes-none

#4838 private: remove automator jobs which we don't have permission for
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.18.gen.yaml
  prow/config/istio-private_jobs/api-1.16.yaml
  prow/config/istio-private_jobs/api-1.17.yaml
  prow/config/istio-private_jobs/api-1.18.yaml
  prow/config/istio-private_jobs/api.yaml
  prow/config/istio-private_jobs/release-builder-1.16.yaml
  prow/config/istio-private_jobs/release-builder-1.17.yaml
  prow/config/istio-private_jobs/release-builder-1.18.yaml
  prow/config/istio-private_jobs/release-builder.yaml
  prow/config/jobs_test.go
Labels: size/S, release-notes-none

#4835 release-builder: use files instead of env
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/jobs/.base.yaml
  prow/config/jobs_test.go
  tools/prowgen/pkg/spec/spec.go
Labels: size/XS, release-notes-none

#4842 Manully update 1.18 build-tools image to latest
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.18.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.18.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.18.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.18.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.18.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.18.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.18.gen.yaml
  prow/config/jobs/api-1.18.yaml
  prow/config/jobs/client-go-1.18.yaml
  prow/config/jobs/common-files-1.18.yaml
  prow/config/jobs/enhancements-1.18.yaml
  prow/config/jobs/istio-1.18.yaml
  prow/config/jobs/istio.io-1.18.yaml
  prow/config/jobs/pkg-1.18.yaml
  prow/config/jobs/proxy-1.18.yaml
  prow/config/jobs/release-builder-1.18.yaml
  prow/config/jobs/tools-1.18.yaml
  prow/config/jobs/ztunnel-1.18.yaml
Labels: size/M

#4843 Update github token description; we now use a finer scoped token
  infra/gcp/istio-prow-build/secrets.tf
Labels: size/XS, release-notes-none

#4844 sort-jobs - use prowtrans to sort by job name asc order
  prow/cluster/jobs/istio-private/envoy/istio-private.envoy.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/config/experimental/.defaults.yaml
  prow/config/istio-private_jobs/.defaults.yaml
Labels: ok-to-test, size/XS

#4846 Various fixes to release builder
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/config/jobs/.base.yaml
  prow/config/jobs/release-builder.yaml
Labels: size/S

#4847 Manually update 1.16 build-tools image to latest
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.16.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.16.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.16.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.16.gen.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/client-go-1.16.yaml
  prow/config/jobs/common-files-1.16.yaml
  prow/config/jobs/enhancements-1.16.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio.io-1.16.yaml
  prow/config/jobs/pkg-1.16.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/release-builder-1.16.yaml
  prow/config/jobs/tools-1.16.yaml
Labels: size/L

#4839 terraform: create new istio-prow-private GCP account
  infra/gcp/istio-prow-private/ar.tf
  infra/gcp/istio-prow-private/cluster.tf
  infra/gcp/istio-prow-private/iam.tf
  infra/gcp/istio-prow-private/main.tf
  infra/gcp/istio-prow-private/providers.tf
  infra/gcp/istio-prow-private/services.tf
  infra/gcp/istio-prow-private/storage.tf
  infra/gcp/modules/gke-cluster/main.tf
  infra/gcp/modules/gke-cluster/outputs.tf
  infra/gcp/modules/gke-nodepool/main.tf
  infra/gcp/modules/gke-nodepool/variables.tf
  infra/gcp/modules/workload-identity-service-account/main.tf
  infra/gcp/modules/workload-identity-service-account/variables.tf
Labels: size/L

#4848 Manually update 1.17 build-tools image to latest
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.17.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.17.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.17.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.17.gen.yaml
  prow/config/jobs/api-1.17.yaml
  prow/config/jobs/client-go-1.17.yaml
  prow/config/jobs/common-files-1.17.yaml
  prow/config/jobs/enhancements-1.17.yaml
  prow/config/jobs/istio-1.17.yaml
  prow/config/jobs/istio.io-1.17.yaml
  prow/config/jobs/pkg-1.17.yaml
  prow/config/jobs/proxy-1.17.yaml
  prow/config/jobs/release-builder-1.17.yaml
  prow/config/jobs/tools-1.17.yaml
Labels: size/L

#4849 Infra: give KMS viewer permission
  infra/gcp/istio-prow-build/keys.tf
  infra/gcp/modules/workload-identity-service-account/main.tf
Labels: size/S, release-notes-none

#4850 Document manual action required
  infra/gcp/istio-prow-private/cluster.tf
Labels: size/XS, release-notes-none

#4851 Terraform: update github token doc (new token generated)
  infra/gcp/istio-prow-build/secrets.tf
Labels: size/XS, release-notes-none

#4852 Update Prow to v20230628-f13bc80c8a
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4855 Various fixes for private cluster
  infra/gcp/istio-prow-private/iam.tf
  infra/gcp/istio-prow-private/storage.tf
  infra/gcp/modules/gke-nodepool/main.tf
  prow/cluster/jobs/all-presets.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.18.gen.yaml
  prow/config/istio-private_jobs/.defaults.yaml
  prow/config/istio-private_jobs/api-1.16.yaml
  prow/config/istio-private_jobs/api-1.17.yaml
  prow/config/istio-private_jobs/api-1.18.yaml
  prow/config/istio-private_jobs/api.yaml
  prow/config/istio-private_jobs/istio-1.16.yaml
  prow/config/istio-private_jobs/istio-1.17.yaml
  prow/config/istio-private_jobs/istio-1.18.yaml
  prow/config/istio-private_jobs/istio.yaml
  prow/config/istio-private_jobs/release-builder-1.16.yaml
  prow/config/istio-private_jobs/release-builder-1.17.yaml
  prow/config/istio-private_jobs/release-builder-1.18.yaml
  prow/config/istio-private_jobs/release-builder.yaml
  prow/config/private-presets.yaml
  tools/prowtrans/cmd/prowtrans/main.go
Labels: size/L

#4859 Private: fix envoy URL
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.18.gen.yaml
  prow/config/private-presets.yaml
Labels: size/XS, release-notes-none

#4861 Update Prow to v20230629-ca1e8ed813
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M

#4862 jobs: cleanup legacy secret-mounting job configs
  prow/cluster/build/kubernetes_external_secrets.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/api-1.17.yaml
  prow/config/jobs/api-1.18.yaml
  prow/config/jobs/client-go-1.16.yaml
  prow/config/jobs/client-go-1.17.yaml
  prow/config/jobs/client-go-1.18.yaml
  prow/config/jobs/common-files-1.16.yaml
  prow/config/jobs/common-files-1.17.yaml
  prow/config/jobs/common-files-1.18.yaml
  prow/config/jobs/enhancements-1.16.yaml
  prow/config/jobs/enhancements-1.17.yaml
  prow/config/jobs/enhancements-1.18.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio-1.17.yaml
  prow/config/jobs/istio-1.18.yaml
  prow/config/jobs/istio.io-1.16.yaml
  prow/config/jobs/istio.io-1.17.yaml
  prow/config/jobs/istio.io-1.18.yaml
  prow/config/jobs/pkg-1.16.yaml
  prow/config/jobs/pkg-1.17.yaml
  prow/config/jobs/pkg-1.18.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/proxy-1.17.yaml
  prow/config/jobs/proxy-1.18.yaml
  prow/config/jobs/release-builder-1.16.yaml
  prow/config/jobs/release-builder-1.17.yaml
  prow/config/jobs/release-builder-1.18.yaml
  prow/config/jobs/tools-1.16.yaml
  prow/config/jobs/tools-1.17.yaml
  prow/config/jobs/tools-1.18.yaml
  prow/config/jobs/ztunnel-1.18.yaml
  prow/config/jobs_test.go
Labels: size/XXL

#4857 Use new proxy override path
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.18.gen.yaml
  prow/config/istio-private_jobs/proxy-1.16.yaml
  prow/config/istio-private_jobs/proxy-1.17.yaml
  prow/config/istio-private_jobs/proxy-1.18.yaml
  prow/config/istio-private_jobs/proxy.yaml
Labels: size/XS, release-notes-none

#4863 Minimize GitHub permissions
  infra/gcp/istio-testing/iam.tf
  prow/cluster/arm/kubernetes-external-secrets_crd.yaml
  prow/cluster/arm/kubernetes-external-secrets_deployment.yaml
  prow/cluster/arm/kubernetes-external-secrets_rbac.yaml
  prow/cluster/arm/kubernetes-external-secrets_service.yaml
  prow/cluster/arm/kubernetes_external_secrets.yaml
  prow/cluster/build/kubernetes-external-secrets_crd.yaml
  prow/cluster/build/kubernetes-external-secrets_deployment.yaml
  prow/cluster/build/kubernetes-external-secrets_rbac.yaml
  prow/cluster/build/kubernetes-external-secrets_service.yaml
  prow/cluster/build/kubernetes_external_secrets.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/kubernetes_external_secrets.yaml
  prow/config/config_test.go
  prow/config/jobs/community.yaml
  prow/config/jobs_test.go
Labels: size/XL

#4856 sinker: grant WI to prow-control-plane
  infra/gcp/istio-testing/iam.tf
  prow/cluster/sinker_rbac.yaml
Labels: size/XS, release-notes-none

#4866 Fix prow-controller-manager lock permission
  prow/cluster/prow-controller-manager.yaml
Labels: size/XS, release-notes-none

#4869 Update Prow to v20230630-9eecc0f38f
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge
