Repository istio/test-infra, pull requests merged in 2023-08, with the labels that each got.

#4928 Add prowjob-bots-deployer KSA
  prow/cluster/prowjob_service_accounts.yaml
Labels: size/XS, release-notes-none

#4942 Adding 1.19 branch protection
  prow/config.yaml
Labels: size/XS

#4941 Update Prow to v20230801-2352e79673
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4944 Fix permission issue with bot deploy
  infra/gcp/istio-testing/iam.tf
Labels: size/XS

#4946 1.19 branch cut - step 3
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.19.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.19.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.19.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.19.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.19.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.19.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.19.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.19.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.19.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.19.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.19.gen.yaml
  prow/config/istio-private_jobs/api-1.19.yaml
  prow/config/istio-private_jobs/istio-1.19.yaml
  prow/config/istio-private_jobs/istio.io-1.19.yaml
  prow/config/istio-private_jobs/proxy-1.19.yaml
  prow/config/istio-private_jobs/release-builder-1.19.yaml
  prow/config/jobs/api-1.19.yaml
  prow/config/jobs/client-go-1.19.yaml
  prow/config/jobs/common-files-1.19.yaml
  prow/config/jobs/enhancements-1.19.yaml
  prow/config/jobs/istio-1.19.yaml
  prow/config/jobs/istio.io-1.19.yaml
  prow/config/jobs/proxy-1.19.yaml
  prow/config/jobs/release-builder-1.19.yaml
  prow/config/jobs/tools-1.19.yaml
  prow/config/jobs/ztunnel-1.19.yaml
  prow/config/private-presets.yaml
  testgrid/config.yaml
Labels: size/XXL

#4947 Update 1.19 proxy to pull from Envoy 1.27 branch
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.19.gen.yaml
  prow/config/jobs/proxy-1.19.yaml
Labels: size/XS

#4943 Update Prow to v20230802-d51826a399
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4948 Automator: update build-tools:release-1.18
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.18.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.18.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.18.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.18.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.18.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.18.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.18.gen.yaml
  prow/config/jobs/api-1.18.yaml
  prow/config/jobs/client-go-1.18.yaml
  prow/config/jobs/common-files-1.18.yaml
  prow/config/jobs/enhancements-1.18.yaml
  prow/config/jobs/istio-1.18.yaml
  prow/config/jobs/istio.io-1.18.yaml
  prow/config/jobs/pkg-1.18.yaml
  prow/config/jobs/proxy-1.18.yaml
  prow/config/jobs/release-builder-1.18.yaml
  prow/config/jobs/tools-1.18.yaml
  prow/config/jobs/ztunnel-1.18.yaml
Labels: size/M, release-notes-none

#4950 Fix build-tools image tag for failing release-postsubmit test
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.19.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.19.gen.yaml
  prow/config/jobs/proxy-1.19.yaml
Labels: size/XS

#4952 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4951 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4945 Automator: update build-tools:release-1.17
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.17.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.17.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.17.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.17.gen.yaml
  prow/config/jobs/api-1.17.yaml
  prow/config/jobs/client-go-1.17.yaml
  prow/config/jobs/common-files-1.17.yaml
  prow/config/jobs/enhancements-1.17.yaml
  prow/config/jobs/istio-1.17.yaml
  prow/config/jobs/istio.io-1.17.yaml
  prow/config/jobs/pkg-1.17.yaml
  prow/config/jobs/proxy-1.17.yaml
  prow/config/jobs/release-builder-1.17.yaml
  prow/config/jobs/tools-1.17.yaml
Labels: size/L, release-notes-none

#4953 Fix branch for build-tools-image job
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.19.gen.yaml
  prow/config/jobs/common-files-1.19.yaml
Labels: size/XS

#4955 Update Prow to v20230804-795d03a2b1
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4954 Automator: update build-tools:release-1.19
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.19.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.19.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.19.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.19.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.19.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.19.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.19.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.19.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.19.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.19.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.19.gen.yaml
  prow/config/jobs/api-1.19.yaml
  prow/config/jobs/client-go-1.19.yaml
  prow/config/jobs/common-files-1.19.yaml
  prow/config/jobs/enhancements-1.19.yaml
  prow/config/jobs/istio-1.19.yaml
  prow/config/jobs/istio.io-1.19.yaml
  prow/config/jobs/proxy-1.19.yaml
  prow/config/jobs/release-builder-1.19.yaml
  prow/config/jobs/tools-1.19.yaml
  prow/config/jobs/ztunnel-1.19.yaml
Labels: size/L, release-notes-none

#4958 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4959 Update Prow to v20230808-2811823aac
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4961 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4960 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4956 Automator: update build-tools:release-1.19
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.19.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.19.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.19.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.19.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.19.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.19.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.19.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.19.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.19.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.19.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.19.gen.yaml
  prow/config/jobs/api-1.19.yaml
  prow/config/jobs/client-go-1.19.yaml
  prow/config/jobs/common-files-1.19.yaml
  prow/config/jobs/enhancements-1.19.yaml
  prow/config/jobs/istio-1.19.yaml
  prow/config/jobs/istio.io-1.19.yaml
  prow/config/jobs/proxy-1.19.yaml
  prow/config/jobs/release-builder-1.19.yaml
  prow/config/jobs/tools-1.19.yaml
  prow/config/jobs/ztunnel-1.19.yaml
Labels: size/L, release-notes-none

#4962 Update Prow to v20230809-b1472a35ec
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4963 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#4964 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#4966 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4965 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4967 Update Prow to v20230810-467d785354
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4968 Update Prow to v20230811-78f080f095
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4969 Update testing to use k8s 1.28.0
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.19.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.19.gen.yaml
  prow/config/jobs/istio-1.19.yaml
  prow/config/jobs/istio.yaml
Labels: size/XS

#4970 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4971 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4972 Update Prow to v20230816-5d4b0fd3f6
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4973 Update Prow to v20230817-a7555751ac
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4974 Automator: update build-tools:release-1.19
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.19.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.19.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.19.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.19.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.19.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.19.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.19.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.19.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.19.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.19.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.19.gen.yaml
  prow/config/jobs/api-1.19.yaml
  prow/config/jobs/client-go-1.19.yaml
  prow/config/jobs/common-files-1.19.yaml
  prow/config/jobs/enhancements-1.19.yaml
  prow/config/jobs/istio-1.19.yaml
  prow/config/jobs/istio.io-1.19.yaml
  prow/config/jobs/proxy-1.19.yaml
  prow/config/jobs/release-builder-1.19.yaml
  prow/config/jobs/tools-1.19.yaml
  prow/config/jobs/ztunnel-1.19.yaml
Labels: size/L, release-notes-none

#4975 Update Prow to v20230818-271b876ddf
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4976 Update Prow to v20230819-9f6571ad1e
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4977 Update Prow to v20230822-4e1a98890b
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4978 Update Prow to v20230823-28504216ad
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4980 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4979 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4981 Update Prow to v20230824-74e8146673
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4983 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4982 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4984 Update Prow to v20230826-01e0d01366
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4987 Update Prow to v20230829-df0ee1785b
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4988 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4989 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4993 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4994 Update Prow to v20230830-eba6df1fa1
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge
