Repository istio/test-infra, pull requests merged in 2023-03, with the labels that each got.

#4604 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4603 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4605 Automator: update common-files@master in istio/test-infra@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#4607 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4606 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4608 Fix update-deps_istio_periodic
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: size/XS

#4614 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4615 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4613 Update Prow to v20230308-c4e98db091
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4598 Remove EOL jobs for istio-private organization
  prow/cluster/jobs/all-presets.yaml
  prow/cluster/private/release-deps.yaml
  prow/config/istio-private_jobs/api-1.11.yaml
  prow/config/istio-private_jobs/api-1.12.yaml
  prow/config/istio-private_jobs/api-1.13.yaml
  prow/config/istio-private_jobs/api-1.14.yaml
  prow/config/istio-private_jobs/envoy-1.11.yaml
  prow/config/istio-private_jobs/envoy-1.12.yaml
  prow/config/istio-private_jobs/envoy-1.13.yaml
  prow/config/istio-private_jobs/envoy-1.14.yaml
  prow/config/istio-private_jobs/istio-1.11.yaml
  prow/config/istio-private_jobs/istio-1.12.yaml
  prow/config/istio-private_jobs/istio-1.13.yaml
  prow/config/istio-private_jobs/istio-1.14.yaml
  prow/config/istio-private_jobs/istio.io-1.11.yaml
  prow/config/istio-private_jobs/istio.io-1.12.yaml
  prow/config/istio-private_jobs/istio.io-1.13.yaml
  prow/config/istio-private_jobs/istio.io-1.14.yaml
  prow/config/istio-private_jobs/proxy-1.11.yaml
  prow/config/istio-private_jobs/proxy-1.12.yaml
  prow/config/istio-private_jobs/proxy-1.13.yaml
  prow/config/istio-private_jobs/proxy-1.14.yaml
  prow/config/istio-private_jobs/release-builder-1.11.yaml
  prow/config/istio-private_jobs/release-builder-1.12.yaml
  prow/config/istio-private_jobs/release-builder-1.13.yaml
  prow/config/istio-private_jobs/release-builder-1.14.yaml
  prow/config/private-presets.yaml
Labels: size/XXL

#4618 Automator: update build-tools:release-1.17
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.17.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.17.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.17.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.17.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.17.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.17.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.17.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.17.gen.yaml
  prow/config/jobs/api-1.17.yaml
  prow/config/jobs/client-go-1.17.yaml
  prow/config/jobs/common-files-1.17.yaml
  prow/config/jobs/enhancements-1.17.yaml
  prow/config/jobs/istio-1.17.yaml
  prow/config/jobs/istio.io-1.17.yaml
  prow/config/jobs/pkg-1.17.yaml
  prow/config/jobs/proxy-1.17.yaml
  prow/config/jobs/release-builder-1.17.yaml
  prow/config/jobs/tools-1.17.yaml
Labels: size/L, release-notes-none

#4616 Automator: update build-tools:release-1.16
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.16.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.16.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.16.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.16.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.16.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.16.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.16.gen.yaml
  prow/config/jobs/api-1.16.yaml
  prow/config/jobs/client-go-1.16.yaml
  prow/config/jobs/common-files-1.16.yaml
  prow/config/jobs/enhancements-1.16.yaml
  prow/config/jobs/istio-1.16.yaml
  prow/config/jobs/istio.io-1.16.yaml
  prow/config/jobs/pkg-1.16.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/release-builder-1.16.yaml
  prow/config/jobs/tools-1.16.yaml
Labels: size/L, release-notes-none

#4617 Automator: update build-tools:release-1.15
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.15.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.15.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.15.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.15.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.15.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.15.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.15.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.15.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.15.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.15.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.15.gen.yaml
  prow/config/jobs/api-1.15.yaml
  prow/config/jobs/client-go-1.15.yaml
  prow/config/jobs/common-files-1.15.yaml
  prow/config/jobs/enhancements-1.15.yaml
  prow/config/jobs/istio-1.15.yaml
  prow/config/jobs/istio.io-1.15.yaml
  prow/config/jobs/pkg-1.15.yaml
  prow/config/jobs/proxy-1.15.yaml
  prow/config/jobs/release-builder-1.15.yaml
  prow/config/jobs/tools-1.15.yaml
Labels: size/L, release-notes-none

#4619 Update Prow to v20230309-adf0d41516
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4620 Separate update-deps to two jobs in isito and proxy
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
Labels: size/S

#4621 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#4623 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4622 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4625 Get istio 1.16 and istio 1.17 building
  prow/cluster/jobs/all-presets.yaml
  prow/cluster/private/release-deps.yaml
  prow/config/private-presets.yaml
Labels: size/L

#4624 Update Prow to v20230313-23dc2a84f3
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4626 Update Prow to v20230315-9f78240711
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4628 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/M, auto-merge, release-notes-none

#4627 Update Prow to v20230315-6d54c174f4
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4629 Update Prow to v20230320-bf693f37b7
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4630 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4631 Automator: update build-tools:master
  prow/cluster/jobs/all-periodics.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/cri/istio.cri.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.experimental-ambient.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/cri.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio-ambient.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#4632 Update Prow to v20230322-fad14aa00d
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4634 Update Prow to v20230324-8697ff4d24
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4635 Update Prow to v20230327-a70c782918
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4637 Update Prow to v20230328-f9f449cfb7
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4638 github-ssh-fingerprint - github changed ssh key signing
  prow/config.yaml
Labels: size/XS

#4600 Update to v1 of ManagedCertificate resource
  prow/cluster/gcsweb/gcsweb-istio-io_managedcertificate.yaml
  prow/cluster/monitoring/grafana_expose.yaml
  prow/cluster/private/prow-private-istio-io_managedcertificate.yaml
  prow/cluster/prow-istio-io_managedcertificate.yaml
Labels: size/S

#4640 Allow org for automator to be configurable in prow jobs
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/pkg.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
Labels: size/M

#4639 Update Prow to v20230328-15a98b0443
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4645 Update release-test job to a 6hr time limit
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.15.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/config/jobs/proxy-1.15.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/proxy-1.17.yaml
  prow/config/jobs/proxy.yaml
Labels: size/M

#4646 Changed postsubmit timeouts for release jobs to 6h
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.15.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.17.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/config/jobs/proxy-1.15.yaml
  prow/config/jobs/proxy-1.16.yaml
  prow/config/jobs/proxy-1.17.yaml
  prow/config/jobs/proxy.yaml
Labels: size/S

#4644 Update Prow to v20230329-c93d79fb7d
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#4642 Adding prow-arm-private config.
  prow/Makefile
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/gencred-config/gencred-config.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/kubernetes_external_secrets.yaml
  prow/cluster/private-arm/authentikos_deployment.yaml
  prow/cluster/private-arm/authentikos_rbac.yaml
  prow/cluster/private-arm/gitconfig.yaml
  prow/cluster/private-arm/kubernetes-external-secrets_crd.yaml
  prow/cluster/private-arm/kubernetes-external-secrets_deployment.yaml
  prow/cluster/private-arm/kubernetes-external-secrets_rbac.yaml
  prow/cluster/private-arm/kubernetes-external-secrets_service.yaml
  prow/cluster/private-arm/kubernetes_external_secrets.yaml
  prow/cluster/private-arm/prowjob_service_accounts.yaml
  prow/cluster/private-arm/test_pod_namespace.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/config/istio-private_jobs/.defaults.yaml
  prow/config/istio-private_jobs/istio.yaml
Labels: size/XL

#4647 Fixing release configs
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.17.gen.yaml
  prow/config/istio-private_jobs/istio-1.15.yaml
  prow/config/istio-private_jobs/istio-1.16.yaml
  prow/config/istio-private_jobs/istio-1.17.yaml
Labels: size/M

#4648 private: fix arm cluster
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.15.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.16.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.17.gen.yaml
  prow/cluster/kubernetes_external_secrets.yaml
  prow/config/istio-private_jobs/proxy-1.15.yaml
  prow/config/istio-private_jobs/proxy-1.16.yaml
  prow/config/istio-private_jobs/proxy-1.17.yaml
  prow/config/istio-private_jobs/proxy.yaml
Labels: size/M
