Repository istio/test-infra, pull requests merged in 2024-10, with the labels that each got.

#5488 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5495 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5496 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5498 Automator: update build-tools:release-1.23
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.release-0.1.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.23.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.23.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.23.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.23.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.23.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.23.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.23.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.23.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.23.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.23.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.23.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.23.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.23.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.23.gen.yaml
  prow/config/jobs/api-1.23.yaml
  prow/config/jobs/client-go-1.23.yaml
  prow/config/jobs/common-files-1.23.yaml
  prow/config/jobs/enhancements-1.23.yaml
  prow/config/jobs/istio-1.23.yaml
  prow/config/jobs/istio.io-1.23.yaml
  prow/config/jobs/proxy-1.23.yaml
  prow/config/jobs/release-builder-1.23.yaml
  prow/config/jobs/sail-operator-release-0.1.yaml
  prow/config/jobs/tools-1.23.yaml
  prow/config/jobs/ztunnel-1.23.yaml
Labels: size/L, release-notes-none

#5499 remove 1.21
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.21.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.21.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.21.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.21.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.21.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.21.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.21.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.21.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.21.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.21.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.21.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.21.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.21.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.21.gen.yaml
  prow/config/istio-private_jobs/api-1.21.yaml
  prow/config/istio-private_jobs/istio-1.21.yaml
  prow/config/istio-private_jobs/istio.io-1.21.yaml
  prow/config/istio-private_jobs/proxy-1.21.yaml
  prow/config/istio-private_jobs/release-builder-1.21.yaml
  prow/config/jobs/api-1.21.yaml
  prow/config/jobs/client-go-1.21.yaml
  prow/config/jobs/common-files-1.21.yaml
  prow/config/jobs/enhancements-1.21.yaml
  prow/config/jobs/istio-1.21.yaml
  prow/config/jobs/istio.io-1.21.yaml
  prow/config/jobs/proxy-1.21.yaml
  prow/config/jobs/release-builder-1.21.yaml
  prow/config/jobs/tools-1.21.yaml
  prow/config/jobs/ztunnel-1.21.yaml
  testgrid/config.yaml
Labels: size/XXL

#5500 Add dualStack tests in Sail Operator
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/config/jobs/sail-operator.yaml
Labels: size/S

#5501 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5503 sail-operator: move automator job to github actions
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/config.yaml
  prow/config/jobs/sail-operator.yaml
  testgrid/config.yaml
Labels: size/S

#5504 Manual: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M

#5505 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5502 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5506 Rename Sail Operator dualStack job
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/config/jobs/sail-operator.yaml
Labels: size/XS

#5508 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5509 Add branch protection for release-1.24
  prow/config.yaml
Labels: size/XS

#5510 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#5512 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5511 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5514 Bump prow images
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M

#5513 Add prow configs for 1.24 branch
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.24.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.24.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.24.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.24.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.24.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.24.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.24.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.24.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.24.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.24.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.24.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.24.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.24.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.24.gen.yaml
  prow/config/istio-private_jobs/api-1.24.yaml
  prow/config/istio-private_jobs/istio-1.24.yaml
  prow/config/istio-private_jobs/istio.io-1.24.yaml
  prow/config/istio-private_jobs/proxy-1.24.yaml
  prow/config/istio-private_jobs/release-builder-1.24.yaml
  prow/config/jobs/api-1.24.yaml
  prow/config/jobs/client-go-1.24.yaml
  prow/config/jobs/common-files-1.24.yaml
  prow/config/jobs/enhancements-1.24.yaml
  prow/config/jobs/istio-1.24.yaml
  prow/config/jobs/istio.io-1.24.yaml
  prow/config/jobs/proxy-1.24.yaml
  prow/config/jobs/release-builder-1.24.yaml
  prow/config/jobs/tools-1.24.yaml
  prow/config/jobs/ztunnel-1.24.yaml
  prow/config/private-presets.yaml
  testgrid/config.yaml
Labels: size/XXL

#5516 Automator: update build-tools:release-1.24
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.24.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.24.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.24.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.24.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.24.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.24.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.24.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.24.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.24.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.24.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.24.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.24.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.24.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.24.gen.yaml
  prow/config/jobs/api-1.24.yaml
  prow/config/jobs/client-go-1.24.yaml
  prow/config/jobs/common-files-1.24.yaml
  prow/config/jobs/enhancements-1.24.yaml
  prow/config/jobs/istio-1.24.yaml
  prow/config/jobs/istio.io-1.24.yaml
  prow/config/jobs/proxy-1.24.yaml
  prow/config/jobs/release-builder-1.24.yaml
  prow/config/jobs/tools-1.24.yaml
  prow/config/jobs/ztunnel-1.24.yaml
Labels: size/L, release-notes-none

#5518 Update to latest 1.32 alpha build
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.24.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.24.gen.yaml
  prow/config/jobs/istio-1.24.yaml
  prow/config/jobs/istio.yaml
Labels: size/XS, release-notes-none
