Repository istio/test-infra, pull requests merged in 2024-06, with the labels that each got.

#5380 Add release deps for 1.22 private branch
  prow/cluster/private/release-deps.yaml
Labels: size/M, release-notes-none

#5381 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/S, auto-merge, release-notes-none

#5383 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5382 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5384 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5385 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5386 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#5389 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5388 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5390 Update Prow to v20240611-924d31f0c
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5391 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5396 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5395 prow: Add new C3 pool
  infra/gcp/istio-prow-build/cluster-prow.tf
  infra/gcp/istio-prow-build/keys.tf
Labels: size/M, release-notes-none

#5387 Automator: update build-tools:release-1.20
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.20.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.20.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.20.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.20.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.20.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.20.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.20.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.20.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.20.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.20.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.20.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.20.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.20.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.20.gen.yaml
  prow/config/jobs/api-1.20.yaml
  prow/config/jobs/client-go-1.20.yaml
  prow/config/jobs/common-files-1.20.yaml
  prow/config/jobs/enhancements-1.20.yaml
  prow/config/jobs/istio-1.20.yaml
  prow/config/jobs/istio.io-1.20.yaml
  prow/config/jobs/proxy-1.20.yaml
  prow/config/jobs/release-builder-1.20.yaml
  prow/config/jobs/tools-1.20.yaml
  prow/config/jobs/ztunnel-1.20.yaml
Labels: size/S, release-notes-none

#5393 Automator: update build-tools:release-1.22
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.22.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.22.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.22.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.22.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.22.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.22.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.22.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.22.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.22.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.22.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.22.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.22.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.22.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.22.gen.yaml
  prow/config/jobs/api-1.22.yaml
  prow/config/jobs/client-go-1.22.yaml
  prow/config/jobs/common-files-1.22.yaml
  prow/config/jobs/enhancements-1.22.yaml
  prow/config/jobs/istio-1.22.yaml
  prow/config/jobs/istio.io-1.22.yaml
  prow/config/jobs/proxy-1.22.yaml
  prow/config/jobs/release-builder-1.22.yaml
  prow/config/jobs/tools-1.22.yaml
  prow/config/jobs/ztunnel-1.22.yaml
Labels: size/L, release-notes-none

#5392 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5397 Update Prow to v20240614-1530389fc
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M

#5398 Update Prow to v20240614-e4ae242d1
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M

#5399 Adds jobs for sail-operator release-0.1 branch
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.release-0.1.gen.yaml
  prow/config.yaml
  prow/config/jobs/sail-operator-release-0.1.yaml
  testgrid/config.yaml
Labels: ok-to-test, size/M

#5402 make ambient docs test job mandatory
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/config/jobs/istio.io.yaml
Labels: size/XS

#5403 Update Prow to v20240619-cfb8754e0
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5404 Update Prow to v20240624-6accc2e16
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5406 Update Prow to v20240625-266ce07da
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5408 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5401 add ambient ipv6 integ-test job
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/config/jobs/istio.yaml
Labels: size/S

#5410 add ambient profile docs test for 1.22
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.22.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.22.gen.yaml
  prow/config/jobs/istio.io-1.22.yaml
Labels: size/L

#5411 Make docs dual stack job mandatory
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/config/jobs/istio.io.yaml
Labels: size/XS

#5412 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#5413 Update token expiration time comment
  infra/gcp/istio-prow-build/secrets.tf
Labels: size/XS, release-notes-none

#5414 temporarily skip helm tests
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/config/jobs/istio.yaml
Labels: size/XS, release-notes-none

#5415 Update Prow to v20240627-79d27b6e3
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5417 Revert "temporarily skip helm tests"
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/config/jobs/istio.yaml
Labels: size/XS

#5407 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5416 Make ambient-ipv6 mandatory presubmit job
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/config/jobs/istio.yaml
Labels: size/XS
