Repository istio/test-infra, pull requests merged in 2024-01, with the labels that each got.

#5132 Bump github.com/go-git/go-git/v5 from 5.4.2 to 5.11.0 with gen
  go.mod
  go.sum
  licenses/dario.cat/mergo/LICENSE
  licenses/github.com/cloudflare/circl/LICENSE
  licenses/github.com/cloudflare/circl/ecc/p384/LICENSE
  licenses/github.com/cyphar/filepath-securejoin/LICENSE
  licenses/github.com/mitchellh/go-homedir/LICENSE
  licenses/github.com/pjbgf/sha1cd/LICENSE
  licenses/github.com/skeema/knownhosts/LICENSE
Labels: size/XL

#5133 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5135 Sort all generated jobs for istio repos in ascending order
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.18.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.19.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.20.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.18.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.19.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.20.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.19.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.20.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.19.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.20.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.18.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.19.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.20.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.18.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.19.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.20.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.18.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.19.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.20.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.18.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.19.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.20.gen.yaml
  tools/prowgen/Dockerfile
  tools/prowgen/cmd/prowgen/main.go
  tools/prowgen/pkg/generate.go
  tools/prowgen/pkg/testdata/.base.yaml
  tools/prowgen/pkg/testdata/matrix.gen.yaml
  tools/prowgen/pkg/testdata/simple.gen.yaml
Labels: size/XS

#5136 Update Prow to v20240102-43c89140b5
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5137 Remove 1.18 jobs
  prow/cluster/jobs/istio-private/api/istio-private.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.18.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.18.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.18.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.18.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.18.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.18.gen.yaml
  prow/cluster/jobs/istio/pkg/istio.pkg.release-1.18.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.18.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.18.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.18.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.18.gen.yaml
  prow/cluster/private/release-deps.yaml
  prow/config/istio-private_jobs/api-1.18.yaml
  prow/config/istio-private_jobs/istio-1.18.yaml
  prow/config/istio-private_jobs/istio.io-1.18.yaml
  prow/config/istio-private_jobs/proxy-1.18.yaml
  prow/config/istio-private_jobs/release-builder-1.18.yaml
  prow/config/jobs/api-1.18.yaml
  prow/config/jobs/client-go-1.18.yaml
  prow/config/jobs/common-files-1.18.yaml
  prow/config/jobs/enhancements-1.18.yaml
  prow/config/jobs/istio-1.18.yaml
  prow/config/jobs/istio.io-1.18.yaml
  prow/config/jobs/pkg-1.18.yaml
  prow/config/jobs/proxy-1.18.yaml
  prow/config/jobs/release-builder-1.18.yaml
  prow/config/jobs/tools-1.18.yaml
  prow/config/jobs/ztunnel-1.18.yaml
  prow/config/private-presets.yaml
  testgrid/config.yaml
Labels: size/XXL

#5139 Add Kubernetes 1.29 support for Istio 1.20 and master
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.20.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.20.gen.yaml
  prow/config/jobs/istio-1.20.yaml
Labels: size/L

#5141 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5138 Update Prow to v20240104-724ea5f0dc
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5140 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5142 Update Prow to v20240105-8718b1383a
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5143 Remove istio/pkg as a depdency
  prow/cluster/private/release-deps.yaml
Labels: size/XS

#5145 Update Prow to v20240108-49228c2a7e
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5146 Update Prow to v20240109-a3102cd4a9
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5148 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5151 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5147 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5149 Automator: update build-tools:release-1.19
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.19.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.19.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.19.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.19.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.19.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.19.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.19.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.19.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.19.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.19.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.19.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.19.gen.yaml
  prow/config/jobs/api-1.19.yaml
  prow/config/jobs/client-go-1.19.yaml
  prow/config/jobs/common-files-1.19.yaml
  prow/config/jobs/enhancements-1.19.yaml
  prow/config/jobs/istio-1.19.yaml
  prow/config/jobs/istio.io-1.19.yaml
  prow/config/jobs/proxy-1.19.yaml
  prow/config/jobs/release-builder-1.19.yaml
  prow/config/jobs/tools-1.19.yaml
  prow/config/jobs/ztunnel-1.19.yaml
Labels: size/L, release-notes-none

#5150 Automator: update build-tools:release-1.20
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.20.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.20.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.20.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.20.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.20.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.20.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.20.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.20.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.20.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.20.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.20.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.20.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.20.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.20.gen.yaml
  prow/config/jobs/api-1.20.yaml
  prow/config/jobs/client-go-1.20.yaml
  prow/config/jobs/common-files-1.20.yaml
  prow/config/jobs/enhancements-1.20.yaml
  prow/config/jobs/istio-1.20.yaml
  prow/config/jobs/istio.io-1.20.yaml
  prow/config/jobs/proxy-1.20.yaml
  prow/config/jobs/release-builder-1.20.yaml
  prow/config/jobs/tools-1.20.yaml
  prow/config/jobs/ztunnel-1.20.yaml
Labels: size/S, release-notes-none

#5152 Update Prow to v20240110-67612f6b02
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5153 Update Prow to v20240111-4df3614954
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5154 Update Prow to v20240112-522878393d
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5155 Automator: update build-tools:release-1.20
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.20.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.20.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.20.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.20.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.20.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.20.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.20.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.20.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.20.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.20.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.20.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.20.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.20.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.20.gen.yaml
  prow/config/jobs/api-1.20.yaml
  prow/config/jobs/client-go-1.20.yaml
  prow/config/jobs/common-files-1.20.yaml
  prow/config/jobs/enhancements-1.20.yaml
  prow/config/jobs/istio-1.20.yaml
  prow/config/jobs/istio.io-1.20.yaml
  prow/config/jobs/proxy-1.20.yaml
  prow/config/jobs/release-builder-1.20.yaml
  prow/config/jobs/tools-1.20.yaml
  prow/config/jobs/ztunnel-1.20.yaml
Labels: size/S, release-notes-none

#5156 Update Prow to v20240113-a5b27f3c7e
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5159 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5158 Bump test-infra dependency to master
  go.mod
  go.sum
  licenses/github.com/cjwagner/httpcache/LICENSE.txt
  licenses/github.com/google/s2a-go/LICENSE.md
  licenses/google.golang.org/appengine/LICENSE
  prow/config/jobs_test.go
  tools/prowgen/cmd/prowgen/main.go
  tools/prowgen/go.mod
  tools/prowgen/go.sum
  tools/prowgen/pkg/decorator/requirement.go
  tools/prowtrans/cmd/prowtrans/main.go
Labels: size/XXL, release-notes-none

#5157 Update Prow to v20240115-9aef1f17dc
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5160 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5161 Update Prow to v20240116-9788709fc1
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5164 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5165 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5163 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5166 Revert "Automator: update build-tools:master"
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M

#5167 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5168 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5170 step2 branch protection for 1.21
  prow/config.yaml
Labels: size/XS

#5169 Update Prow to v20240122-427eba29a5
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5173 Update proxy image to use release-1.21
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.21.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.21.gen.yaml
  prow/config/jobs/api-1.21.yaml
  prow/config/jobs/proxy-1.21.yaml
Labels: size/XS

#5174 fix wrong script
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.21.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.21.gen.yaml
  prow/config/jobs/proxy-1.21.yaml
Labels: size/XS

#5175 Automator: update build-tools:release-1.21
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.21.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.21.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.21.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.21.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.21.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.21.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.21.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.21.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.21.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.21.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.21.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.21.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.21.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.21.gen.yaml
  prow/config/jobs/api-1.21.yaml
  prow/config/jobs/client-go-1.21.yaml
  prow/config/jobs/common-files-1.21.yaml
  prow/config/jobs/enhancements-1.21.yaml
  prow/config/jobs/istio-1.21.yaml
  prow/config/jobs/istio.io-1.21.yaml
  prow/config/jobs/proxy-1.21.yaml
  prow/config/jobs/release-builder-1.21.yaml
  prow/config/jobs/tools-1.21.yaml
  prow/config/jobs/ztunnel-1.21.yaml
Labels: size/S, release-notes-none

#5176 Update BASE_IMAGE version for release 1.21
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.21.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.21.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.21.gen.yaml
  prow/config/jobs/enhancements-1.21.yaml
  prow/config/jobs/istio-1.21.yaml
  prow/config/jobs/tools-1.21.yaml
Labels: size/XS

#5179 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5178 Automator: update build-tools:master
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5180 Update Prow to v20240126-4a8e72f766
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5182 Update Prow to v20240126-fda91e14e6
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5183 add missing release-deps cm for 1.20 and 1.21
  prow/cluster/private/release-deps.yaml
Labels: size/L

#5185 Update Prow to v20240130-12d69bd5cb
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5187 Update Prow to v20240131-27b33826e4
  .prow.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/deck_private_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow-controller-manager.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/M, auto-merge

#5188 Automator: update common-files@master in istio/test-infra@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none
