Repository istio/test-infra, pull requests merged in 2025-04, with the labels that each got.

#5634 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5633 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5635 Add sail-operator release-1.25
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.release-1.25.gen.yaml
  prow/config.yaml
  prow/config/jobs/sail-operator-release-1.25.yaml
  testgrid/config.yaml
Labels: ok-to-test, size/M

#5637 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5636 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5639 Automator: update build-tools:release-1.23
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.release-0.1.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.23.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.23.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.23.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.23.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.23.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.23.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.23.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.23.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.23.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.23.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.23.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.23.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.23.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.23.gen.yaml
  prow/config/jobs/api-1.23.yaml
  prow/config/jobs/client-go-1.23.yaml
  prow/config/jobs/common-files-1.23.yaml
  prow/config/jobs/enhancements-1.23.yaml
  prow/config/jobs/istio-1.23.yaml
  prow/config/jobs/istio.io-1.23.yaml
  prow/config/jobs/proxy-1.23.yaml
  prow/config/jobs/release-builder-1.23.yaml
  prow/config/jobs/sail-operator-release-0.1.yaml
  prow/config/jobs/tools-1.23.yaml
  prow/config/jobs/ztunnel-1.23.yaml
Labels: size/L, release-notes-none

#5640 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5641 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/format_go.sh
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
Labels: size/XL, auto-merge, release-notes-none

#5642 add dhawton to infra admins
  infra/gcp/common.tf
Labels: size/XS

#5644 Add new job for sail operator: automated docs testing
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/config/jobs/sail-operator.yaml
Labels: ok-to-test, size/XS

#5647 [release 1.26] branch cut step 3
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.26.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.26.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.26.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.26.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.26.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.26.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.26.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.26.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.26.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.26.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.26.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.26.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.26.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.26.gen.yaml
  prow/config/istio-private_jobs/api-1.26.yaml
  prow/config/istio-private_jobs/istio-1.26.yaml
  prow/config/istio-private_jobs/istio.io-1.26.yaml
  prow/config/istio-private_jobs/proxy-1.26.yaml
  prow/config/istio-private_jobs/release-builder-1.26.yaml
  prow/config/jobs/api-1.26.yaml
  prow/config/jobs/client-go-1.26.yaml
  prow/config/jobs/common-files-1.26.yaml
  prow/config/jobs/enhancements-1.26.yaml
  prow/config/jobs/istio-1.26.yaml
  prow/config/jobs/istio.io-1.26.yaml
  prow/config/jobs/proxy-1.26.yaml
  prow/config/jobs/release-builder-1.26.yaml
  prow/config/jobs/tools-1.26.yaml
  prow/config/jobs/ztunnel-1.26.yaml
  prow/config/private-presets.yaml
  testgrid/config.yaml
Labels: size/XXL

#5646 Add release-1.26 branch protection
  prow/config.yaml
Labels: size/S

#5648 Add jobs for ambient multicluster
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/config/jobs/istio.yaml
Labels: size/S

#5649 [release-1.26] update automator proxy branch
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.26.gen.yaml
  prow/config/jobs/proxy-1.26.yaml
Labels: size/XS

#5650 Fixup ambient multicluster tests with a new topology
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/config/jobs/istio.yaml
Labels: size/XS

#5651 Fix formatting
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/config/jobs/istio.yaml
Labels: size/XS

#5652 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5653 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5655 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5654 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5656 add Keith to tf admins to be able to release for experimental branches
  infra/gcp/common.tf
Labels: size/XS
