Repository istio/test-infra, pull requests merged in 2025-07, with the labels that each got.

#5690 update Slack URL
  infra/gcp/istio-io/run.tf
Labels: size/XS

#5691 Add release-1.27 branch protection
  prow/config.yaml
Labels: size/XS

#5692 [release-1.27] Automated branching step 3
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.27.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.27.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.27.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.27.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.27.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.27.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.27.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.27.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.27.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.27.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.27.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.27.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.27.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.27.gen.yaml
  prow/config/istio-private_jobs/api-1.27.yaml
  prow/config/istio-private_jobs/istio-1.27.yaml
  prow/config/istio-private_jobs/istio.io-1.27.yaml
  prow/config/istio-private_jobs/proxy-1.27.yaml
  prow/config/istio-private_jobs/release-builder-1.27.yaml
  prow/config/jobs/api-1.27.yaml
  prow/config/jobs/client-go-1.27.yaml
  prow/config/jobs/common-files-1.27.yaml
  prow/config/jobs/enhancements-1.27.yaml
  prow/config/jobs/istio-1.27.yaml
  prow/config/jobs/istio.io-1.27.yaml
  prow/config/jobs/proxy-1.27.yaml
  prow/config/jobs/release-builder-1.27.yaml
  prow/config/jobs/tools-1.27.yaml
  prow/config/jobs/ztunnel-1.27.yaml
  prow/config/private-presets.yaml
  testgrid/config.yaml
Labels: size/XXL

#5695 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5696 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5698 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#5703 resolve dependabot prs
  authentikos/go.mod
  authentikos/go.sum
  go.mod
  go.sum
  tools/prowgen/go.mod
  tools/prowgen/go.sum
Labels: size/L

#5705 Indicate new expiration date for token
  infra/gcp/istio-prow-build/secrets.tf
Labels: size/XS

#5709 fix wrong UPDATE_BRANCH
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.27.gen.yaml
  prow/config/jobs/proxy-1.27.yaml
  prow/config/jobs/proxy.yaml
Labels: size/XS
