Repository istio/test-infra, pull requests merged in 2025-01, with the labels that each got.

#5557 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5558 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5561 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5563 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5562 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5566 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5567 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5568 sail-operator: remove duplicate unit/integ tests runs
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/config/jobs/sail-operator.yaml
Labels: size/XS

#5569 update image
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M

#5570 Automator: update build-tools:release-1.24
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.release-0.2.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.release-1.24.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.release-1.24.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.release-1.24.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.release-1.24.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.release-1.24.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.release-1.24.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.release-1.24.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.release-1.24.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.release-1.24.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.release-1.24.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.release-1.24.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.release-1.24.gen.yaml
  prow/cluster/jobs/istio/tools/istio.tools.release-1.24.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.release-1.24.gen.yaml
  prow/config/jobs/api-1.24.yaml
  prow/config/jobs/client-go-1.24.yaml
  prow/config/jobs/common-files-1.24.yaml
  prow/config/jobs/enhancements-1.24.yaml
  prow/config/jobs/istio-1.24.yaml
  prow/config/jobs/istio.io-1.24.yaml
  prow/config/jobs/proxy-1.24.yaml
  prow/config/jobs/release-builder-1.24.yaml
  prow/config/jobs/sail-operator-release-0.2.yaml
  prow/config/jobs/tools-1.24.yaml
  prow/config/jobs/ztunnel-1.24.yaml
Labels: size/L, release-notes-none

#5571 Introduce IP_FAMILIES for integration tests
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
Labels: size/S

#5575 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5572 Remove IP_FAMILY env in favor of IP_FAMILIES
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
Labels: size/S

#5576 Make integ-ambient-ipv6 a mandatory presubmit job
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/config/jobs/istio.yaml
Labels: size/XS

#5577 sail-operator: create release-1.0 branch
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.release-1.0.gen.yaml
  prow/config/jobs/sail-operator-release-1.0.yaml
  testgrid/config.yaml
Labels: size/M

#5579 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5578 Automator: update build-tools:master
  prow/cluster/jobs/istio-ecosystem/sail-operator/istio-ecosystem.sail-operator.main.gen.yaml
  prow/cluster/jobs/istio-private/api/istio-private.api.master.gen.yaml
  prow/cluster/jobs/istio-private/istio.io/istio-private.istio.io.master.gen.yaml
  prow/cluster/jobs/istio-private/istio/istio-private.istio.master.gen.yaml
  prow/cluster/jobs/istio-private/proxy/istio-private.proxy.master.gen.yaml
  prow/cluster/jobs/istio-private/release-builder/istio-private.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/api/istio.api.master.gen.yaml
  prow/cluster/jobs/istio/bots/istio.bots.master.gen.yaml
  prow/cluster/jobs/istio/client-go/istio.client-go.master.gen.yaml
  prow/cluster/jobs/istio/common-files/istio.common-files.master.gen.yaml
  prow/cluster/jobs/istio/community/istio.community.master.gen.yaml
  prow/cluster/jobs/istio/enhancements/istio.enhancements.master.gen.yaml
  prow/cluster/jobs/istio/istio.io/istio.istio.io.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/cluster/jobs/istio/istio/istio.istioexperimental.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxy.master.gen.yaml
  prow/cluster/jobs/istio/proxy/istio.proxyexperimental.gen.yaml
  prow/cluster/jobs/istio/release-builder/istio.release-builder.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml
  prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
  prow/cluster/jobs/istio/tools/istio.tools.master.gen.yaml
  prow/cluster/jobs/istio/ztunnel/istio.ztunnel.master.gen.yaml
  prow/config/jobs/api.yaml
  prow/config/jobs/bots.yaml
  prow/config/jobs/client-go.yaml
  prow/config/jobs/common-files.yaml
  prow/config/jobs/community.yaml
  prow/config/jobs/enhancements.yaml
  prow/config/jobs/istio.io.yaml
  prow/config/jobs/istio.yaml
  prow/config/jobs/proxy.yaml
  prow/config/jobs/release-builder.yaml
  prow/config/jobs/sail-operator.yaml
  prow/config/jobs/test-infra.yaml
  prow/config/jobs/tools.yaml
  prow/config/jobs/ztunnel.yaml
Labels: size/M, release-notes-none

#5580 Automator: update common-files@master in istio/test-infra@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5583 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#5584 Fix failing update-go-control-plane job
  prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml
  prow/config/jobs/istio.yaml
Labels: size/XS

#5585 Automator: update common-files@master in istio/test-infra@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#5588 nil check os.DirEntry before checking d.IsDir in callback
  tools/prowgen/cmd/prowgen/main.go
Labels: size/S

#5590 Fix command parsing for prow commands
  tools/generate-transform-jobs/main.go
  tools/prowgen/cmd/prowgen/main.go
Labels: size/XS
